### ISSUE TITLE
Custom action arguments are treated as identical while defining action (when they are different)

### ISSUE THREAD

**Issue by mlafuentem** [FlutterFlow/flutterflow-issues#1066]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A custom action with four different arguments is applied onto a button. While defining the on-tap action and trying to pass in the arguments to the action, two of these arguments ('questionID' and 'answer') are treated as identical when they are actually different. When I fill in one of these arguments, the other is automatically filled in with the same value as the first one.

### Expected Behavior

The platform should allow giving two distinct values to the arguments 'questionID' and 'answer' of the custom action.

### Steps to Reproduce

1. Create a custom action with this code: '// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'package:cloud_firestore/cloud_firestore.dart';
import '/auth/firebase_auth/auth_util.dart';

Future<void> submitChallengeText(BuildContext context, String userID,
    String challengeID, String questionID, String answer) async {
  try {
    // Get a reference to the Firestore service
    final db = FirebaseFirestore.instance;

    // Get a reference to the subcollection
    final subcollectionRef =
        db.collection('users/$userID/challenge_submissions');

    // Create a document with the challengeID, questionID, the answer, submissionType, userID, and the current date
    await subcollectionRef.add({
      'challengeID': challengeID,
      'questionID': questionID,
      'submissionContent': answer,
      'submissionType': 'text',
      'userID': userID,
      'created': Timestamp.now(),
    });
  } catch (e) {
    // Show a Snackbar with the error message
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
        content: Text('An error occurred while recording the entry: $e')));
    // Rethrow the exception
    throw e;
  }
}'
2. Create a new page
3. Create a button on the page
4. Define an action on the button, custom actions, and select the custom action defined in step 1
5. Fill in the arguments (arguments 3 and 4 are treated as identical)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gl/Lcw5NIm8tb7qXyb+9WpDwXG1w8aL00st5Hd0gdCOPrBuwAYMn4blRtZOnjaVNfPlCl+WIG3NrKhdjxMvBdNRSaY4B+z4dyUTvee2ihVpSaCZOOfnBRLJhTIW3E356V2CNNLvhZLl48wzquCPK9ST/DBOu/Zwh9f6PHaOI=

### Context

I'm trying to write onto Firebase the answers of users along with its timestamp, etc., so I must use an argument to identify the question that is being answered (there are many). Without solving this, I cannot properly add a new document to my firebase to record the answer of the user.

### Visual documentation

![im1](https://github.com/FlutterFlow/flutterflow-issues/assets/60664735/c74428d7-a745-4178-912b-6c1070e75f45)

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.10.4
- Platform: Web
- Browser name and version: Chrome 114.0.5735.135 (Build oficial) (64 bits)
- Operating system and version affected: Windows 11 Pro
```

**Comment by SameerShahzad99** [comment]
@mlafuentem Thank you for submitting this bug, I can reproduce this problem on your project specifically!

**Comment by SameerShahzad99** [comment]
@SamVdvd Can you please share the bug report code, So i could test?

**Comment by SamVdvd** [comment]
“bug report code”, do you mean the code of the complete project?

Van: SameerShahzad99 ***@***.***>
Verzonden: dinsdag 4 juli 2023 16:08
Aan: FlutterFlow/flutterflow-issues ***@***.***>
CC: Sam Vandevelde ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [FlutterFlow/flutterflow-issues] Custom action arguments are treated as identical while defining action (when they are different) (Issue #1066)

EXTERNE MAIL: Open enkel attachments of hyperlinks indien u de afzender vertrouwt.


@SamVdvd<https://github.com/SamVdvd> Can you please share the bug report code, So i could test?

**Comment by SamVdvd** [comment]
found it: IT4SzfHqw5B2ofVK0L6JcfpV+SUvJjs/a7gZju1AEAEdB7arPIkfXOjASEhVXd+/TAl2Ilu0rGYxw/eLuPPQVuQHAw+tG9Q7z8xUbxbjRjmuR4SmEamORXYlI/hVHkuV16SR3SNvOvNoLHg8wFyEAO/KExbaGKGyNno/HvyZEJ/4pF6ZAi+6Xn0Jg1ZSfCvr

**Comment by SamVdvd** [comment]
I created a small test-project with only one screen and one action, same problem there (maybe easier to debug). Bug report code of that project: ITFfz/Hqx891mNte14SJK/lWoGYRNVMcTIMziNZ+exUbfaL1BuwQZeLSTBJDTeaqaVNcIWaYklsd082Pv4TUVvIDBwSbRphxzpduEg7ke2imVYzWO4eOfXYkGcNMGmK518PUuBN+G7JiZV492V2yOt+XQg3DFOu/Zwh9f6PHaOI=

**Comment by SamVdvd** [comment]
Any update on this yet? This problem is blocking our project.

**Comment by vishalagarwal2** [comment]
Hi the issue has been fixed and will be available on our next deploy

**Comment by mlafuentem** [comment]
Thanks for the update!!

**Comment by SamVdvd** [comment]
This issue is partially fixed, not completely. I can now change the action arguments independently but these changes are not saved. See zipped screen video
[Bezig met opnemen 2023-08-09 133705.zip](https://github.com/FlutterFlow/flutterflow-issues/files/12302143/Bezig.met.opnemen.2023-08-09.133705.zip)

**Comment by SamVdvd** [comment]
Hi Vishal

This issue is partially fixed, not completely. I can now change the action arguments independently but these changes are not saved. See zipped screen video on Github.

Sam

Van: Vishal Agarwal ***@***.***>
Verzonden: woensdag 2 augustus 2023 20:10
Aan: FlutterFlow/flutterflow-issues ***@***.***>
CC: Sam Vandevelde ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [FlutterFlow/flutterflow-issues] Custom action arguments are treated as identical while defining action (when they are different) (Issue #1066)

EXTERNE MAIL: Open enkel attachments of hyperlinks indien u de afzender vertrouwt.


Hi the issue has been fixed and will be available on our next deploy

**Comment by vishalagarwal2** [comment]
https://github.com/FlutterFlow/flutterflow-issues/assets/63578295/e8883ac6-14ea-41d5-8a34-71b4a2d89027

Hi, I just tried using a custom action and it seems to work as expected. Attached a video reference. Let me know if you're still facing the issue and if so please share your project link so I can take a closer look.
