### ISSUE TITLE
App not working in Android 12 / 13

### ISSUE THREAD

**Issue by samhepburn-hiya** [FlutterFlow/flutterflow-issues#1236]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We have developed an app using FlutterFlow (https://app.flutterflow.io/project/hiya-axde0c). When the app is run on an Android 12 or 13 device the screen goes green (the primary colour) and no further functionality is possible. 

When checking the emulator logs, the following trace was observed:
```
E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(flutter_stripe initialization failed, The plugin failed to initialize:\
                                                                                                    Your theme isn't set to use Theme.AppCompat or Theme.MaterialComponents.\
                                                                                                    Please make sure you follow all the steps detailed inside the README: https://github.com/flutter-stripe/flutter_stripe#android\
                                                                                                    If you continue to have trouble, follow this discussion to get some support https://github.com/flutter-stripe/flutter_stripe/discussions/538, null, null)\
                                                                                                    #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:171)\
                                                                                                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)\
                                                                                                    <asynchronous suspension>\
                                                                                                    #2      MethodChannelStripe.initialise (package:stripe_platform_interface/src/method_channel_stripe.dart:53)\
                                                                                                    <asynchronous suspension>\
                                                                                                    #3      Stripe._initialise (package:flutter_stripe/src/stripe.dart:699)\
                                                                                                    <asynchronous suspension>\
                                                                                                    #4      initializeStripe (package:hiya/backend/stripe/payment_manager.dart:31)\
                                                                                                    <asynchronous suspension>\
                                                                                                    #5      main (package:hiya/main.dart:34)\
                                                                                                    <asynchronous suspension>}
```

This suggests an issue concerning stripe and the app theme.

After discussion with FlutterFlow support I was advised to post this here as a bug.

### Expected Behavior

The app should load consistently and correctly on Android 11, 12 and 13.

### Steps to Reproduce

1. Build a project that uses the stripe package.
2. Run on a device using Android 12 / 13
3. Observe that the app does not run

(I do not know if these steps are reproducible from a blank project. Our last deployed version of the app (March 2023) worked on these OS versions.)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESkMrq5ZdgocsE7rrtbvp6hQAkH1x/bZJEl9cbcEsbfar1OooEPOr+VFhVX/GVS35XfFD++UUepMmPj9/fUMYFCzCrQoNoz89udDngWn2mR66RO8+wTnZATMVUJ2K+056zmwlSWbR0V3gtw1r/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

We cannot deploy our application as it will not run on Android 12 and 13.

### Visual documentation

An example running the app on an emulated Pixel XL with Android 13:
<img width="200" alt="Screenshot 2023-08-09 at 14 26 54" src="https://github.com/FlutterFlow/flutterflow-issues/assets/94903293/1e297206-2911-4d19-b0f7-cc4d6e3affda">

When running the app on an emulated device with Android 11:
<img width="200" alt="Screenshot 2023-08-09 at 14 29 29" src="https://github.com/FlutterFlow/flutterflow-issues/assets/94903293/3f58e931-b9e9-4fd2-9efc-ae54bdc9cf91">

This behaviour was originally noticed on many physical devices when the app was rolled out to the Play Store. it's not an emulator issue.

### Additional Info

Almost all of the things we have changed since our last deployment (that worked successfully on Android 12/13) are cosmetic:
- Updated colours in colour palette
- Added dark mode palette
- Updated Base API URL
- General style updates to buttons, text etc.

General functionality has not changed.

We have not changed any code locally etc.

### Environment

```markdown
- FlutterFlow version: 
- Platform: Android
- Browser name and version: Android 12 / 13
- Operating system and version affected:
```

**Comment by davidflutterflow** [comment]
We troubleshoot this issue in support.

**Comment by hariprasadms** [comment]
Hi @samhepburn-hiya - Thanks for submitting the issue. As per support team investigation, it is related to stripe package compatibility with some versions of android real devices. I can mark this as bug. Development will look into it shortly. Thanks

**Comment by wenkaifan0720** [comment]
Hi @samhepburn-hiya. Is this still happening to you? I tried to run the snapshot project you shared on an Android 13 emulator and could launch the app.

**Comment by bydakid** [comment]
Hi, I am experiencing the same issue with my app and the stripe package. With Android 13 and 12 my screen does not change but with android 11 everything works fine. Is this issue been solved?

**Comment by samhepburn-98** [comment]
> Hi @samhepburn-hiya. Is this still happening to you? I tried to run the snapshot project you shared on an Android 13 emulator and could launch the app.

This still is not working for us, we are still unable.e to release that version of the app.

**Comment by Jahalex** [comment]
@wenkaifan0720 @SameerShahzad99 Can you tell us the progress of this bug please? Do you have any ideas on how to resolve this bug? I thank you in advance ☺️

**Comment by wenkaifan0720** [comment]
Hi @Jahalex. Could you share a bug report code? I am still not able to reproduce this issue. I have also created a test project(https://app.flutterflow.io/project/flutterflow-issue-1236-knvej2). Could you see if you can reproduce the issue in this project?

**Comment by Jahalex** [comment]
So it will be complicated to release a bug report code because to reproduce the bug you have to test on an Android 12/13. You must install Stripe on the project then download the APK on Android 12 or 13.

samhepburn-hiya who initiated the bug to share the error:

```
E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(flutter_stripe initialization failed, The plugin failed to initialize:\
                                                                                                    Your theme isn't set to use Theme.AppCompat or Theme.MaterialComponents.\
                                                                                                    Please make sure you follow all the steps detailed inside the README: https://github.com/flutter-stripe/flutter_stripe#android\
                                                                                                    If you continue to have trouble, follow this discussion to get some support https://github.com/flutter-stripe/flutter_stripe/discussions/538, null, null)\
                                                                                                    #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:171)\
                                                                                                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)\
                                                                                                    <asynchronous suspension>\
                                                                                                    #2      MethodChannelStripe.initialise (package:stripe_platform_interface/src/method_channel_stripe.dart:53)\
                                                                                                    <asynchronous suspension>\
                                                                                                    #3      Stripe._initialise (package:flutter_stripe/src/stripe.dart:699)\
                                                                                                    <asynchronous suspension>\
                                                                                                    #4      initializeStripe (package:hiya/backend/stripe/payment_manager.dart:31)\
                                                                                                    <asynchronous suspension>\
                                                                                                    #5      main (package:hiya/main.dart:34)\
                                                                                                    <asynchronous suspension>}
```

By investigating a little we can see that:

Theme issue: The error indicates that your Android app theme is not properly configured to use Theme.AppCompat or Theme.MaterialComponents. The Stripe plugin generally requires your app to use a Material Design-compatible theme to ensure it works properly.

Solution: To resolve this issue, follow these steps:

Make sure your Flutter app is configured to use a Material Design compatible theme, for example by using Flutter's ThemeData in your app.

Check your android/app/src/main/res/values/styles.xml file and make sure the theme you are using is compatible with Material Design. You can use Theme.AppCompat or Theme.MaterialComponents. For example :

```
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
     <!-- Other style configurations -->
</style>
```

Also make sure you've followed the instructions specific to the Stripe plugin for Android, as described in their README. There may be additional configurations required to properly integrate Stripe into your application.

**Comment by Jahalex** [comment]
I found the error !!! 👍 💯 🥇  @wenkaifan0720 @SameerShahzad99 

In step 3 of #Requirements #Android of the tutorial offered by stripe on Github: https://github.com/flutter-stripe/flutter_stripe#android\

3. Using a descendant of Theme.AppCompat for your activity: [example](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/app/src/main/res/values/styles.xml#L15), [example night theme](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/app/src/main/res/values-night/styles.xml#L16)

We can see that when we click on example night theme, they show the example code that we need to put:

example/android/app/src/main/res/**values-night**/styles.xml

We should have this:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Theme applied to the Android Window while the process is starting when the OS's Dark Mode setting is on -->
    <!-- TODO document the necessary change -->
    **<style name="LaunchTheme" parent="Theme.AppCompat.DayNight.NoActionBar">**
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <!-- Theme applied to the Android Window as soon as the process has started.
         This theme determines the color of the Android Window while your
         Flutter UI initializes, as well as behind your Flutter UI while its
         running.
         
         This Theme is only used starting with V2 of Flutter's Android embedding. -->
    <style name="NormalTheme" parent="Theme.MaterialComponents">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
```

When I download the code of my project and I go to the style.xlm of the "values-night" folder I have this:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Theme applied to the Android Window while the process is starting when the OS's Dark Mode setting is on -->
    **<style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">**
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <!-- Theme applied to the Android Window as soon as the process has started.
         This theme determines the color of the Android Window while your
         Flutter UI initializes, as well as behind your Flutter UI while its
         running.
         
         This Theme is only used starting with V2 of Flutter's Android embedding. -->
    <style name="NormalTheme" parent="Theme.MaterialComponents">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
```

We can see that it's not good I have the light theme line " <style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar"> " whereas I should have that as said in the stripe example "<style name="LaunchTheme" parent="Theme.AppCompat.DayNight.NoActionBar">"

So to resolve the bug you need to add the correct code in the style.xlm of the "values-night" folder.

**Comment by wenkaifan0720** [comment]
Thank @Jahalex for the investigation. This should be fixed in our next update.

**Comment by Jahalex** [comment]
@wenkaifan0720 @SameerShahzad99  I noticed that you delivered, but still the same error...

```
09-20 07:57:20.997  9896  9956 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(flutter_stripe initialization failed, The plugin failed to initialize:
09-20 07:57:20.997  9896  9956 E flutter : Your theme isn't set to use Theme.AppCompat or Theme.MaterialComponents.
09-20 07:57:20.997  9896  9956 E flutter : Please make sure you follow all the steps detailed inside the README: https://github.com/flutter-stripe/flutter_stripe#android
09-20 07:57:20.997  9896  9956 E flutter : If you continue to have trouble, follow this discussion to get some support https://github.com/flutter-stripe/flutter_stripe/discussions/538, null, null)
09-20 07:57:20.997  9896  9956 E flutter : #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:171)
09-20 07:57:20.997  9896  9956 E flutter : #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
09-20 07:57:20.997  9896  9956 E flutter : <asynchronous suspension>
09-20 07:57:20.997  9896  9956 E flutter : #2      MethodChannelStripe.initialise (package:stripe_platform_interface/src/method_channel_stripe.dart:52)
09-20 07:57:20.997  9896  9956 E flutter : <asynchronous suspension>
09-20 07:57:20.997  9896  9956 E flutter : #3      Stripe._initialise (package:flutter_stripe/src/stripe.dart:666)
09-20 07:57:20.997  9896  9956 E flutter : <asynchronous suspension>
09-20 07:57:20.997  9896  9956 E flutter : #4      initializeStripe (package:neo_i_d/backend/stripe/payment_manager.dart:31)
09-20 07:57:20.997  9896  9956 E flutter : <asynchronous suspension>
09-20 07:57:20.997  9896  9956 E flutter : #5      main (package:neo_i_d/main.dart:30)
09-20 07:57:20.997  9896  9956 E flutter : <asynchronous suspension>
```

**Comment by wenkaifan0720** [comment]
Hi @Jahalex. This is quite weird. Could you provide a bug report code so I can look into your project specifically?

**Comment by Jahalex** [comment]
Hello @wenkaifan0720, Could you be more specific about bug report export? Just tell me what you want more precisely and how to export it to help you as much as possible.

It's really on Androichosend 13 that there is this problem.

I came across this ticket stripe where there is the same problem if that helps: https://github.com/flutter-stripe/flutter_stripe/discussions/538

I could see that you made the change in the values-night folder, but it still doesn't work weird. Because I looked at the stripe code and that of my project and I have the same thing... We can see in the error in my previous message that it's really "Your theme isn't set to use Theme. AppCompat or Theme.MaterialComponents." which poses a problem. Now you need to know the why and the how. Because I find "Theme.AppCompat or Theme.MaterialComponents" in my project, but I have the impression that stripe cannot find it.

**Comment by wenkaifan0720** [comment]
Hi @Jahalex. In order to get a bug report code, go to any page and open the widget tree panel. Right click on any widget and you can see the `Get Bug Report Code` option.

**Comment by wenkaifan0720** [comment]
The bug report code is not during your app runtime, its from the project inside FlutterFlow itself.

**Comment by Jahalex** [comment]
I do not reproduce the bug on flutterflow test. The bug is only present on Android 13/12.

**Comment by wenkaifan0720** [comment]
I need the bug report code to access your project in a confidential way.

**Comment by Jahalex** [comment]
ITFTivHlsYtNpbxb+KribvkxnWQUGUMAWoJMitUbdx4dJZOqOrQXP/fSV0NKT9+ETHxYC078mmID//T0kt7lIewpG0uVfNln0JVAVBficz6leKa0Crm7dHNSROxhIB2y08PR2AlDNrNtS1Fg62GhNa3qNleeY8aSfxBlZ7vfcPo=

**Comment by wenkaifan0720** [comment]
Hi @Jahalex. Thank you. I can however run your project on Android 12/13 with both the emulator and a Samsung S23. 

![Screenshot_20230926_001053](https://github.com/FlutterFlow/flutterflow-issues/assets/112435854/bf8de0b3-30b1-4632-8442-55968ced9021)

Could you provide more information about what device are you testing on? A screen recording would be very helpful.

**Comment by Jahalex** [comment]
I suggest you download the app on Android from a real phone or Lambdatest from browsertack.

As soon as the application launches I arrive directly on a white screen.

Screenshot :
<img width="894" alt="Capture d’écran 2023-09-25 à 18 34 21" src="https://github.com/FlutterFlow/flutterflow-issues/assets/43749754/060c07ed-4670-4ba6-b0e5-6f889b758666">

**Comment by MyTechAgent** [comment]
Hey team,

I am experiencing this issue too. I have done some poking and found similar threads over the last couple of days / weeks. As soon as I remove stripe it works. So really the only way to deploy to android would be to do what was advised earlier and manually export and upload if someone wants to use a payment system. Works on emulator, works on iOS, not on android via apk. I am waiting to be verified on google play to see if it's more of a security thing but some priority around this would be much appreciated.

**Comment by Abayjafton** [comment]
Guys
Remove background color and preloading color completely in splash screen in settings
Transparent or unset them
The application now starts up properly and stripe works.
That worked for me.

**Comment by Jahalex** [comment]
@Abayjafton Thank you very much, it works for me 👍

**Comment by juanconchag** [comment]
I have this same problem. I did what @Abayjafton said and I put it on transparent both the background color and the preloading. Didnt work for me. Anyone know how to put those color in Unset? Or any other suggestions? Thank you in advance

**Comment by MyTechAgent** [comment]
Hey mate,
That didn’t work for me. Removing it all together worked though.


Sent from Yahoo Mail for iPhone


On Thursday, October 19, 2023, 9:53 am, juanconchag ***@***.***> wrote:




I have this same problem. I did what @Abayjafton said and I put it on transparent both the background color and the preloading. Didnt work for me. Anyone know how to put those color in Unset? Or any other suggestions? Thank you in advance

**Comment by juanconchag** [comment]
> Hey mate, That didn’t work for me. Removing it all together worked though. Sent from Yahoo Mail for iPhone On Thursday, October 19, 2023, 9:53 am, juanconchag ***@***.***> wrote: I have this same problem. I did what @Abayjafton said and I put it on transparent both the background color and the preloading. Didnt work for me. Anyone know how to put those color in Unset? Or any other suggestions? Thank you in advance — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Excelent. It worked this way. Thank you

**Comment by sbis04** [comment]
This issue should be fixed in the next update!
