### ISSUE TITLE
Infinite scroll breaks for subcollections

### ISSUE THREAD

**Issue by neian-world** [FlutterFlow/flutterflow-issues#1248]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When infinite scroll is enabled and the query targets a subcollection (under the user collection), the query skips the user collection reference and tries to do a collectionGroup query across all user collections.

<img width="394" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/fbf8d3d7-1509-432c-8ffb-b76356eec637">

### Expected Behavior

Infinite scroll should also take into consideration the parent collection variable specified. 

### Steps to Reproduce

1. Create a subcollection query and specify a parent collection, don't enable infinite scroll.
2. Check the number of returned documents.
3. Enable infinite scroll on the query.
4. The returned documents now come from all subcollections combined (collectionGroup query).

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghc/lvJdOm99J1aX2de9VvCkQJmU1a5c0sNtuTQIdCYDuBIYiac/sTFhtOeG5TX9pKEWLnl0E3MLqj+DDJMI4AwSrQYg4z89hED3xeD+/aoubOpeWOn8nMJlPf0yi0ra3nQolKbdaSiVm7XGqF9++RXbUQeb7Zwh9f6PHaOI=

### Context

I'm trying to get a list of favorites items for a specific user, while using infinite scroll to avoid reading all the data at once.

### Visual documentation

In my database there are 2 documents for my current user, and 1 document for another user. Even though the query specifies the parent collection (user), I get 3 documents.
I had to change firestore rules to enable contentFavorited to be read across all parent user collections, otherwise I get a firestore rules error (because this user is not allowed to read other user's subcollections).

<img width="319" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/14129957-02c5-4ca9-b39b-99a7246f9409">

<img width="400" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/28e8a79e-7a5d-4c53-a6b8-e59d759bfe50">
<img width="1112" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/f44fbb1c-38fd-40ab-99e0-cfc43df21713">

### Environment

```markdown
- FlutterFlow version: 1.1.95
- Platform: MacOS
- Browser name and version:
- Operating system and version affected: 13.4.1 (c) (22F770820d)
```

**Comment by neian-world** [comment]
Tested on Chrome Version 115.0.5790.170 (Official Build) (x86_64)

**Comment by AlexFox63** [comment]
Found this issue also. Please fix it quickly because it affects many modules in our projects.

**Comment by SitnAlex** [comment]
Same issue, broke in all of my projects

**Comment by SitnAlex** [comment]
Tested on android (APK) and iOs (TestFlight),bug replicated. 
Potentialy bug appeared with "infinite scroll for more widgets" update 20 Jul 2023

**Comment by sbis04** [comment]
This should be fixed in the next update!

**Comment by SitnAlex** [comment]
Hey @sbis04, I'm looking through the app right now, I still get this bug, could you please look through it?

**Comment by AlexFox63** [comment]
Still the same

**Comment by AlexFox63** [comment]
> This should be fixed in the next update!

Any updates?

**Comment by sbis04** [comment]
This should be fixed now, I think the fix wasn't deployed at that time.
