### ISSUE TITLE
Firebase App Check Authentication enforce does not work

### ISSUE THREAD

**Issue by rafamessias** [FlutterFlow/flutterflow-issues#1287]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After configuring Firebase App Check and enforce Authentication, it not possible to login and the App returns the following error on console log: Firebase App Check token in invalid.

![error](https://github.com/FlutterFlow/flutterflow-issues/assets/45216878/c124d11f-4e09-4210-a652-b1d14aa5c5e5)

### Expected Behavior

Firebase App Check Authentication enforce should work fine like Firestore enforce.

### Steps to Reproduce

1. Have a FF App with Firebase Authentication
2. Create two pages, one as Login Page and another as an Authenticated Page
3. Configure Firestore App Check following the [documentation ](https://docs.flutterflow.io/settings-and-integrations/integrations/firebase-app-check)
4. Go to Firebase console -> App check
5. Click on Authentication -> Enforce button (as image below)
6. Try to login into your App

![Screenshot 2023-08-10 084416](https://github.com/FlutterFlow/flutterflow-issues/assets/45216878/e4a8c1eb-f5f9-4694-ad79-2b54733f0e1c)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sifLcw5d2xdtJ0K6JK+5r/SYQG248aoIkscsZa0kdB4joPLJ+Oszsak5pTsTgSkNhHFmJgmAy+d7XiuDiFe0CISqdR759yc5+EAvve3q8R4SIPc2SVkd8M/5MIFS41J6r2RJdJfhhdGA82zmHOOuifHbrN5O/Zwh9f6PHaOI=

### Context

When Firebase App Check Authentication enforce is enabled, it is unable to login into the App.

### Visual documentation

If you try to login into the App the following error will occur:
![error](https://github.com/FlutterFlow/flutterflow-issues/assets/45216878/740c92b6-2458-41a2-bbe2-027aceca417f)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: 115.0.5790.171
- Operating system and version affected: Windows 11
```

**Comment by SameerShahzad99** [comment]
@rafamessias Thank you so much for submitting this bug, I was able to reproduce this bug on a local project
Bug Report code:
IT4ol8j6y5VNsdta1c7qdcAxnSQ7Q2J/aLs808pBZywgfZzzBLN/fPfQP0loTselSmNEPVmcp14z0+DSkYaeVPcEaBKZRt1I+Kt6EQ2XXj6QabmTF7qCQXwnBp9MJ2qny6azgAhBIrJfWmQb2Ey2H++/QgnrJYSzPGo4Sq/LZO4=

**Comment by katherineqian** [comment]
Hi @rafamessias, I wanted to apologize for the extremely delayed response on this issue. I appreciate all of the details that you gave to help resolve the bug. I was not active on maintenance and I'm sorry that I let this fall through the cracks like this. I wanted to provide you with an ETA on when this would be addressed - it should likely be fixed on the second release from now (aka in the release after next), if not the next one after that. I will provide an update here if it turns out this isn't a bug, but based on the report, I believe I should be able to find a fix for this. I'm sorry again for the delay.

**Comment by gurpalc** [comment]
Hello, I'm adding a comment here to add that I am experiencing this issue as well. I have signed up for recaptcha, entered the required information, and when I enable app check for my web application, it does not work. Is this a bug that has been resolved? I'm working with flutterflow support on this and no other solutions have been found yet. Thank you

**Comment by jeffersonGlemos** [comment]
Hello.
I have this same issue right now any update about this?

**Comment by devjoter** [comment]
Pleas keep this issue of high importance as App Check is vast security layer for firebase. 
In fact there are issues with Web implementation for me as well.

**Comment by katherineqian** [comment]
Hi @gurpalc, @jeffersonGlemos, @devjoter - thank you for adding your reports to this. Can you please confirm some details for me? 
1. Whether the bug is occurring in production or only in debug mode. 
2. Which platform you are receiving this exception on (so far it appears the reports are for Web only). 
3. Whether Firebase Storage is enabled for the project you are trying to use App Check on. 
Thank you!

**Comment by katherineqian** [comment]
Can you also please try the debugging steps from #1080?
> Sorry for the slow reply.
> 
> I'm unable to reproduce the issue: it works fine for me when I set the "Run/Test Mode Debug Token". The reCAPTCHA token is not required for Test Mode.
> 
> Please try the following steps and let me know the results:
> 
> * Make sure "Run/Test Mode Debug Token" is set.
> * Regenerate Firebase config files, regenerate the debug token in Firebase console, update the token in FlutterFlow, start new Test Mode session.
> * Check your browser console. Does it print a message like this? `App Check debug token: <...>. You will need to add it to your app's App Check settings in the Firebase console for it to work.` Is this your token?
> 
> @anorld-droid What's in the "Request" tab and what's in the "Response" tab?

**Comment by gurpalc** [comment]
>1. Whether the bug is occurring in production or only in debug mode.
>2. Which platform you are receiving this exception on (so far it appears the reports are for Web only).
>3. Whether Firebase Storage is enabled for the project you are trying to use App Check on.
Thank you!

1. It is occurring in both production and debug mode
2. Web version
3. Firebase storage is currently enabled

**Comment by gurpalc** [comment]
> Can you also please try the debugging steps from #1080?
> 
> > Sorry for the slow reply.
> > I'm unable to reproduce the issue: it works fine for me when I set the "Run/Test Mode Debug Token". The reCAPTCHA token is not required for Test Mode.
> > Please try the following steps and let me know the results:
> > 
> > * Make sure "Run/Test Mode Debug Token" is set.
> > * Regenerate Firebase config files, regenerate the debug token in Firebase console, update the token in FlutterFlow, start new Test Mode session.
> > * Check your browser console. Does it print a message like this? `App Check debug token: <...>. You will need to add it to your app's App Check settings in the Firebase console for it to work.` Is this your token?
> > 
> > @anorld-droid What's in the "Request" tab and what's in the "Response" tab?
 
Hello, I have uploaded screenshots from my developer that he says answers that question. Is this helpful or is further information needed? Thank you
 
![screenshot 3](https://github.com/FlutterFlow/flutterflow-issues/assets/108390844/bc9013b9-a57b-4a77-933a-a2bab0396f29)
![screenshot 2](https://github.com/FlutterFlow/flutterflow-issues/assets/108390844/28ce643b-a404-46f4-9caf-4cbfc42f9da7)
![screenshot 1](https://github.com/FlutterFlow/flutterflow-issues/assets/108390844/89bcd65e-d5ae-42f6-841e-0a7827de3fb7)

**Comment by aemelyanovff** [comment]
I can reproduce the issue. It looks like the problem is that FlutterFlow is using an outdated version of `firebase_app_check`.

**Comment by aemelyanovff** [comment]
Fixed in the last update.

**Comment by DentalRx** [comment]
App Check is still not functional on web for me. Can we confirm that this issue is fixed?

**Comment by DentalRx** [comment]
> > App Check is still not functional on web for me. Can we confirm that this issue is fixed?
> 
> Is the error exactly the same as in the issue description?

Current Behavior
After configuring Firebase App Check and enforce Authentication, it not possible to login and the App returns the following error on console log: Firebase App Check token in invalid.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/138252345/3dfdccc7-c9dd-4b59-bd64-2bf5e13d61fd)

**Comment by gurpalc** [comment]
> > App Check is still not functional on web for me. Can we confirm that this issue is fixed?
> 
> Is the error exactly the same as in the issue description?

Hi I can confirm it is having the same error for me, it just says "Error: Error" in a snackbar, just like last time.

**Comment by pedrohssales** [comment]
'm using reCaptcha Enterprise. I followed all the FlutterFlow documentation to deploy, but I keep getting an eternal loading screen for my app: [sispcad.flutterflow.app](http://sispcad.flutterflow.app/)

When checking the console, there is visibly an error. I don't know how to interpret it for sure, but it is possible to see a mention of reCaptcha V3.

This looks like a FlutterFlow bug to me.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/130273434/a4be56af-c355-4ff5-85b1-fd15a0ae780d)

These are the metrics I'm getting from app check requests, from firestore:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/130273434/cd9d603d-f376-42fd-96b3-5e4e50878d3b)

**Comment by pedrohssales** [comment]
I received a response from the firebase support team. The answer indicates that my suspicion was correct. Flutterflow is trying to create a token with reCaptcha V3, not reCaptcha Enterprise, resulting in a bug.

![screenshot](https://github.com/FlutterFlow/flutterflow-issues/assets/130273434/e0a1f85d-c5c5-4658-acaa-7ef53d35cf0d)

**Comment by DentalRx** [comment]
> I received a response from the firebase support team. The answer indicates that my suspicion was correct. Flutterflow is trying to create a token with reCaptcha V3, not reCaptcha Enterprise, resulting in a bug.
> 
> ![screenshot](https://private-user-images.githubusercontent.com/130273434/294310201-e0a1f85d-c5c5-4658-acaa-7ef53d35cf0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDY2MDEsIm5iZiI6MTcwNDQwNjMwMSwicGF0aCI6Ii8xMzAyNzM0MzQvMjk0MzEwMjAxLWUwYTFmODVkLWM1YzUtNDY1OC1hY2FhLTdlZjUzZDM1Y2YwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQyMjExNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjEyNGIxM2U5OGY1NmJkY2JlYTkwNzM3ZWY4ZmU2NjFkYWMyZjU5MjdjMDIyZDRkNDU0ZmU5OWYyMGY5MjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.04ppzLtCjOZkkqM6LrnH35MdJP3MAwgntFSaLsjvAQk)

In the documentation they use reCaptcha enterprise... this is good to know though. Thank you. 

FlutterFlow team: are we to assume there is no support coming for enterprise? Or should we hold tight?

**Comment by pedrohssales** [comment]
> Hi all:
> 
> * reCaptcha Enterprise is not supported by FlutterFlow yet, but we'll add it in the next update. Until then, please use reCaptcha v3.
> * Make sure your web app's URL is allow-listed in reCaptcha.
> * Try re-publishing your web app. We recently upgraded our AppCheck dependencies.
> * If the issue persists, please reach out to Support.

Hello, aemelyanovff.

Alright, I understand there is no support currently. But I believe, then, that there is an error in the flutterflow documentation. There is mention of reCaptcha Enterprise as compatible. But thank you very much for the feedback, I will wait for the next update

**Comment by SakhileMamba** [comment]
Hello.

Please note I am facing the same issue when trying to test with a real device on android.
