### ISSUE TITLE
Dropdown Multi Select Issue in Flutterflow

### ISSUE THREAD

**Issue by flutterflowdevs** [FlutterFlow/flutterflow-issues#1343]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I select multiple options from a dropdown widget, I receive a list of strings as output. 
However, when I attempt to set the initial value options in a multiple dropdown, the system only accepts a single string variable. This behavior was mentioned in a video. 
Additionally, there is an action provided in FlutterFlow that allows setting multiple values in a dropdown, but upon using this action, it results in a runtime error. 
Please refer to the attached screenshot for further clarification.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/126557523/da7ec59e-2746-4e14-8b8a-603f00878a36)

### Expected Behavior

It should accept a list of strings if I use a multi-select dropdown.

### Steps to Reproduce

1. Create a dropdown on a Page.
2. Switch On the Allow Multi Select option. 
3. Try to set a list of string type variables in the initial value.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kksn6389IsdtJ7pDAb8d7/SAWQkR+U40wlu5HbAA0IbbnG7YASs77P1VeTbzhTFc3Ik60hmQz+dLQvfbIN8EVA0yaQbpyzs0BUA7vWn+uSqqmBs2KS3wkPNpKBUin1MO7vR5+ItBpSi0M31yuCemiYAjUNYTRNXoZIPiJIpDOs3PuQ0SLb3kNh1JWeC/v

### Context

The client project has requirements where users can choose multiple hobbies. These selected hobbies should be stored in a database. Additionally, users should be able to modify their chosen hobbies at a later time. As part of this functionality, it's essential to display their previously selected hobbies in a dropdown list for easy updating.

### Visual documentation

Please find the video link below:-
https://www.awesomescreenshot.com/video/20188695?key=52439d9238d609ea33419b6bbe7e542f

### Environment

```markdown
- FlutterFlow version: v3.1--Flutter3.10.4 
- Platform: Flutterflow Panel
- Browser name and version: Version 116.0.5845.98 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by wenkaifan0720** [comment]
Hi @flutterflowdevs. This should be fixed in our next update. Thanks!

**Comment by neian-world** [comment]
The UI shows that it's a list now, but the build still fails. Could it be related to the initial value still not being a list (even though it's left blank)?

<img width="627" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/0d48ba5c-dc24-406d-92dd-15c6d079fef0">
<img width="637" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/f7f8b187-2175-4f81-87e4-d63ec3b10f47">

**Comment by neian-world** [comment]
Any news on this one? Tested again and the build fails the same way.

**Comment by flutterflowdevs** [comment]
@wenkaifan0720 how this ticket is closed when the issue is not yet resolved?

**Comment by wenkaifan0720** [comment]
Hi @neian-world, @flutterflowdevs. Our previous fix had some issue and wasn't deployed. I will reopen this issue and work on it once I got the time.

**Comment by codeorlov** [comment]
The same situation for me, it is important. I hope, that it will be fixed in next update.

**Comment by wenkaifan0720** [comment]
Hi all. Unfortunately, it doesn't look like we can perform set/reset actions (or provide a initial value list) when the dropdown is multiselect. This is just because how the multiselect dropdown widget we use is designed. It is not impossible to achieve this, but for now I would just push a fix that disables those crashing behaviors.

**Comment by codeorlov** [comment]
Hi, @wenkaifan0720 , sorry, buit it is not clear fo me. In inital value description, we can see that in will be a list, but, now it string. Does your answer mean that we can't use dynamic value determination for a multiple choice list? this really sounds depressing.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/130235685/7d398372-79a6-4478-addd-5e665ec2f749)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/130235685/77d87770-4e2a-4d43-b954-ccfd701aa283)

**Comment by wenkaifan0720** [comment]
Unfortunately yes for now. Right now you can only access the state of the multiple choice list, which is a list of strings.

**Comment by codeorlov** [comment]
Ok, got it, thanks. I hope, that will be fixed in future, because without dynamic functionality dropdown with multiple options useless in many cases.

**Comment by akshaydewan22** [comment]
@wenkaifan0720 When can we expect this functionality to be added:
Set/reset actions (or provide a initial value list) when the dropdown is multiselect.

**Comment by akshaydewan22** [comment]
@hariprasadms any update on the fix being released soon?

**Comment by akshaydewan22** [comment]
@hariprasadms @flutterflowdevs  any update on the fix being released soon?

**Comment by farhannkaskar** [comment]
This is a blocker. We need this asap please

**Comment by akshaydewan22** [comment]
@flutterflowdevs @hariprasadms @wenkaifan0720 pls respond and atleast let us know if it is being solved soon. Else I will invest time in a Custom Widget and move ahead.

**Comment by akshaydewan22** [comment]
@farhannkaskar you can refresh your window. They have rollled out this option :)

Thanks a ton @flutterflowdevs @hariprasadms @wenkaifan0720
