### ISSUE TITLE
App State: hint shows "field_name" but underscores are not allowed

### ISSUE THREAD

**Issue by k98kurz** [FlutterFlow/flutterflow-issues#1383]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating a new App State field, it is impossible to type in an underscore to use snake_case as suggested by the input label.

### Expected Behavior

Underscores should be allowed to be typed, or the type hint should be changed to camelCase

### Steps to Reproduce

1. Create a new App State field.
2. Try to type anything in snake_case.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5TlPHlx5NOmN9J7arAacZvmjs5JjsjauYzju1ERRQaJuvxEIlze8nRT3FJYcukTFVcIWKZ/Wcz+KHWuIf2UOw4FAqrQ4Ne+qt+cw7iIWaRRqrQC7mORHNPGZlXN26D1rSKmA9dKsdfSXws1FOENuutFynZHpy0Om4zQ+SYFIbMon/mFSXsFDhFxmNecCfn

### Context

Just trying to adhere to the suggested naming convention.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/4357561/1963697a-fd12-4374-9bf0-3889216c6cff)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/4357561/ffe29bb2-e69b-4686-893b-68ef42066a86)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Vivaldi 6.1.3035.302
- Operating system and version affected: Ubuntu 22.04
```

**Comment by k98kurz** [comment]
Bump

**Comment by takashiff** [comment]
This issue has been fixed and will be updated in our next deploy

**Comment by pmarathay** [comment]
Did the fix also include variable names used in Arguments for Custom Actions?  We are still seeing the problem when we try to define an Argument.  Thx
