### ISSUE TITLE
Keyboard not dismissed inside bottom sheets.

### ISSUE THREAD

**Issue by kium-one** [FlutterFlow/flutterflow-issues#1484]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When tapping outside of a field on a normal page (with Dismiss keyboard on tap enabled) the keyboard hides. In bottom sheets with input fields though, the keyboard stays open no matter where I tap.

### Expected Behavior

Keep the setting from the page on the bottom sheet as well, or have a separate setting for the bottom sheet.

### Steps to Reproduce

1. Create a component with a text input field
2. Open that component in a bottom sheet
3. Click on the text input
4. Click anywhere else
5. Keyboard can't be mismissed.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghc/lvJdOm99J1aX2de9VvCkQJmU1a5c0sdlud0wdCoDuBIk+ZPWkbhBpTc+rYwliMESmmnMJ+vyPiuLpD/I3CzWqc4g9yKtcEAnyeFGhe5OBEpO3dkB6EelMJ2qZ0MKJryVBIsB0SHga6mWPe+vIUXTAJLL2ImdISq/LZO4=

### Context

See above

### Visual documentation

Self-explanatory

### Environment

```markdown
- FlutterFlow version: 3.1 Sep 17
- Platform: iOS 17 through Xcode
- Browser name and version:
- Operating system and version affected: iOS 17 through Xcode
```

**Comment by victoriahuang1** [comment]
Hi @kium-one , thanks for the report. I have fixed a bug on our end, and this should be resolved upon the next deploy

**Comment by kium-one** [comment]
Wonderful, thank you Victoria.On Sep 21, 2023, at 7:42 PM, Victoria Huang ***@***.***> wrote:﻿
Hi @kium-one , thanks for the report. I have fixed a bug on our end, and this should be resolved upon the next deploy

**Comment by kium-one** [comment]
Hey @victoriahuang1, this is unfortunately still happening even after the update (Sep 28).
