### ISSUE TITLE
Send Email Verification Link Action not working 

### ISSUE THREAD

**Issue by graymanOz** [FlutterFlow/flutterflow-issues#1536]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Send Email Verification Link Action is not sending verification emails. 

After a user hits submit button to signs up , action is Auth: Create Account and second action Auth: send email verification link. 

However, users are not receiving emails to verify email accounts. 

I also have an action to resend the email verification link when a user tries to log back in without having verified.  

This link is also not being sent.

My app is in the app store, and email verification was working fine before.  

The last confirmed email verification link sent to a new user was Sept 4, but i suspect that emails were only sent intermittently before then as well. 

I have checked the console and the console response: "Paused on promise rejection" and "Firebase Error: Operation Cancelled".

I have submitted a help request to FireBase as well, but i note that according to an earlier FF user who submitted a FlutterFlow bug report on a similar/same isue they say:  "This does not appear to be an issue with Firebase as it is reporting all systems operational." 
(Bug: "Send Email Verification Link Action not working consistently #964" - by KeepTrackSolutions submitted Jun. 4)  https://github.com/FlutterFlow/flutterflow-issues/issues/964 

### Expected Behavior

email verification to be sent to users on sign up and, if needed, if they try to log in again without having received a link and confirmed their email address

### Steps to Reproduce

My app is in the app store, and email verification was working, now its not.  

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXls/l5Yx2ssBE187xLMJVqDwwFjMMbY0v0u0bFB4jG5jsEJk+Z/T7MkNKTe2Zdwk/MWKlmk4JpdbOheP1GMI6ZDarR7Z80JVPEjvjVlq5MbnXCs2WbXB8BexmClSd0aanhiZSNuphSnA8w2GPNq3qNleeY8aSfxBlZ7vfcPo=

### Context

i want my users to be able to verify their emails

### Visual documentation

![Screenshot (350)](https://github.com/FlutterFlow/flutterflow-issues/assets/101852823/780718ff-6359-4831-8621-1823cfca6208)
![Screenshot (349)](https://github.com/FlutterFlow/flutterflow-issues/assets/101852823/e07c0850-eb7e-4aeb-bc8f-3178dec93465)

### Environment

```markdown
- FlutterFlow version: 4.0, but issue has been going on since before now
- Platform: ios and android for users and chrome when Run/testing
- Browser name and version: chrome  Version 117.0.5938.92 (Official Build) (64-bit)
- Operating system and version affected: windows 11 home 22621.2283
```

**Comment by graymanOz** [comment]
a screenshot of the debug screen when a user tries to log in without having verified their email
![Screenshot (351)](https://github.com/FlutterFlow/flutterflow-issues/assets/101852823/6a19b817-3780-4094-8bfc-172615f59aac)

**Comment by graymanOz** [comment]
a screenshot of the debug screen when a user signs up 
Screenshot (355)](https://github.com/FlutterFlow/flutterflow-issues/assets/101852823/3667a6ef-75d5-486a-b5d5-4239d20bfa71)

**Comment by adrianoos** [comment]
Same Issue here with my app, but even when I try to send activation mail manually from firebase web console it is not working

**Comment by adrianoos** [comment]
I received a response from Firebase support to configure the SMTP service and send emails this way. Unfortunately, this also doesn't work even from the console

**Comment by graymanOz** [comment]
Update 2023.10.02 : 
 - as of the last few days email verifications are once again being sent to new users,  
 - i am not sure if either or both of Flutterflow folks or Firebase folks have made changes to effect this.

**Comment by graymanOz** [comment]
update:  the problem has been solved by Firebase.  Their explanation:  

"It was actually an issue that had to be checked from the engineering side, and it was mainly being caused when using a custom domain. At the moment, this issue should already be solved without anything else that needs to be done from their side."  

thanks  

G

**Comment by aman2k4** [comment]
Hi, im still facing the issue. FF is not sending the email verification link to the account. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45624072/22c1c38e-9e64-42a4-bac2-358911d0aba3)

**Comment by graymanOz** [comment]
if you'd like to contact Firebase, here is my resolved case number and contact. maybe better to open a new case (?)
  
To: firebase-support@google.com
subject:  Re: Case 10249981: Email Verification

**Comment by KeepTrackSolutions** [comment]
> Hi, im still facing the issue. FF is not sending the email verification link to the account. ![image](https://user-images.githubusercontent.com/45624072/273660686-22c1c38e-9e64-42a4-bac2-358911d0aba3.png)

@aman2k4 be sure to Create the Account before sending the Verification Email.  From the picture above it appears you are trying to send the email before the account is actually created.

**Comment by KeepTrackSolutions** [comment]
We have also added a 5 second (5000ms) delay between these steps, to allow plenty of time for the account creation to complete successfully.  Also, make sure to complete all the steps to validate your custom domain with Firebase..


Check custom domain is properly configured in Firebase:
Go to Firebase -> Authentication -> Templates -> Email Address Verification
Click the pencil (or Customise domain). 
Check to make sure you have completed all of the verification steps.  (Various DNS entries need to be created on your custom domain.)

Hopefully this helps.  Thanks @graymanOz for raising this with Firebase!

**Comment by borisrybar** [comment]
Thank you @KeepTrackSolutions for 5s delay tip. It helped!
