### ISSUE TITLE
Can't remove icons from components when set from variable

### ISSUE THREAD

**Issue by danileca** [FlutterFlow/flutterflow-issues#159]
## Expected behavior (required)
When creating a component and setting the "Leading Icon" to be set from a variable defined in the component parameters I should be able to remove the icon, when editing the component's properties in the page.

## Current behavior (required)
I'm able just to select the icon, but I don't have the "x" to remove it after I set it.

## To Reproduce (required)
1. Create new component from a TextField widget
2. Create a new Component Parameter using Parameter Name = "icon" and Type = "Icon"
3. Select the TextField widget from the component's tree, go to widget properties and set the Leading Icon from variable "icon". CLick confirm.
4. Go to the page, select the component and set the "icon [icon]" with any icon from Material or Font Awesome
5. The selected Icon appears
6. There is no option to remove the icon like it would be if there wouldn't be a variable used for it.

## Context (required)
Can't update/change the icon in custom components, making me use repetitive widgets to have full control on it. For future styling changes I'll have to find each of these widgets and manually update them instead of updating just the custom component.

## Screenshots / recordings
<img width="245" alt="shot3" src="https://user-images.githubusercontent.com/118264362/203861465-ea38ec92-0bad-495e-b52b-10fc2aef046e.png">
<img width="254" alt="shot2" src="https://user-images.githubusercontent.com/118264362/203861467-fbbb7c9a-51ad-4ece-be2a-460d042cd47f.png">
<img width="1198" alt="shot1" src="https://user-images.githubusercontent.com/118264362/203861468-b31110b5-def4-4449-aeaf-e8f94556bba7.png">

## Your environment
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Edge Version 107.0.1418.42 (Official build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 Enterprise 22H2 desktop

**Comment by Pepino-GR** [comment]
Hi danileca,
I don't think, that it is a bug. You set the appearance of the icon based on a variable in the custom component. So you have to change it in the custom component.  If you don't need the icon in your page, you can set the icon color to the color of the background of the textfield.

**Comment by danileca** [comment]
Thanks for the reply! Unfortunately if I set the icon to transparent then the text won't be centered.
The easiest way to manage this would still be to have an "x" in the icon button of the parameter, just as you have on the widget itself. 

I hope this makes sense

Thanks again

**Comment by Pepino-GR** [comment]
You can set a small icon size.

**Comment by Pepino-GR** [comment]
Or you can set a separate icon and set the visibility to on or of

**Comment by wenkaifan0720** [comment]
Hi @danileca. If you want to remove the icon parameter, you can hover on the title bar of each of the parameter section (like the one called "Parameter 5") and you should see a red "Remove" text button that lets you remove the relevant parameter. Is this what you are looking for?

**Comment by danileca** [comment]
Thanks @Pepino-GR and @wenkaifan0720 for the comments. It looks like after FF refreshed to the newest version I can't set an icon at all

I've uploaded a screen recording that hopefully can explain this better: https://youtu.be/0u_FiDdjfEY

**Comment by wenkaifan0720** [comment]
This is definitely a bug. I'll fix it soon. Thank you for noticing!

**Comment by wenkaifan0720** [comment]
Hi @danileca . Could you try it again? I just tried with the latest version and it works.

**Comment by danileca** [comment]
Hi @wenkaifan0720, just tried it again and still doesn't work for me. I created a new project just to make sure there's nothing wrong in there and tried with both button and textfield, whilst for TextFields I tried setting both a trailing and leading icons.

I also still cannot see the option to remove the icon once I selected one.

Many thanks!

![image](https://user-images.githubusercontent.com/118264362/205427440-b9680668-4881-41cb-8ae1-a0098cb7cc25.png)
![image](https://user-images.githubusercontent.com/118264362/205427660-ad866aa7-2ef9-44d5-8e7e-4251bf2a423c.png)

**Comment by wenkaifan0720** [comment]
Hi @danileca. I think I have figured out what is going on. 

When you are editing the component and trying to set the leading icon (for a button) from a variable, the change would not be reflected in the component page because it is dynamic (same for the string variable, but we made a placeholder string like [text] for it). When you add it to the home page and pass in a icon, the button should have the same icon. I don't know why in your video the icon is not showing up, please see this project that I made: https://app.flutterflow.io/project/flutterflow-issue-159-so4wre, in which the icon is visible.

If you want to delete the icon parameter, you should do it in the component parameter page (where you defined the interface of the component), instead of in the parameter passing panel.

**Comment by danileca** [comment]
Hi @wenkaifan0720 

I just created a new project as well to try again and it still doesn't work to me: https://app.flutterflow.io/project/testing-h7ezqv
You will find there a button component and a textfield component, both having icons from variables that don't show up. The TextField has both leading and trailing icons.
Underneath them there are the regular widgets that show the icons fine.

Can you please have a look? It looks like I set everything like you did (and I did as well in my initial project)

**Comment by wenkaifan0720** [comment]
Hi @danileca. It seems like right now you need to first set some fixed icon and then set the icon from variable for it to show up. This is indeed a bug (or at least very confusing behavior for the user). I'll fix it when I can. Thank you for getting to the bottom of this issue!

**Comment by wenkaifan0720** [comment]
@danileca This bug has been fixed. Thank you!

**Comment by danileca** [comment]
@wenkaifan0720 I'm afraid it still doesn't work for me. You can see the new project above where I tried again, basically re-creating the parameters and everything, but the icon still doesn't show up.

**Comment by danileca** [comment]
Hi @wenkaifan0720, the Icons do appear in the buttons now but they can't be removed. So basically I still need to create a component for the button with the icon and another component for the same button without an icon - which is still duplicated code, from my perspective.

Ideally I should create a button component and have the ability to re-use it across the app with or without an icon.

On a secondary note, the same behavior goes for textfield components, where none of the Trailing or Leading icons appear if I'm using a component for them. Feel free to take a look at my test project as a reference: https://app.flutterflow.io/project/testing-h7ezqv

**Comment by Pepino-GR** [comment]
Hi danileca,

as I mentioned at the beginning, you can use a separate icon widget in your component and use a boolean component variable to set the visibility to true or false.
