### ISSUE TITLE
Timer widget - initial (countdown) time doesn't get set, if value comes from variable with the latest FF update

### ISSUE THREAD

**Issue by Ratsbew** [FlutterFlow/flutterflow-issues#1683]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

With the latest FlutterFlow update, the initial (countdown) time for the timer widget doesn't get set any more, if the value comes from a variable. If the value gets hardcoded, the initial time gets set as expected. 

### Expected Behavior

The initial time for the timer widget should be set to the value of the widget parameter "Countdown Time(ms)" regardless of whether the value comes from a variable or it gets hardcoded.

### Steps to Reproduce

1. Use the latest FlutterFlow release (October 20, 2023)
2. Create a new page
3. Add a timer widget (type countdown)
4. Add a value from a variable (integer) in the "Countdown Time(ms)" - field
5. Run / test the app and see that the initial time doesn't get set

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Context

 -

### Visual documentation

<img width="804" alt="FlutterFlowTimerController_class" src="https://github.com/FlutterFlow/flutterflow-issues/assets/87870776/50e1b812-2769-4fa4-bdc3-2e80b64001fd">
<img width="1774" alt="page_model" src="https://github.com/FlutterFlow/flutterflow-issues/assets/87870776/1b435d90-0c88-42b5-9efe-288955b4185c">
<img width="1787" alt="page_widget" src="https://github.com/FlutterFlow/flutterflow-issues/assets/87870776/8bd122fa-8012-4f12-9cce-0cf7292ff59c">

### Additional Info

Since the `widget.controller.timer.setPresetTime(mSec: widget.initialTime, add: false);` got relocated from the FlutterFlowTimerController class to the page's Model, in the recent FlutterFlow update, the initial time doesn't get set, if it comes from a variable.

### Environment

```markdown
- FlutterFlow version: FlutterFLow v4.0 released October 20, 2023 
- Platform: Web / MacOS Desktop
- Browser name and version: Google Chrome v118.0.5993.96
- Operating system and version affected: macOS Ventura 13.6
```

**Comment by Fibn007** [comment]
Hi, I also noticed this problem and have it as well. Can confirm that it works with a hardcoded integer but does not run from my custom function that returns an integer and is used as input into a timer.

**Comment by Nouss-R** [comment]
Same issue here.

**Comment by hariprasadms** [comment]
Hi, Thanks for submitting the issue. I have tested above steps. I am not able to reproduce the issue. Reproduce the issue in a blank project and share project bug report code. Thanks

**Comment by gsleininger** [comment]
I have the same issue. Timer widget initial value comes up as zero when set from a variable (mine comes from a custom function or code expression that returns an integer). Hard coding a value does work correctly. This issue was definitely popped up with the latest flutterflow update last Thursday. My code was working correctly before that update.

**Comment by gsleininger** [comment]
After testing today, it looks like the issue is resolved. My timer is working correctly again.

**Comment by Fibn007** [comment]
Just updating, mine is also working now today.

**Comment by Ratsbew** [comment]
After the widget.controller.timer.setPresetTime(mSec: widget.initialTime, add: false); got relocated back to the FlutterFlowTimerController class, the timer is working correctly, again. Thanks!

**Comment by Nouss-R** [comment]
Yes it is fixed now, thanks.

**Comment by Ryujinie** [comment]
hi, I still have this issue on my end, do flutterflow need to be updated manually?

**Comment by cranthon** [comment]
@hariprasadms Not sure if I need to create a new issue or if this one can be reactivated, but looks like this issue is back. I'm on FlutterFlow 4.1 w/ Flutter 3.13.7.
