### ISSUE TITLE
Cannot click on Dropdown item when it overlaps a WebView

### ISSUE THREAD

**Issue by yogeshpatelTD** [FlutterFlow/flutterflow-issues#1691]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have encountered a strange behavior.

I have a page on which there is Component for navigation. Inside this component there is Dropdown Widget.

Now when a user clicks on the Dropdown it opens and show all the items inside it but the user cannot click on any items which are overlapping above the WebView as all the click events are received/captured by WebView.

### Expected Behavior

User should be able to click on items that are overlapping on Web View.

### Steps to Reproduce

1. Create a page
2. Place a Dropdown widget with many items
3. Place a Web View widget and load some URL in it
4. Publish code
5. Go to published url
6. Clink on Dropdown to open it and try to click on any item that is overlapping the Web View widget (you will not be able to click on it)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48ls/l5Yx2tbxY17X6YMExljw5JUc7bLsriOx+cws8J5zKB+wAYvf7P1FWTLy/YEFcf06Zhjg0xvfqjuOWCcYnGE+rfNU61rtuaTzNWn67RKqMEs63fW1fI/5UBWK014mvmRUmPuloWCEk6kyINui9HwPACZT6NTMFJvGlKdeK2SrDX1iXc2URm05KZDPz

### Context

I am using a third party Dashboard BI tool and embedding it in my web app.

Now this works but as user is not able to interact with Dropdown items I have to change the design of the page which the client is not accepting.

### Visual documentation

![Screenshot](https://github.com/FlutterFlow/flutterflow-issues/assets/117966150/22e7bf95-15e6-433c-afec-5b7af1777b23)

The part shown in Yellow is the WebView and the part with a Red color rectangle is the list of Dropdown items.

Here we can Click on the Log Out item but cannot click on Edit Profile item.

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Version 118.0.5993.89 (Official Build) (64-bit)
- Operating system and version affected: All
```

**Comment by yogeshpatelTD** [comment]
Are there any chances of solving this BUG?

**Comment by sabatage3** [comment]
Hello, I am also experiencing this issue, can't use any clickable widget on top of a WebView widget, tried everything, but nothing works

**Comment by victoriahuang1** [comment]
Hi @sabatage3 , thanks for the report. This should be fixed upon the next deploy

**Comment by kkoobe11** [comment]
still doesn't really work on test mode, works on iOS simulators i used
