### ISSUE TITLE
Desktop App / Web Error Inconsistencies

### ISSUE THREAD

**Issue by davhad** [FlutterFlow/flutterflow-issues#178]
When using the web and app version of flutterflow, one of the two will always mark firebase indexing and other config as missing. 
Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

The bug and issues highlighted along with the count on web and desktop should be consistent.

## Current behavior (required)

If you fix it be deploying for example when indexing firestore through the flutterflow interface, then the instance being used is marked gets 0 errors and the other gets errors. Vice versa also happens. 

## To Reproduce (required)
1. Open both instances desktop app and web of flutterflow
2. Remove all errors from one. 
3. Note that errors are gone and running and deployment is possible.
4. Go to the other instance and note how the errors are there.
5. Fix the errors on this instance. 
6. Note how the errors now appear in the first instance.

## Your environment
Latest version of Flutterflow on mac and web.

**Comment by pstatile** [comment]
Thumbs up!

**Comment by wenkaifan0720** [comment]
Hi @davhad. Is this still the case? I just created a project and didn't see this issue on web/desktop. If it is, could you share with me the project id? Thank you!

**Comment by pstatile** [comment]
HI! It still happens. I use the flutterflow macOS desktop app and when I am at another location I use the web version. Each time I go to the other, it has 6 arrors, asking me to re-deploy push notifications, braintree, stripe, check functions, firebase rules and another thing I don't recall now. 
Thanks!

**Comment by wenkaifan0720** [comment]
Hi @pstatile. This is due to the hashing function (used for detect deployment validity) difference across different platforms in Dart. We have switched to use a custom hash function that is consistent. We will roll out the new hash gradually (as the user needs to deploy once again). I'll close this issue for now. Thank you!

**Comment by davhad** [comment]
@wenkaifan0720 @pstatile I'm unsure why this was marked as resolved as the same issue is re-occurring. Just to be clear using 1.1.28 and just now went on desktop to deploy firebase indexes after seeing an error icon. When deployed the desktop version removed the error and the web version raised it. Tried the reverse and also re-occurring.

Also important to highlight that both are used simultaneously because many it's faster to develop on desktop, but higher feature completeness with web.

**Comment by wenkaifan0720** [comment]
Hi @davhad. I should have been more clear. There are a few places that use this hashing function. The users would have to redeploy each of them. That might cause a high load on our backend so I only rolled out the update for half of the places at the moment (and firebase is not included for now). I will continue to roll out the rest of them maybe next week. 

I'll reopen this issue just to remind me to fully fix it. But don't worry, the issue will be resolved.

**Comment by davhad** [comment]
@wenkaifan0720 ok great. thanks for sharing details and confirming you're on your way to getting fixed.

**Comment by wenkaifan0720** [comment]
Hi @davhad. The rest of the fix has been pushed. Just wait for a few days before it's live. Thank you!

**Comment by davhad** [comment]
@wenkaifan0720 wenkai thanks, appreciate your effort. Should make for a smoother experience :)

**Comment by pstatile** [comment]
HI! There are still two things that still appear to be reproducing the
problem: Firebase Indexes, Firebase Storage Setup and Custom Widgets. Those
3 still ask me to fix errors when changing from desktop <-> web.

[image: Captura de pantalla 2022-12-30 a la(s) 09.53.07.png]

Thanks!

**Comment by pstatile** [comment]
<img width="355" alt="Captura de pantalla 2022-12-30 a la(s) 09 53 07" src="https://user-images.githubusercontent.com/50183743/210072465-f01686c8-eaa9-410d-92c7-0d62206035aa.png">

**Comment by pstatile** [comment]
I hope this will be ok in a few days, but left  you all the information in case you need it. Thanks!
