### ISSUE TITLE
Searching the Icons library Breaks the app

### ISSUE THREAD

**Issue by lincolnmudau** [FlutterFlow/flutterflow-issues#1789]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have just realized that from projects that have custom icons I cannot search the icons library, it breaks the project. I tried it on the web and the macOS app. It was working well before.

### Expected Behavior

I should be able to search custom icons

### Steps to Reproduce

1. Create a new project or existing project
2. Add custom icons (cool-icons/eva-icons/feather-icons/hero-icons/remix-icons
3. Search Icons library

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz/HluIhOsdhE7aX6bu9WoDg4OUAnRJc0st4bGAsdGOvrBqQTdcj7M0tVXdDiaVNfeWeKmnoypOCNidmXGMACG02ZQIR9/6V2TTzke2iXRqqVCajpSXJSEtFPIUCg3MGZkSV5NbFeV3AB7TnzB+SsTg/DFOu/Zwh9f6PHaOI=

### Context

I cannot search for icons anymore, i have to scroll the whole library (+6000 icons) to get an icon i want. takes time

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/74670651/1cc78fc4-97da-4f9b-88b1-a32b5a9c4e85

### Environment

```markdown
- FlutterFlow version: 4.0.2 (Mac) & 4.0 (Released 4 Nov 23 - Web)
- Platform: Web & macOS
- Browser name and version:Chrome Version 119.0.6045.105 (Official Build) (x86_64)
- Operating system and version affected: macOS Monterey 12.6
```

**Comment by hariprasadms** [comment]
Hi @lincolnmudau - Thanks for submitting the issue. I have looked at your project. I can see the issue exists in the project. However, when I test the same steps in different projects, nothing going wrong but all working as expected. 

Looking at the number of custom icons you have uploaded, I guess the issue should be around uploaded custom icons. 

When you remove uploaded custom icons set by set, are you able to see any changes? Give it a try and let me know. 

I can classify this as a project-specific bug.

**Comment by lincolnmudau** [comment]
Hi @hariprasadms , thanks for getting back to me. I tried to individually remove each set and noticed that the problem was with the "remix Icons set".... which is strange as it was working fine before the update

**Comment by av3n93rz** [comment]
This is not a project specific issue. It breaks on our project as well, even when we are trying to search for widgets. We dont have any custom icons.
It works fine in the web application, breaks in the desktop app.

**Comment by LuisFlywheel** [comment]
I have the same problem when I try to search for a specific icon. Breaks in the web app (using Chrome). It used to work well. 

https://github.com/FlutterFlow/flutterflow-issues/assets/132684664/c5de8ad6-d571-4001-b732-59155c901782

**Comment by brian-tempo** [comment]
I'm having the same issue. Searching for icons on the flutterflow web app breaks the app.

**Comment by BryanFlywheel** [comment]
I am having this issue as well.

**Comment by syg-eliseu** [comment]
I'm also going through this, I've been using the same icon pack since the beginning of the project but I'm going through this recently

**Comment by LuisFlywheel** [comment]
This problem has been solved

**Comment by lincolnmudau** [comment]
The problem is only solved on the web and not the macOS app. Just installed a new dmg and still experiencing the issue

**Comment by agreaves** [comment]
Hey folks, confirming that this issue was indeed fixed so I'm closing it for now! Thank you for the bug report and necessary info.
