### ISSUE TITLE
CheckBoxGroup returns null when selection loaded from PageState variable

### ISSUE THREAD

**Issue by KeepTrackSolutions** [FlutterFlow/flutterflow-issues#1865]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We have created a CheckBoxGroup to which options can be added using a TextField and buttons.  When a button is pressed, the value of the TextField is added to 2 Page State String Lists (list and selected).  These are assigned to the options and selection for the CheckBoxGroup.  When pressed, the CheckBoxGroup displays the option on the screen and shows it checked.  But when I access the Widget State CheckBoxGroup String List it returns null.

### Expected Behavior

Instead of returning null, the Widget State CheckBoxGroup should return the selected String

### Steps to Reproduce

1. Create New Blank Project
2. On Homepage, add 2 page state variables: list and selected.
3. Add CheckBoxGroup and assign list to options and selected to selections
4. Add a TextField and Button.  The action on the Button adds the value of the Text Field to Both page state variables and Rebuilds Current Page.
5. Add Button to display the Widget State value for CheckBoxGroup
6. Run Test Build
7. Type a String into TextField
8. Press Button to add option, selection, and rebuild the page.  CheckBoxGroup displays new option and shows it selected.
9. Press Button to display SnackBar with Widget State CheckBoxGroup.  This shows null.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4elcr135VNj7xZ1s7fbfkxhiYRKUs7U403m+0aaAwgF7WuE5oTOuj+XGZtTdO4TwlEP2aLrHIyp87IhIbXFPknCxeVbIs73JVqThfiJD+5VJiUCKmwSERtJJtbN2KuyLes2xFGA+FhdEYO2maYNd7KbA/fQ+fYIW0jD/yHKq/A+mzlFSTBMSxV0TQXEx7eTI5ODEz25eKMrop5yfj/0w==

### Context

I am trying to build a selection component which can have options added to it.
Once added and selected, these options will be used in Actions

### Visual documentation

Here is a video from the blank project set up to demonstrate the issue.

https://github.com/FlutterFlow/flutterflow-issues/assets/134727359/bb6b0075-0743-4888-86b6-2c410e702d2e

### Additional Info

<img width="145" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134727359/712cc2c7-1bb0-4967-87dc-3311e3f6b5e0">

<img width="143" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134727359/2409fee1-7101-486d-aa82-3e4abe8b158f">

<img width="146" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134727359/8a4c0c71-4791-448c-8945-db4b24cd3ea4">

<img width="146" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134727359/c66365ab-4ed6-458d-a634-92c4fd30b89b">

<img width="155" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134727359/747938f8-9897-40ff-9da2-8b4bb652e70e">

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: x86
- Browser name and version: Google Chrome Version 119.0.6045.124 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by KeepTrackSolutions** [comment]
This is still an issue for us.  Please let us know if you need any more detail to reproduce the issue.

**Comment by KeepTrackSolutions** [comment]
Has anyone been able to take a look at this?  This is still an issue.  I wouldn't chase except the bot will mark things stale if I don't. @agreaves @SameerShahzad99

**Comment by hariprasadms** [comment]
Hi, Apologies for the delayed response. Since the issue doesn't seem to be widespread and hasn't received further follow-up, it may have been inadvertently overlooked. Given the age of the issue, it's possible that it has been addressed in the latest FlutterFlow updates. Please verify if you are still encountering the problem, and if so, we can proceed with investigating it further. I've marked the issue status as _"waiting for user response"_ and will leave it open for the next 4 days before closing it. Thank you for your understanding.

**Comment by KeepTrackSolutions** [comment]
@hariprasadms This is still an issue in the latest FlutterFlow version.  The project we set up to demonstrate this issue still shows null responses.

**Comment by msusviela** [comment]
Hi @KeepTrackSolutions, I was able to reproduce the issue, I will send it to the ENG team so they can work on this!
