### ISSUE TITLE
Can't stop audioplayer after navigating to another page and going back to audioplayer page

### ISSUE THREAD

**Issue by Ryujinie** [FlutterFlow/flutterflow-issues#1872]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I start the audioplayer and navigate forward to another page, when I go back to the page with audioplayer, the pause button is not working, music keeps on playing. It only works if I play the music audio again but it overlays on the previously playing audio

### Expected Behavior

I expected the pause button to pause the audioplayer

### Steps to Reproduce

1. Create 2 pages (firstpage, secondpage)
2. Add audioplayer in firstpage
3. Set audio type to network and path https://filesamples.com/samples/audio/mp3/sample3.mp3
4. Turn off pause on forward navigation
5. Enable play in background
6. Add button to navigate to second page
7. Show both pages on navbar
8. Test
9. Play audioplayer
10. Click button to navigate to 2nd page
11. Go to first page via the navbar
12. Click pause audioplayer

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oiMjfsJRIocMA1aXide9amSQ7OVt9U50vkcpBczodGIjuPO8EfPTOak5vZryndHxcM2eGhnsK1vfqhvH2GsFeCzOrR4A6+roNVgnwLUOjaZPSO7iJfW1fGdxXfVTF4baF3RJNANV1LmRn61yMB+jIY3bvHuPQOFURO/G1KdeK2SrDX1iXc2URm05KZDPz

### Context

I'm creating a music player in one of the pages of my app, this bug won't allow the user to pause the currently playing audio and select another until its finished resulting to bad user experience

### Visual documentation

![Capture](https://github.com/FlutterFlow/flutterflow-issues/assets/72432031/4eb15a74-5601-4e04-ac8b-88c673e4954c)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform:Web
- Browser name and version: Microsoft Edge
- Operating system and version affected: Windows 10.0.19045
```

**Comment by hariprasadms** [comment]
Hi, Apologies for the delayed response. Since the issue doesn't seem to be widespread and hasn't received further follow-up, it may have been inadvertently overlooked. Given the age of the issue, it's possible that it has been addressed in the latest FlutterFlow updates. Please verify if you are still encountering the problem, and if so, we can proceed with investigating it further. I've marked the issue status as _"waiting for user response"_ and will leave it open for the next 4 days before closing it. Thank you for your understanding.

**Comment by hariprasadms** [comment]
If the same issue persists, kindly create a new issue with additional details. Thank you!

**Comment by ks233ever** [comment]
I can confirm this issue is still happening. It looks like this bug has been open since November and has not yet been addressed, along with the audio player title overflow[ issue](https://github.com/FlutterFlow/flutterflow-issues/issues/2234), which has been open for over a month. Does Flutterflow have any SLAs for bugs? Curious when or even if any of these issues will be addressed?
