### ISSUE TITLE
Renaming any widget exits after inputting 2 chars

### ISSUE THREAD

**Issue by mferraroni** [FlutterFlow/flutterflow-issues#1991]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Renaming any widget exits after inputting 2 chars.

### Expected Behavior

Rename should exit when return is pressed.

### Steps to Reproduce

1. Create new project
2. Add any widget (e.g. a container widget)
3. Double-click its name to rename it
4. Start typing the new name
5. Observe the widget takes only 2 chars and then exits forcing you to double-click again to continue the input of the new name

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kzcrl+Y9OxLlE0LXhbcdop2AQNmY2TL03pu0bFEggGLbrBIYMafTOVxNVXbDidFVpKEWLkk8x//THvtnxGsYEAw2aRqJYyqlpWBbNeEO/aoSPDs2efGskJJpWJlfD0Z7R3QlANfppZU4k7E73F+iXYHPrO5f7Zwh9f6PHaOI=

### Context

I am trying to rename my widget so it will be easier to know what is what.

### Visual documentation

https://watch.screencastify.com/v/s1nppoknFHt4wH0eSi8x

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Any
- Browser name and version: Chrome 119.0.6045.199
- Operating system and version affected: MacOs Ventura (13.6)
```

**Comment by 47X** [comment]
Same here. Annoying AF. You can rename using the property editor on the right, though.

**Comment by mferraroni** [comment]
> Same here. Annoying AF. You can rename using the property editor on the right, though.

Thank you! I didn't know it.

**Comment by rahil320** [comment]
I think the issue is resolved by FF team as it is not occurring in my projects now

**Comment by itailulu** [comment]
Still happens to me, using Mac 12.6 and Chrome Version 120.0.6099.109 (Official Build) (x86_64)
