### ISSUE TITLE
LateInitializationError: Field '_prefs' has not been initialized. exception when running integration tests.

### ISSUE THREAD

**Issue by zgorawski** [FlutterFlow/flutterflow-issues#2070]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Got `LateInitializationError: Field '_prefs' has not been initialized` error when running integration test.

I've briefly checked the code and spotted that SharedPrefs used in the `internationalization.dart` file are not optional (unlike the ones used in the `flutter_flow_theme`).

### Expected Behavior

Test should be executed without error

### Steps to Reproduce

1. Create project
2. Add tests
3. Add second language (?)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oj8ncx492xLhA7a6JcvlV/SY5KWU7U6xMlsJxUUk2F5PNG7IUY8jeVGVtXdOhdH02eFqjkTgK3NGOvubIN+4CGz6YbKZbzalidgvxXn67SqaMErrtX3d9FtpKC36P36e4nghBCPp0WUIb11yIHfPKcC/vQJDQDDIBBcn9D53Us3PuQ0SLb3kNh1JWeC/v

### Context

Was trying to use tests feature

### Visual documentation

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following LateError was thrown building _InheritedProviderScope<FFAppState?>(value: <not yet
loaded>):
LateInitializationError: Field '_prefs' has not been initialized.

The relevant error-causing widget was:
  _InheritedProviderScope<FFAppState?>
  _InheritedProviderScope:file:///Users/zgorawski/.pub-cache/hosted/pub.dev/provider-6.0.5/lib/src/inherited_provider.dart:161:12

### Environment

```markdown
- FlutterFlow version: 4.0.3
- Platform: MacOS
- Browser name and version: -
- Operating system and version affected: -
```

**Comment by zgorawski** [comment]
I've fixed the test by adding following lines below ` _overrideOnError();`

```
    SharedPreferences.setMockInitialValues({'__locale_key__': 'en'});
    await FFLocalizations.initialize();
```

but it will be of course overridden by the FlutterFlow and proper solution needs to be done on the platform level. Cheers!

**Comment by wenkaifan0720** [comment]
Hi @zgorawski. This should be fixed in our next update. Thanks!

Just to be sure, is this line ` SharedPreferences.setMockInitialValues({'__locale_key__': 'en'});` necessary? The current fix doesn't include this line and the test can be passed.

**Comment by BobFactory** [comment]
@wenkaifan0720 I still see this issue happening at my end. My FlutterFLow version details are 

FlutterFlow v4.1 released February 15, 2024
Flutter version is 3.13.7

I am using Custom Auth manager and below is my full stacktrace: 

```
═╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following LateError was thrown running a test:
LateInitializationError: Field '_prefs' has not been initialized.

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3  throw_
packages/ecp_app/auth/custom_auth/custom_auth_manager.dart 99:26             get [_prefs]
packages/ecp_app/auth/custom_auth/custom_auth_manager.dart 138:18            persistAuthData
packages/ecp_app/auth/custom_auth/custom_auth_manager.dart 37:5              signOut
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54           runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5           _async
packages/ecp_app/auth/custom_auth/custom_auth_manager.dart 27:17             signOut
test.dart 27:23                                                              <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1407:47                                         _rootRunUnary
dart-sdk/lib/async/zone.dart 1308:19                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 846:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                                    [_completeWithValue]
dart-sdk/lib/async/future.dart 529:22                                        <fn>
dart-sdk/lib/async/zone.dart 1407:47                                         _rootRunUnary
dart-sdk/lib/async/zone.dart 1308:19                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 846:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 721:7                                    <fn>
dart-sdk/lib/async/zone.dart 1399:13                                         _rootRun
dart-sdk/lib/async/zone.dart 1301:19                                         run
dart-sdk/lib/async/zone.dart 1209:7                                          runGuarded
dart-sdk/lib/async/zone.dart 1249:23                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>

```

We need this in our project on an urgent basis to demo this to the client so any workarounds would be appreciated.

**Comment by SEGVeenstra** [comment]
Experience the same issue on the same version.
Seems to be Custom Auth related.

I also commented out the `authManager.signOut();` part and then that part works, but as soon as it tries to login the same error occurs.
