### ISSUE TITLE
DataTable not working with Light & Dark Mode - bug + Shrink table

### ISSUE THREAD

**Issue by eduriftio** [FlutterFlow/flutterflow-issues#2265]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The background of the Data field in DataTable is not working; it shows Light mode only in the published web app. It shows properly in the Flutterflow dashboard, though. Also there is no way to Shrink the table if only a few data rows. It would be great if the table could adjust the height based on the data loaded, if one row is available, the table would shrink to one data only.

### Expected Behavior

The data show change the color based on the mode.

### Steps to Reproduce

1. Create a DataTable widget
2. Assign Light and Dark modes with different colours
3. Test Dark and Light mode in the Flutterflow app dashboard; you should see changes.
4. Publish the web app
5. Change the mode from Light to Dark and reverse. The data font color and background do not change color.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk/H634ZNodcA+ZSJcsExgWQQJmEcTuQ/itUbTQ0gF4jyBJsUZ8nRQHdVXc+hdG02MWCJsD4J+vTLhebIN8EDPSqqY4BMwbpuSDqXIUy7VYikDZe0dEQnLNpKCG6y17e4kSMkLs1YdHw1w16uf+6XTnbvCYy3PGswAM6lJqXInXPuQ0SLb3kNh1JWeC/v

### Context

I need the data to be adjusted by Dark or Light mode just like all other widgets

### Visual documentation

![Screenshot 2024-01-30 at 14 14 20](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9a710a3d-a682-48fe-a4da-7d5eb690356f/b351f2b5-d26b-4a5f-8337-52ff6daaaf70?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85YTcxMGEzZC1hNjgyLTQ4ZmUtYTRkYS03ZDVlYjY5MDM1NmYvYjM1MWYyYjUtZDI2Yi00YTVmLTgzMzctNTJmZjZkYWFhZjcwIiwiaWF0IjoxNzA2NzQ2ODk1LCJleHAiOjMzMjc3MzA2ODk1fQ.i2eGXkNzOzW6YQTr45trHxzTdyJiEwrDz2Dnl_MSJZU)

![Screenshot 2024-01-30 at 14 14 15](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c5709975-b86a-4d62-8bf5-ee182e34df23/1e94c002-93e7-4a5a-8290-cac7d6dfb97c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNTcwOTk3NS1iODZhLTRkNjItOGJmNS1lZTE4MmUzNGRmMjMvMWU5NGMwMDItOTNlNy00YTVhLTgyOTAtY2FjN2Q2ZGZiOTdjIiwiaWF0IjoxNzA2NzQ2ODk1LCJleHAiOjMzMjc3MzA2ODk1fQ.5tARexUzXUhM8zMAYvVxWCzrCFPQ7oMsKxUDmBsgEJc)

![Screenshot 2024-01-30 at 14 13 54](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/da660140-cf05-4c1b-b359-2d2bdeff45cc/6f77c672-a583-4cd5-89e8-0d0c87c0226e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kYTY2MDE0MC1jZjA1LTRjMWItYjM1OS0yZDJiZGVmZjQ1Y2MvNmY3N2M2NzItYTU4My00Y2Q1LTg5ZTgtMGQwYzg3YzAyMjZlIiwiaWF0IjoxNzA2NzQ2ODk1LCJleHAiOjMzMjc3MzA2ODk1fQ.vxFWue9G7Rl20jERoVGhzzTYQM-pvQl8zXZkmD5iv_o "=1301x")

![Screenshot 2024-01-30 at 14 13 48](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b1b68792-a887-4b65-9858-37f5484d9720/6b80a7d2-8d39-450d-b3ca-fbd40ec6d122?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iMWI2ODc5Mi1hODg3LTRiNjUtOTg1OC0zN2Y1NDg0ZDk3MjAvNmI4MGE3ZDItOGQzOS00NTBkLWIzY2EtZmJkNDBlYzZkMTIyIiwiaWF0IjoxNzA2NzQ2ODk1LCJleHAiOjMzMjc3MzA2ODk1fQ.daaJzoBK12F-pecUJDVx4L6m4yFeupFv_Ds4IggW6uI "=1305x")

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: v4.1
- Platform: Web
- Browser name and version:121.0.6167.85
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by eduriftio** [comment]
We are eager to use the new DataTable to replace all custom bunch of components and widgets; please write good documentation on how to use the new DataTable and fix issues. Shrink table so it is not full height, Light and Dark mode and backend queries.

**Comment by hariprasadms** [comment]
Hi @eduriftio - Thanks for submitting the issue. Here are the updates related to the points mentioned in the issue details.

1. The new data table widget is intentionally designed without a background color by default to allow it to seamlessly blend with the page background. However, you can achieve a background color by wrapping the data table with a container widget.
2. The font color (Text widget color) for data is functioning as expected in both dark and light modes.
3. Regarding the shrink table, it currently aligns with the design specifications.
 
If you believe there are issues preventing you from achieving the expected result using existing data table properties, please provide a blank project replicating all the mentioned issues. Share the bug report code for the same project. So that it can help us in investigating the reported to the points. Thank you.

**Comment by hariprasadms** [comment]
Just added a quick video about dark and light mode of DT widget. 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/d497f463-cac8-4e1b-98ca-70777fde26a9

**Comment by takashiff** [comment]
Hi @eduriftio, in regards to the shrink wrap effect, you can change the "Expansion" setting of the DataTable to have the height/width adapt and be constrained to the parent Column/Row. Please see the attached screenshot for reference. Thanks
<img width="295" alt="Screenshot 2024-02-02 at 12 40 03 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134453477/5f270d7f-22c6-4aa1-b066-ef294a61bf2a">

**Comment by agreaves** [comment]
Hi @eduriftio, thanks for the report! We've fixed several bugs around data table including the dark mode / light mode issue and @takashiff's suggestion is a good approach for the other issue you mentioned! Closing for now.

**Comment by eduriftio** [comment]
> Hi @eduriftio, in regards to the shrink wrap effect, you can change the "Expansion" setting of the DataTable to have the height/width adapt and be constrained to the parent Column/Row. Please see the attached screenshot for reference. Thanks <img alt="Screenshot 2024-02-02 at 12 40 03 PM" width="295" src="https://private-user-images.githubusercontent.com/134453477/301966646-5f270d7f-22c6-4aa1-b066-ef294a61bf2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NjM1NTksIm5iZiI6MTcwNjk2MzI1OSwicGF0aCI6Ii8xMzQ0NTM0NzcvMzAxOTY2NjQ2LTVmMjcwZDdmLTIyYzYtNGFhMS1iMDY2LWVmMjk0YTYxYmYyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QxMjI3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2M4MDUxMjc3YmE1YTY5MTc5MzcxMmYzYmQxYmEyMDQ0MGIzYWRlNGRmOTZkZmNjYTM4MjJkNWM4MTJmY2E0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lk5b9YoR7oxaRsqTGlfTYCVYgwww_WSptx9yhDPo424">

Hi @takashiff what I mean by Shrinking is the content. For example, I have a list of invoices and if I have only 2 invoices, I still see the whole table. What I suggest is to shrink the table so it expands by the amount of raws. 
![Screenshot 2024-02-03 at 22 27 02](https://github.com/FlutterFlow/flutterflow-issues/assets/145130088/f5d605ae-5f89-43ea-bbad-ed17fad1d7e6)

**Comment by eduriftio** [comment]
@takashiff This is another example how it looks like without Shrinking option. It is inside a container and still cannot resize to fit. 
![Screenshot 2024-02-06 at 16 34 09](https://github.com/FlutterFlow/flutterflow-issues/assets/145130088/40365555-286d-40c7-8302-cd8aa216f66b)

**Comment by takashiff** [comment]
Hi @eduriftio, thank you for the additional information. This is currently intentional behavior behind our DataTable widget, but I understand your desired behavior. I'll mark this as a feature request so that it may be implemented in the future. Thanks
