### ISSUE TITLE
Walktroughs Error

### ISSUE THREAD

**Issue by DevKursat** [FlutterFlow/flutterflow-issues#2488]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Instead of the walktroughs that should run when the page loads, the action that should appear when it finishes is triggered. and I can neither try my code nor get the apk

### Expected Behavior

Walktroughs should start the way I set it, and when it finishes or is skipped, the code I set should run.

### Steps to Reproduce

Just load the Home Page but it is not possible to try the code. Because there is a bug in Walktroughs.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeyfLl05NPn7xJ16X1LccwmQMwGkQ5a7sviu5+FBQaI+P1BIkUe8zRYRJDWOqHS29AH1mbnmEz//CNhYbPJvFcNS6Vf65JzahhUxDhf3y5SqbQDJboe0Z9EcJYCWac5rSrkCNBKsdYdX9m3F6Le9iuY3qCf9qOYwx5e6fDbOY=

### Context

It has prevented me from promoting my app to users and has been preventing me from sending updates for a few days.

### Visual documentation

![Ekran görüntüsü 2024-03-12 131555](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9ef3e9e7-703d-4216-bcdf-f4789cb65656/d8f99f5f-9b6a-4d54-b331-297ece3903c6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ZWYzZTllNy03MDNkLTQyMTYtYmNkZi1mNDc4OWNiNjU2NTYvZDhmOTlmNWYtOWI2YS00ZDU0LWIzMzEtMjk3ZWNlMzkwM2M2IiwiaWF0IjoxNzEwNTIxNzcwLCJleHAiOjMzMjgxMDgxNzcwfQ.ZbGTatUoqH-BW0LzTvjdBQ2LyEBDQzxAtzZX1NriHDk)

![Ekran görüntüsü 2024-03-12 131606](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1d51bd68-09dc-44d3-9eac-7081179baed0/811b73e5-e76a-4056-8895-f0ad65e46c27?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xZDUxYmQ2OC0wOWRjLTQ0ZDMtOWVhYy03MDgxMTc5YmFlZDAvODExYjczZTUtZTc2YS00MDU2LTg4OTUtZjBhZDY1ZTQ2YzI3IiwiaWF0IjoxNzEwNTIxNzcwLCJleHAiOjMzMjgxMDgxNzcwfQ.N3Zwem6FmoONnBYyw9O3ABCAYeVYeQvdXJ_p76cKpvQ)

![Ekran görüntüsü 2024-03-11 124720](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9f8a70d6-dad6-4c53-bb6b-d4c6d005bf57/c2f21400-443c-4374-af90-aa88dd0e2395?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ZjhhNzBkNi1kYWQ2LTRjNTMtYmI2Yi1kNGM2ZDAwNWJmNTcvYzJmMjE0MDAtNDQzYy00Mzc0LWFmOTAtYWE4OGRkMGUyMzk1IiwiaWF0IjoxNzEwNTIxNzcwLCJleHAiOjMzMjgxMDgxNzcwfQ.PuKXHW5AMGNFEkyz8nxwnwaZqLOmCG2Ewvnr3QoGgpE)

![Ekran görüntüsü 2024-03-11 124746](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/03232f2b-ff30-424d-a070-c1bcf35704d8/c232e1fd-db96-4371-9ee7-8d78e01f9c6b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wMzIzMmYyYi1mZjMwLTQyNGQtYTA3MC1jMWJjZjM1NzA0ZDgvYzIzMmUxZmQtZGI5Ni00MzcxLTllZTctOGQ3OGUwMWY5YzZiIiwiaWF0IjoxNzEwNTIxNzcwLCJleHAiOjMzMjgxMDgxNzcwfQ.rzCAuraYCtmXP2p6DQwUe2W7uBvu9ju-smlKW2D0Sa0)

### Additional Info

I don't want to create a new page. The application should not take up much space. Since I thought the Walktroughs feature would not come and I exceeded the project size while adding it as a special function, I made a component that teaches the application. (Not only the Home Page, but all pages in the application were made with conditional visibility, and I coded Walktroughs accordingly in FlutterFlow. Will this never work as I did?)

Component that teaches the application: (I won't delete this, but walktroughs is much more professional than this. I'm looking forward to getting this bug resolved and sending the new update.)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9616d122-67bc-4c52-9ad5-fa8f85939dc4/e83dc372-32f8-4fb3-8c19-b56d6be29db8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NjE2ZDEyMi02N2JjLTRjNTItOWFkNS1mYThmODU5MzlkYzQvZTgzZGMzNzItMzJmOC00ZmIzLThjMTktYjU2ZDZiZTI5ZGI4IiwiaWF0IjoxNzEwNTIxNzcwLCJleHAiOjMzMjgxMDgxNzcwfQ.Ccqlzn2svdgkYcnhpFpUCBYEemxUlZTgIKpzMZNjlhI)

114 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...
lib/detaylar/ana_sayfa/ana_sayfa_model.dart:183:21: Error: 'createPageWalkthrough' is already declared in this scope.
  TutorialCoachMark createPageWalkthrough(BuildContext context) =>
                    ^^^^^^^^^^^^^^^^^^^^^
lib/detaylar/ana_sayfa/ana_sayfa_model.dart:150:21: Context: Previous declaration of 'createPageWalkthrough'.
  TutorialCoachMark createPageWalkthrough(BuildContext context) =>
                    ^^^^^^^^^^^^^^^^^^^^^
lib/detaylar/sosyalles/sosyalles_model.dart:181:21: Error: 'createPageWalkthrough' is already declared in this scope.
  TutorialCoachMark createPageWalkthrough(BuildContext context) =>
                    ^^^^^^^^^^^^^^^^^^^^^
lib/detaylar/sosyalles/sosyalles_model.dart:120:21: Context: Previous declaration of 'createPageWalkthrough'.
  TutorialCoachMark createPageWalkthrough(BuildContext context) =>
                    ^^^^^^^^^^^^^^^^^^^^^
lib/profil/profil_model.dart:205:21: Error: 'createPageWalkthrough' is already declared in this scope.
  TutorialCoachMark createPageWalkthrough(BuildContext context) =>
                    ^^^^^^^^^^^^^^^^^^^^^
lib/profil/profil_model.dart:170:21: Context: Previous declaration of 'createPageWalkthrough'.
  TutorialCoachMark createPageWalkthrough(BuildContext context) =>
                    ^^^^^^^^^^^^^^^^^^^^^
lib/walkthroughs/ana_sayfa_etkinlikler.dart:26:23: Error: Undefined name 'FFLocalizations'.
              baslik: FFLocalizations.of(context).getText(
                      ^^^^^^^^^^^^^^^
lib/walkthroughs/ana_sayfa_etkinlikler.dart:29:25: Error: Undefined name 'FFLocalizations'.
              aciklama: FFLocalizations.of(context).getText(
                        ^^^^^^^^^^^^^^^
lib/walkthroughs/ana_sayfa_etkinlikler.dart:48:23: Error: Undefined name 'FFLocalizations'.
              baslik: FFLocalizations.of(context).getText(
                      ^^^^^^^^^^^^^^^
lib/walkthroughs/ana_sayfa_etkinlikler.dart:51:25: Error: Undefined name 'FFLocalizations'.
              aciklama: FFLocalizations.of(context).getText(
                        ^^^^^^^^^^^^^^^
lib/walkthroughs/ana_sayfa_takip_edilenler.dart:27:23: Error: Undefined name 'FFLocalizations'.
              baslik: FFLocalizations.of(context).getText(
                      ^^^^^^^^^^^^^^^
lib/walkthroughs/ana_sayfa_takip_edilenler.dart:30:25: Error: Undefined name 'FFLocalizations'.
              aciklama: FFLocalizations.of(context).getText(
                        ^^^^^^^^^^^^^^^
lib/walkthroughs/ana_sayfa_takip_edilenler.dart:50:23: Error: Undefined name 'FFLocalizations'.
              baslik: FFLocalizations.of(context).getText(
                      ^^^^^^^^^^^^^^^
lib/walkthroughs/ana_sayfa_takip_edilenler.dart:53:25: Error: Undefined name 'FFLocalizations'.
              aciklama: FFLocalizations.of(context).getText(
                        ^^^^^^^^^^^^^^^
lib/walkthroughs/ana_sayfa_takip_edilenler.dart:73:23: Error: Undefined name 'FFLocalizations'.
              baslik: FFLocalizations.of(context).getText(
                      ^^^^^^^^^^^^^^^
lib/walkthroughs/ana_sayfa_takip_edilenler.dart:76:25: Error: Undefined name 'FFLocalizations'.
              aciklama: FFLocalizations.of(context).getText(
                        ^^^^^^^^^^^^^^^
lib/detaylar/ana_sayfa/ana_sayfa_model.dart:152:18: Error: 'createWalkthroughTargets' is imported from both 'package:kursat/walkthroughs/ana_sayfa_etkinlikler.dart' and 'package:kursat/walkthroughs/ana_sayfa_takip_edilenler.dart'.
        targets: createWalkthroughTargets(context),
                 ^^^^^^^^^^^^^^^^^^^^^^^^
lib/detaylar/ana_sayfa/ana_sayfa_model.dart:154:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'AnaSayfaModel'.

* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
         if (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.fEtkinliklertArkadaslar) {
             ^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:155:13: Error: The method 'setState' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:156:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToTanitilanOzellikler('Etkinlik');
             ^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:160:13: Error: The method 'setState' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:161:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToTanitilanOzellikler('Takip Edilen');
             ^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:167:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
         if (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.fEtkinliklertArkadaslar) {
             ^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:168:13: Error: The method 'setState' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:169:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToTanitilanOzellikler('Etkinlik');
             ^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:173:13: Error: The method 'setState' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:174:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToTanitilanOzellikler('Takip Edilen');
             ^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:171:13: Error: A value must be explicitly returned from a non-void function.
           return;
           ^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:176:13: Error: A value must be explicitly returned from a non-void function.
           return;
           ^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:185:18: Error: 'createWalkthroughTargets' is imported from both 'package:kursat/walkthroughs/ana_sayfa_etkinlikler.dart' and 'package:kursat/walkthroughs/ana_sayfa_takip_edilenler.dart'.
       targets: createWalkthroughTargets(context),
                ^^^^^^^^^^^^^^^^^^^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:187:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
         if (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.fEtkinliklertArkadaslar) {
             ^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:188:13: Error: The method 'setState' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:189:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToTanitilanOzellikler('Etkinlik');
             ^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:193:13: Error: The method 'setState' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:194:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToTanitilanOzellikler('Takip Edilen');
             ^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:200:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
         if (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.fEtkinliklertArkadaslar) {
             ^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:201:13: Error: The method 'setState' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:202:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToTanitilanOzellikler('Etkinlik');
             ^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:206:13: Error: The method 'setState' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:207:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'AnaSayfaModel'.
* 'AnaSayfaModel' is from 'package:kursat/detaylar/ana_sayfa/ana_sayfa_model.dart' ('lib/detaylar/ana_sayfa/ana_sayfa_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToTanitilanOzellikler('Takip Edilen');
             ^^^^^^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:204:13: Error: A value must be explicitly returned from a non-void function.
           return;
           ^
  lib/detaylar/ana_sayfa/ana_sayfa_model.dart:209:13: Error: A value must be explicitly returned from a non-void function.
           return;
           ^
  lib/walkthroughs/abonelik.dart:25:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/abonelik.dart:28:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/walkthroughs/kesfet.dart:27:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/kesfet.dart:30:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/walkthroughs/kesfet.dart:49:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/kesfet.dart:52:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/walkthroughs/kesfet.dart:71:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/kesfet.dart:74:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:122:18: Error: 'createWalkthroughTargets' is imported from both 'package:kursat/walkthroughs/abonelik.dart' and 'package:kursat/walkthroughs/kesfet.dart'.
       targets: createWalkthroughTargets(context),
                ^^^^^^^^^^^^^^^^^^^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:124:16: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
         if ((\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretilenAlanlar.contains(valueOrDefault(
              ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:129:16: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.tabBarCurrentIndex == 0)) {
              ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:130:13: Error: The method 'setState' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:131:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToOgretilenAlanlar('Keşfet');
             ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:135:18: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
           if ((\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretilenAlanlar.contains(valueOrDefault(
                ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:140:18: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
               (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.tabBarCurrentIndex == 2)) {
                ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:141:15: Error: The method 'setState' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
             setState(() {
             ^^^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:142:17: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
               \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToOgretilenAlanlar('Abone');
               ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:151:16: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
         if ((\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretilenAlanlar.contains(valueOrDefault(
              ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:156:16: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.tabBarCurrentIndex == 0)) {
              ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:157:13: Error: The method 'setState' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:158:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToOgretilenAlanlar('Keşfet');
             ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:162:18: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
           if ((\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretilenAlanlar.contains(valueOrDefault(
                ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:167:18: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
               (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.tabBarCurrentIndex == 2)) {
                ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:168:15: Error: The method 'setState' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
             setState(() {
             ^^^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:169:17: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
               \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToOgretilenAlanlar('Abone');
               ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:160:13: Error: A value must be explicitly returned from a non-void function.
           return;
           ^
  lib/detaylar/sosyalles/sosyalles_model.dart:171:15: Error: A value must be explicitly returned from a non-void function.
             return;
             ^
  lib/detaylar/sosyalles/sosyalles_model.dart:173:15: Error: A value must be explicitly returned from a non-void function.
             return;
             ^
  lib/detaylar/sosyalles/sosyalles_model.dart:183:18: Error: 'createWalkthroughTargets' is imported from both 'package:kursat/walkthroughs/abonelik.dart' and 'package:kursat/walkthroughs/kesfet.dart'.
       targets: createWalkthroughTargets(context),
                ^^^^^^^^^^^^^^^^^^^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:185:16: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
         if ((\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretilenAlanlar.contains(valueOrDefault(
              ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:190:16: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.tabBarCurrentIndex == 0)) {
              ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:191:13: Error: The method 'setState' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:192:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToOgretilenAlanlar('Keşfet');
             ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:196:18: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
           if ((\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretilenAlanlar.contains(valueOrDefault(
                ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:201:18: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
               (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.tabBarCurrentIndex == 2)) {
                ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:202:15: Error: The method 'setState' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
             setState(() {
             ^^^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:203:17: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
               \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToOgretilenAlanlar('Abone');
               ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:212:16: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
         if ((\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretilenAlanlar.contains(valueOrDefault(
              ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:217:16: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.tabBarCurrentIndex == 0)) {
              ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:218:13: Error: The method 'setState' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:219:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToOgretilenAlanlar('Keşfet');
             ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:223:18: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
           if ((\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretilenAlanlar.contains(valueOrDefault(
                ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:228:18: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
               (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.tabBarCurrentIndex == 2)) {
                ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:229:15: Error: The method 'setState' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
             setState(() {
             ^^^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:230:17: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'SosyallesModel'.
* 'SosyallesModel' is from 'package:kursat/detaylar/sosyalles/sosyalles_model.dart' ('lib/detaylar/sosyalles/sosyalles_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
               \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToOgretilenAlanlar('Abone');
               ^^^^^^
  lib/detaylar/sosyalles/sosyalles_model.dart:221:13: Error: A value must be explicitly returned from a non-void function.
           return;
           ^
  lib/detaylar/sosyalles/sosyalles_model.dart:232:15: Error: A value must be explicitly returned from a non-void function.
             return;
             ^
  lib/detaylar/sosyalles/sosyalles_model.dart:234:15: Error: A value must be explicitly returned from a non-void function.
             return;
             ^
  lib/walkthroughs/tum_sohbetler.dart:25:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/tum_sohbetler.dart:28:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/detaylar/tum_sohbetler/tum_sohbetler_model.dart:69:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'TumSohbetlerModel'.
* 'TumSohbetlerModel' is from 'package:kursat/detaylar/tum_sohbetler/tum_sohbetler_model.dart' ('lib/detaylar/tum_sohbetler/tum_sohbetler_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
         if (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretilenAlanlar.contains(valueOrDefault(
             ^^^^^^
  lib/detaylar/tum_sohbetler/tum_sohbetler_model.dart:74:13: Error: The method 'setState' isn't defined for the class 'TumSohbetlerModel'.
* 'TumSohbetlerModel' is from 'package:kursat/detaylar/tum_sohbetler/tum_sohbetler_model.dart' ('lib/detaylar/tum_sohbetler/tum_sohbetler_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/detaylar/tum_sohbetler/tum_sohbetler_model.dart:75:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'TumSohbetlerModel'.
* 'TumSohbetlerModel' is from 'package:kursat/detaylar/tum_sohbetler/tum_sohbetler_model.dart' ('lib/detaylar/tum_sohbetler/tum_sohbetler_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToOgretilenAlanlar('Canlı Sohbet');
             ^^^^^^
  lib/detaylar/tum_sohbetler/tum_sohbetler_model.dart:83:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'TumSohbetlerModel'.
* 'TumSohbetlerModel' is from 'package:kursat/detaylar/tum_sohbetler/tum_sohbetler_model.dart' ('lib/detaylar/tum_sohbetler/tum_sohbetler_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
         if (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretilenAlanlar.contains(valueOrDefault(
             ^^^^^^
  lib/detaylar/tum_sohbetler/tum_sohbetler_model.dart:88:13: Error: The method 'setState' isn't defined for the class 'TumSohbetlerModel'.
* 'TumSohbetlerModel' is from 'package:kursat/detaylar/tum_sohbetler/tum_sohbetler_model.dart' ('lib/detaylar/tum_sohbetler/tum_sohbetler_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/detaylar/tum_sohbetler/tum_sohbetler_model.dart:89:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'TumSohbetlerModel'.
* 'TumSohbetlerModel' is from 'package:kursat/detaylar/tum_sohbetler/tum_sohbetler_model.dart' ('lib/detaylar/tum_sohbetler/tum_sohbetler_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToOgretilenAlanlar('Canlı Sohbet');
             ^^^^^^
  lib/detaylar/tum_sohbetler/tum_sohbetler_model.dart:91:13: Error: A value must be explicitly returned from a non-void function.
           return;
           ^
  lib/detaylar/tum_sohbetler/tum_sohbetler_model.dart:93:13: Error: A value must be explicitly returned from a non-void function.
           return;
           ^
  lib/walkthroughs/benim_profil.dart:31:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/benim_profil.dart:34:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/walkthroughs/benim_profil.dart:53:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/benim_profil.dart:56:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/walkthroughs/benim_profil.dart:75:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/benim_profil.dart:78:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/walkthroughs/benim_profil.dart:98:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/benim_profil.dart:101:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/walkthroughs/benim_profil.dart:120:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/benim_profil.dart:123:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/walkthroughs/benim_profil.dart:142:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/benim_profil.dart:145:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/walkthroughs/benim_profil.dart:164:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/benim_profil.dart:167:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/walkthroughs/profil_baskasi.dart:26:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/profil_baskasi.dart:29:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/walkthroughs/profil_baskasi.dart:48:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/profil_baskasi.dart:51:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/profil/profil_model.dart:172:18: Error: 'createWalkthroughTargets' is imported from both 'package:kursat/walkthroughs/benim_profil.dart' and 'package:kursat/walkthroughs/profil_baskasi.dart'.
       targets: createWalkthroughTargets(context),
                ^^^^^^^^^^^^^^^^^^^^^^^^
  lib/profil/profil_model.dart:175:16: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'ProfilModel'.
* 'ProfilModel' is from 'package:kursat/profil/profil_model.dart' ('lib/profil/profil_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretilenAlanlar.contains(valueOrDefault(
              ^^^^^^
  lib/profil/profil_model.dart:180:13: Error: The method 'setState' isn't defined for the class 'ProfilModel'.
* 'ProfilModel' is from 'package:kursat/profil/profil_model.dart' ('lib/profil/profil_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/profil/profil_model.dart:181:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'ProfilModel'.
* 'ProfilModel' is from 'package:kursat/profil/profil_model.dart' ('lib/profil/profil_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToOgretilenAlanlar('Benim Profil');
             ^^^^^^
  lib/profil/profil_model.dart:186:18: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'ProfilModel'.
* 'ProfilModel' is from 'package:kursat/profil/profil_model.dart' ('lib/profil/profil_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
               (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretilenAlanlar.contains(valueOrDefault(
                ^^^^^^
  lib/profil/profil_model.dart:191:15: Error: The method 'setState' isn't defined for the class 'ProfilModel'.
* 'ProfilModel' is from 'package:kursat/profil/profil_model.dart' ('lib/profil/profil_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
             setState(() {
             ^^^^^^^^
  lib/profil/profil_model.dart:192:17: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'ProfilModel'.
* 'ProfilModel' is from 'package:kursat/profil/profil_model.dart' ('lib/profil/profil_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
               \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToOgretilenAlanlar('Profil Başkası');
               ^^^^^^
  lib/profil/profil_model.dart:207:18: Error: 'createWalkthroughTargets' is imported from both 'package:kursat/walkthroughs/benim_profil.dart' and 'package:kursat/walkthroughs/profil_baskasi.dart'.
       targets: createWalkthroughTargets(context),
                ^^^^^^^^^^^^^^^^^^^^^^^^
  lib/profil/profil_model.dart:210:16: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'ProfilModel'.
* 'ProfilModel' is from 'package:kursat/profil/profil_model.dart' ('lib/profil/profil_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretilenAlanlar.contains(valueOrDefault(
              ^^^^^^
  lib/profil/profil_model.dart:215:13: Error: The method 'setState' isn't defined for the class 'ProfilModel'.
* 'ProfilModel' is from 'package:kursat/profil/profil_model.dart' ('lib/profil/profil_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
           setState(() {
           ^^^^^^^^
  lib/profil/profil_model.dart:216:15: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'ProfilModel'.
* 'ProfilModel' is from 'package:kursat/profil/profil_model.dart' ('lib/profil/profil_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToOgretilenAlanlar('Benim Profil');
             ^^^^^^
  lib/profil/profil_model.dart:221:18: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'ProfilModel'.
* 'ProfilModel' is from 'package:kursat/profil/profil_model.dart' ('lib/profil/profil_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
               (\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretilenAlanlar.contains(valueOrDefault(
                ^^^^^^
  lib/profil/profil_model.dart:226:15: Error: The method 'setState' isn't defined for the class 'ProfilModel'.
* 'ProfilModel' is from 'package:kursat/profil/profil_model.dart' ('lib/profil/profil_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
             setState(() {
             ^^^^^^^^
  lib/profil/profil_model.dart:227:17: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'ProfilModel'.
* 'ProfilModel' is from 'package:kursat/profil/profil_model.dart' ('lib/profil/profil_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
               \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.addToOgretilenAlanlar('Profil Başkası');
               ^^^^^^
  lib/walkthroughs/tanitim_369.dart:27:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/tanitim_369.dart:30:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/walkthroughs/tanitim_369.dart:49:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/tanitim_369.dart:52:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/walkthroughs/tanitim_369.dart:71:23: Error: Undefined name 'FFLocalizations'.
             baslik: FFLocalizations.of(context).getText(
                     ^^^^^^^^^^^^^^^
  lib/walkthroughs/tanitim_369.dart:74:25: Error: Undefined name 'FFLocalizations'.
             aciklama: FFLocalizations.of(context).getText(
                       ^^^^^^^^^^^^^^^
  lib/k369/k369_model.dart:230:11: Error: The method 'setState' isn't defined for the class 'K369Model'.
* 'K369Model' is from 'package:kursat/k369/k369_model.dart' ('lib/k369/k369_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
         setState(() {
         ^^^^^^^^
  lib/k369/k369_model.dart:231:13: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'K369Model'.
* 'K369Model' is from 'package:kursat/k369/k369_model.dart' ('lib/k369/k369_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
           \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretildiMi = true;
           ^^^^^^
  lib/k369/k369_model.dart:235:11: Error: The method 'setState' isn't defined for the class 'K369Model'.
* 'K369Model' is from 'package:kursat/k369/k369_model.dart' ('lib/k369/k369_model.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'setState'.
         setState(() {
         ^^^^^^^^
  lib/k369/k369_model.dart:236:13: Error: The getter '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model' isn't defined for the class 'K369Model'.
* 'K369Model' is from 'package:kursat/k369/k369_model.dart' ('lib/k369/k369_model.dart').
  Try correcting the name to the name of an existing getter, or defining a getter or field named '\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model'.
           \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_model.ogretildiMi = true;
           ^^^^^^
  Waiting for connection from debug service on Web Server... 67.7s
  Failed to compile application.

### Environment

```markdown
- FlutterFlow version: V4.1 - Flutter 3.19.1
- Platform: Web/ iOS/ Android
- Browser name and version: Google Chrome/ Opera/ Microsoft Edge (Güncel Son Sürüm)
- Operating system and version affected:
 
Project URL: https://app.flutterflow.io/project/zafer-rqs8we?tab=widgetTree&page=AnaSayfa
```

**Comment by LuisChavezz** [comment]
Same problem.
![Captura de pantalla 2024-03-11 095451](https://github.com/FlutterFlow/flutterflow-issues/assets/54516518/d2e7e23a-d2d0-40ec-ad72-541c66f98c45)

**Comment by hariprasadms** [comment]
Hey, it seems like your downloaded project has an issue as well. This appears to be caused by a layout design problem. Please check if there are any issues with the design layout.

<img width="1511" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/b60dba88-101b-417d-8c72-cd7e28ac9b6f">

**Comment by DevKursat** [comment]
The design error was also caused by FlutterFlow, but I solved it. (Please let Walktroughs work without errors now.)

The reason for the design error: When I add a conditional after adding a confirm dialogue to other fields in FlutterFlow Action, except for the "When the page loads" section, an empty conditional is assigned and the actions to be taken based on the answer are not added.

**Comment by DevKursat** [comment]
@hariprasadms @LuisChavezz @asmengistu @organicnz 

I don't want to offend you, I have great respect for your efforts, but I wonder when this error will be resolved as soon as possible? My anxiety has been so high for days, I need to post an update.

I will do my best to answer all your questions about the error. Even if everything is OK and these import errors are not received, the action that will be shown when Walktroughs finishes without being triggered is shown.

**Comment by DevKursat** [comment]
A NEW UPDATE HAS BEEN AVAILABLE BUT THIS ERROR HAS NOT BEEN FIXED. PLEASE PROVIDE SUPPORT, TEAM!

@hariprasadms @LuisChavezz @asmengistu @organicnz

**Comment by agreaves** [comment]
Hi @DevKursat, this issue should now be fixed as of a few hours ago. Please let me know if you continue to experience this issue.

**Comment by DevKursat** [comment]
I waited for more than a week and when it was not resolved, I deleted walktroughs. I'll go back from Project History and check.
@agreaves

**Comment by agreaves** [comment]
Ok thank you! Apologies again for the bug and any inconvenience we caused.

**Comment by DevKursat** [comment]
Project URL: https://app.flutterflow.io/project/share-feature-j5ye27?tab=widgetTree&page=HomePage
Error still exists, please try compiling the existing code. @agreaves

**Comment by sbis04** [comment]
@DevKursat Currently, it's not possible to use two different walkthroughs for a single page. That should show up as project errors:

![screenshot](https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/72b9249f-ed7b-481f-891d-8abd46fffd74)

I think when you last tested probably that part wasn't fully deployed, for which the errors might not be showing at that time and resulting in the build failure. Now, those errors should show up. Hope this addresses the issue.
