### ISSUE TITLE
Auto fill of email and password does not work with iOS

### ISSUE THREAD

**Issue by phils-hub** [FlutterFlow/flutterflow-issues#2707]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

iOS detects that it can autofill, but after selecting e.g. a known email address or a known password, the value is not filled into the input field. Basically nothing happens. It also does not ask whether the credentials should be stored.

### Expected Behavior

Should insert the email or password on user selection, should offer to store credentials for later re-use.

### Steps to Reproduce

1. Use the standard auth flow template's login page.
2. Try to login

Or just create an input field of type email or password with auto fill enabled and observe on iOS.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez8rluJNJpbxJ7c+AY8JWqwMwHVgjbJ0vpe5+dwsjCeKqEIkLPMmkSEhBcuqHewt2DmD/njkdpdrMhYbhEvk3CwSZRqJizKVfUxDvfHK5b5StO5CKWGpPM/xgC0C90Kan3RZ5BNBiLlIG12CILuqQb3qCf9qOYwx5e6fDbOY=

### Context

It basically makes login tedious, which is a terrible user experience. I am surprised that FlutterFlow has such issues, even though it has matured over the past year.

### Visual documentation

Easy to replicate

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released April 11, 2024
- Platform: MacOS 15 Desktop App as well as Chrome
- Browser name and version:
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @phils-hub, thanks for you report. The autocomplete and hint options are on the property panel, under the "Additional Properties" section. <br><br>Please let me know if your app behaves as expected after enabling those options.

**Comment by phils-hub** [comment]
@paulperez-dev apologies for the late reply and thanks for the quick response from your side. Those properties were already set appropriately. Basically iOS is not recognising the autofill property and hint configuration. It also does not ask whether the username and password should be saved (upon form submission).

Observations:
1. On create user account
1.1 Email field -> ✅  iOS suggests email addresses, 🔴  but no "hide my email" suggestion
1.2 Password ->  ✅  iOS suggests opening password manager,  🔴 but does not suggest to generate a password
1.3 On submit -> 🔴 iOS does not suggest storing the credentials
2. On log in 
2.1 🔴 No suggest population of credentials from iOS



* Flow: Create user
   * email field autofill suggestions show as email
   * password field autofill suggests openiing

**Comment by paulperez-dev** [comment]
@phils-hub If you want the ability to hide your email while registering, you need to add the option to sign with Apple. The other behaviors you mentioned are more related to web apps than to mobile apps, I mean, the browser is who suggests passwords and prompts to enter stored credentials.

**Comment by phils-hub** [comment]
Hi again @paulperez-dev, not to my knowledge. iOS and Android have active password managers that propose password generation and the storing and populating of passwords for mobile apps. So this is not a web app feature only. 

FlutterFlow Apps not only do not enable iOS to suggest/generate a password, they also do not ask whether the credentials should be automatically filled. Please see the description here - https://support.apple.com/en-gb/guide/iphone/iphf9219d8c9/ios 

If FlutterFlow does not support this then it makes any login and sign up process very tedious. WDYT?

**Comment by phils-hub** [comment]
@paulperez-dev and FlutterFlow team do you have any feedback on this and any recommendations on how to deal with it?

**Comment by paulperez-dev** [comment]
Hi @phils-hub, I will be looking into this. This may raise a feature request. I will keep you posted here.

**Comment by phils-hub** [comment]
@paulperez-dev what would the scope of the feature be? Let me know if I can support.

**Comment by rzambroni** [comment]
this might be related to a known bug on the flutter side that still haven't been fixed.<br>[https://github.com/flutter/flutter/issues/84444](https://github.com/flutter/flutter/issues/84444)

**Comment by smplfy** [comment]
Any updates on this issue? The login experience on iOS really does feel broken.

**Comment by d002054** [comment]
We have the same challenge. It would be great to get this fixed.

**Comment by paulperez-dev** [comment]
Hi everyone! Flutter needs to fix this first, there's not too much we can do in this case.

**Comment by smplfy** [comment]
This is still a major problem for my users. First experience is broken login. @paulperez-dev This does not appear to be the same issue as reported in the flutter issue above. That is related to keyboard type. Autofill does not work in any circumstance where face id is used. It seems the field loses focus and doesn't complete.

**Comment by srh98** [comment]
Hi there any updates on this please? Also an issue in our app

**Comment by smplfy** [comment]
I just received a negative review on the App Store because password autofills do not work in iOS. Can we please get someone to prioritize this issue?

**Comment by d002054** [comment]
I cannot agree more! Thanks for raising this topic again.Am 27.09.2024 um 14:13 schrieb Daniel Busse ***@***.***>:﻿
I just received a negative review on the App Store because password autofills do not work in iOS. Can we please get someone to prioritize this issue?

**Comment by smplfy** [comment]
Responding to keep this issue active. Additional context in the video (password: flutterflow). 

When I select a pre-populated password suggestion, you’ll see that it appears successful but does not fill out the textfield. However, if I go all the way into my password manager and select from that list it works. As I understand it, using Universal Links and Autofill Credential Provider, it recognizes my app based on the domain information so that I don’t have to search for the credentials in my password manager.

https://www.dropbox.com/scl/fi/25vospbwru95rt7o79flq/ScreenRecording_10-02-2024-12-29-47_1-1.MP4?rlkey=xn5dnjbzg346jx1ztygb4cnk5&st=2ucb81eo&dl=0

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by ksrath** [comment]
So this issue is not being fixed by Flutterflow it seems?

**Comment by neo-etremblay** [comment]
Anyone found a way to make the autofill work ?

**Comment by EGabriel29** [comment]
I'm having the same issue; almost a year has passed since this problem was reported, and it still isn't fixed. How is that possible?

**Comment by smplfy** [comment]
Issue still persists. This isn't a flutter error, it's the lack of the AutoFillGroup widget in Flutterflow. I hope that login / password autofill improves in the future, but I haven't seen much action from the Flutterflow team. You would think this was a priority.

@rzambroni  https://api.flutter.dev/flutter/widgets/AutofillGroup-class.html

**Comment by muicci** [comment]
Its June 2025, any updates? @rzambroni

**Comment by KaRaOkE18** [comment]
Hello,

 I am facing the same issue and it is a serious userflow distraction. Anyone found a solution? Any fix from flutterflow?
