### ISSUE TITLE
"Backend Query" > "Query Collection" > "Filter" with the "in" "Relationship" has undesired behavior when checking against empty list

### ISSUE THREAD

**Issue by RobertStuursma** [FlutterFlow/flutterflow-issues#2780]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have setup a ListView with a "Query Collection" as a "Backend query". I've added a filter to "Query Collection" to only return documents where "users" which are in the "list" are returned.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c7407b00-c137-41da-b00c-0f1ba1718418/ee99acc8-fd6f-4de4-9eab-c81edc77c5b7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNzQwN2IwMC1jMTM3LTQxZGEtYjAwYy0wZjFiYTE3MTg0MTgvZWU5OWFjYzgtZmQ2Zi00ZGU0LTllYWItYzgxZWRjNzdjNWI3IiwiaWF0IjoxNzEzNzI0OTE3LCJleHAiOjMzMjg0Mjg0OTE3fQ.m_5YApKY14WfmnP24e2xiaT0JkpkogEIsCW_PEAqwj0)

When the "list" contains at least 1 value, only those users that match the value(s) are returned (the desired behavior).
When the "list" is empty however, all user documents are returned from the collection. This behavior seems not to be influenced by toggling the option "Filter on Null values" (neither do I know if this is exactly what this option is meant for).

### Expected Behavior

What I would expect is that when you filter with "in" and the "list" your filtering against is empty, that no documents would be returned by "Query collection". Simple because if a list is empty, it will not contain the chosen "Collection field" of a document.

### Steps to Reproduce

Let's say we have a collection of fruit (fruitCode , fruitName ) in Firebase

The collection has the following documents:

{"abc", "apple"},
{"def", "banana"},
{"ghi", "pear"}

1. Create a "Listview" and Setup the backend query: "Query Collection"
2. For the "Collection" set "fruit"
3. For the "Query Type" set "List of Documents"
4. For "Filter 1" set "Collection Field Name" to "fruitCode"
5. For "Filter 1" set "Relation" to "in"
6. For "Filter 1" set "Value" to a list of fruitCode Strings that contains no items (it is empty)

Now all fruit documents should be returned (meanwhile the desired behavior should be that no fruit documents should be returned)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kicnf3It2rt9f1ar2ccFB/TssKVg/a7gelsIbEA40Iu6tG7YAW/SkQE9WZ7yhdH02fWaJrGEy/vDWhczIN+w6HxOBbqpdyLtUETrvVj2jaa6WBquKRXN9FtpKCECe3MCrhxBRANV0W0Ya6jqmNeSWfDbBJZz6DHozRsr/Op7No3PuQ0SLb3kNh1JWeC/v

### Context

I'm building a dating app. If the list of profiles that a user has liked is empty (in other words, he has not liked anyone yet), I don't want all profiles that are in the database to be returned.

I have created a workaround for now and have added a conditional to only show the ListView if the number of items in the list I'm checking against != 0. This solves the problem for now.

### Visual documentation

This is a private project.

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.34+
- Platform: -
- Browser name and version: -
- Operating system and version affected: -
```

**Comment by paulperez-dev** [comment]
Hi @RobertStuursma, thanks for your report! I was able to reproduce the issue. I will sent this to the ENG team so they can work on this.

**Comment by paulperez-dev** [comment]
Hi @RobertStuursma, can you please verify if the issue still happening after toggling "Filter on Null Values" in the query?

**Comment by takashiff** [comment]
Hi @RobertStuursma, thanks for the bug report! I apologize that you've encountered this issue and have decided to migrate to Supabase. As @paulperez-dev has stated earlier, the "Filter on Null Values" toggle should resolve this issue. I am going to go ahead and close this ticket, since this bug is no longer reproducible/verifiable. Thank you for your patience!

**Comment by singletonerik** [comment]
I have the same issue. Can you re-open this bug? It still exists.

I can describe how to reproduce, if that's needed. 

The basic idea is that the collection query has a filter where field is `in` a state variable which is an empty list.

When you render that result, it returns the entire collection. This happens even when Filter on null values is selected. I can provide more detail if that's needed.
