### ISSUE TITLE
Walkthrough translation error

### ISSUE THREAD

**Issue by damianfraire** [FlutterFlow/flutterflow-issues#2782]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently walkthroughs are not allowing me to add a translation for the text passed to the component to display the walkthrough message. The text also does not show in the settings -> languages page.

Additionally, there's a bug in the "Allow Translation" switch button, not "switching" status when clicked (although status actually changes).

### Expected Behavior

It should allow translation for the text passed to components from the walkthrough.

### Steps to Reproduce

1. Create a new page.
2. Create a new component that receives 2 strings params, and add 2 text widgets to the component, linking each to the parameters.
3. Create a walkthrough for the page.
4. Select the component and type text in the parameters.
5. Click on the "Allow translation" switch button. (It does not show the switch action, but the switched status gets recorded).
6. Click "Close"
7. Open again the parameter page and now the world icon for translations should be displayed, along side with the "Switch" button displaying the correct status
8. Click on the world icon, error comes up "Error encountered finding translations"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjc+A5ZVNxd8B15CMbccxgj0vJnp7TLJEpu0bWUkbGO/4PIYcOvfCbVtoXfazaHxYOk7+/U0EpKHVvvzxO8cDBwyqRqZj+c9UbhPPbEigV6qDDc2/OXJDI8ZXIGqD37SZrBV4HONpWE5n1GCMHeiyaz+Cf9qOYwx5e6fDbOY=

### Context

Note: Bug report code is not really pointing to the issue as it's not related to a widget.

This issue is affecting ability to display personalized walkthrough to end users based on their language preferences.

### Visual documentation

![Screenshot 2024-04-21 at 6 36 09 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/70819362/48b2d4d1-7fee-4ea5-9163-7ea5c35aee48)

### Environment

```markdown
- FlutterFlow version: v4.1.40
- Platform: macOS, Windows and web version of the flutterflow app.
- Browser name and version: Google Chrome
- Operating system and version affected: MacOS Sonoma
```

**Comment by Nic61** [comment]
I had to create a component for every single walkthrough step as a workaround

**Comment by rzambroni** [comment]
Hey @Nic61, i was able to replicate the issue you are describing, will send it to the team so they can take a look. We will update the status here once it is fixed.

Thanks for the report!

**Comment by joaocordeiro-dotted** [comment]
any updates on this? it's making the feature unusable :(

**Comment by JhefersonBR** [comment]
Hello everyone, I am also having this problem. Additionally, the first step after building the app never focuses on the target widget. The first step to be executed is always focusing incorrectly, causing confusion for the user who views the tutorial. When you change which step will be the first, it also becomes unfocused. In other words, it only happens with the first step, making it unfeasible to use this feature.

**Comment by cragroc** [comment]
I have the issue where the walkthrough focus does not align to the center of the widget it's supposed to also like JhefersonBR said: "The first step to be executed is always focusing incorrectly"
I opened a support case and they pointed me to this bug to watch, hopefully it's being used to track this issue as well.

**Comment by zifanjiang** [comment]
The bug was fixed in earlier versions and appeared again in the latest version (FlutterFlow v5.2.1 released February 14, 2025). Any plan to fix this?

**Comment by williamradic** [comment]
FF costs 86,10 USD monthly (at least in my country) and a bug like this is still present... What are they doing there? I don't want to create numerous separate widgets for this to work, I want it to work the way it is supposed to.

**Comment by EtienneTLM** [comment]
I use version 6.4.21 of FlutterFlow and the issue is still present. Very annoying.
What's the roadmap to fixing this FF team?

**Comment by totroi** [comment]
I am publicating my app with an English walkthrough only. If we could make more than one walkthrough for each page, we could use conditionals to have "translations". But well, what can we do. Best wishes for the FF dev team!
