### ISSUE TITLE
Switch Widget Fails to Apply Initial Value Correctly

### ISSUE THREAD

**Issue by deepanchal** [FlutterFlow/flutterflow-issues#2851]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When an initial value is provided to `Switch` widget, it is setting initial value to what the value was in flutterflow before setting an initial value var.

### Expected Behavior

When an initial value is provided to `Switch` widget, it should set initial value correctly.

### Steps to Reproduce

Please note: I am providing code from my existing project and I was able to replicate it by creating a simple flutterflow page with a `Switch`. The issue is in flutterflow code generation. Please see images below.

1. Create a new page in flutterflow (e.g. `BrokenSwitchBug`)
2. Add a new variable `initialSwitchValue` to Local Page State Variables with initial value of `true`
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46167867/40b81824-0de0-4ae9-8a13-5343ff4927db)

3. Add a `Switch` under `Column` and set the initial value to `initialStateValue` page state variable
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46167867/47261c2a-2f8d-40a9-8a7b-3a4d966f7450)

5. Add an action from any main page to navigate to this page 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46167867/4034cbde-b175-499d-9a77-fdfc14409e87)

6. Run the app and navigate to `BrokenSwitchBug` page.
7. After navigating to the page, you should see that the switch is toggled on as it should be from `initialSwitchValue` var.

The switch value should be true, but it's false. This `true/false` value is coming from before we set a variable to set initial switch value 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46167867/1c4b0ace-3d27-4fea-89c4-372f8791dd93)
In this image, if you were to set "Switch Initial Value" to true, and then set it to use `initialSwitchValue` variable, then it will default to true. The flutterflow code generation used to be `bool? switchValue;` which would allow it to use value from `initialSwitchValue` var bc of this line `_model.switchValue ??= _model.initialSwitchValue,`, however, it no longer sets variable as null (`bool switchValue = false;`).

`broken_switch_model.dart`

```dart
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/flutter_flow/flutter_flow_widgets.dart';
import 'broken_switch_bug_widget.dart' show BrokenSwitchBugWidget;
import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';

class BrokenSwitchBugModel extends FlutterFlowModel<BrokenSwitchBugWidget> {
  ///  Local state fields for this page.

  bool initialSwitchValue = true;

  ///  State fields for stateful widgets in this page.

  final unfocusNode = FocusNode();
  // State field(s) for Switch widget.
  bool switchValue = false;

  @override
  void initState(BuildContext context) {}

  @override
  void dispose() {
    unfocusNode.dispose();
  }
}
```

`broken_switch_widget.dart`

```dart
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/flutter_flow/flutter_flow_widgets.dart';
import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import 'broken_switch_bug_model.dart';
export 'broken_switch_bug_model.dart';

class BrokenSwitchBugWidget extends StatefulWidget {
  const BrokenSwitchBugWidget({super.key});

  @override
  State<BrokenSwitchBugWidget> createState() => _BrokenSwitchBugWidgetState();
}

class _BrokenSwitchBugWidgetState extends State<BrokenSwitchBugWidget> {
  late BrokenSwitchBugModel _model;

  final scaffoldKey = GlobalKey<ScaffoldState>();

  @override
  void initState() {
    super.initState();
    _model = createModel(context, () => BrokenSwitchBugModel());

    logFirebaseEvent('screen_view',
        parameters: {'screen_name': 'BrokenSwitchBug'});
    WidgetsBinding.instance.addPostFrameCallback((_) => setState(() {}));
  }

  @override
  void dispose() {
    _model.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => _model.unfocusNode.canRequestFocus
          ? FocusScope.of(context).requestFocus(_model.unfocusNode)
          : FocusScope.of(context).unfocus(),
      child: Scaffold(
        key: scaffoldKey,
        backgroundColor: FlutterFlowTheme.of(context).primaryBackground,
        appBar: AppBar(
          backgroundColor: FlutterFlowTheme.of(context).primary,
          automaticallyImplyLeading: false,
          title: Text(
            'Broken Switch Bug',
            style: FlutterFlowTheme.of(context).headlineMedium.override(
                  fontFamily: FlutterFlowTheme.of(context).headlineMediumFamily,
                  color: Colors.white,
                  fontSize: 22.0,
                  letterSpacing: 0.0,
                  useGoogleFonts: GoogleFonts.asMap().containsKey(
                      FlutterFlowTheme.of(context).headlineMediumFamily),
                ),
          ),
          actions: [],
          centerTitle: false,
          elevation: 2.0,
        ),
        body: SafeArea(
          top: true,
          child: Align(
            alignment: AlignmentDirectional(0.0, 0.0),
            child: Column(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Switch.adaptive(
                  value: _model.switchValue ??= _model.initialSwitchValue,
                  onChanged: (newValue) async {
                    setState(() => _model.switchValue = newValue!);
                  },
                  activeColor: FlutterFlowTheme.of(context).primary,
                  activeTrackColor: FlutterFlowTheme.of(context).accent1,
                  inactiveTrackColor: FlutterFlowTheme.of(context).alternate,
                  inactiveThumbColor:
                      FlutterFlowTheme.of(context).secondaryText,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

This line in `broken_switch_model` was changed in flutterflow update from this morning.

before:
```dart
  // State field(s) for Switch widget.
  bool? switchValue;
```

after:
```dart
  // State field(s) for Switch widget.
  bool switchValue = false;
```

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kj8n18c5OoeFZ1s7pbcZWq2IXQ3ojTLJEtusbTUggfbL4EJk+d8ylXElpYMizaHNMemeZvHIfwvT5jdj2GMIqNRCaQao61qlUehPPbH2lVbqhC7jtPXRCJ/hbI2q51sGFvSZQHNd2W3Ak62eACujKYz6Cf9qOYwx5e6fDbOY=

### Context

All of the switches in my project using initial values are broken

### Visual documentation

I believe this bug was caused by a flutterflow update from this morning.

This diff shows that all switch values now have default value of `true/false` instead of null.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46167867/c4bd53f5-19df-4fcd-af6d-076278e2838c)

And in the widget code, this line has no effect because model is already setting `true/false` value
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46167867/ede758f7-1fb5-462b-9a9a-c73448597ebf)

### Environment

```markdown
- FlutterFlow version: 4.1.46+
- Platform: Android
- Browser name and version: Brave Browser 124.1.65.123
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @deepanchal thanks for your report. I can see a lot of detail that could help us fix really quick the bug, but I'm not seeing the steps to actually reproduce it and see the unexpected behaviour. Could you please give me some steps to reproduce this from a blank project so I can confirm the bug and send it to the technical team? Thanks!

**Comment by deepanchal** [comment]
Hii @ignalauret, here are the steps to reproduce the bug. Thanks!!

# Steps to reproduce
1. Create a new page in flutterflow (e.g. `BrokenSwitchBug`)
2. Add a new variable `initialSwitchValue` to Local Page State Variables with initial value of `true`
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46167867/40b81824-0de0-4ae9-8a13-5343ff4927db)

3. Add a `Switch` under `Column` and set the initial value to `initialStateValue` page state variable
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46167867/47261c2a-2f8d-40a9-8a7b-3a4d966f7450)

5. Add an action from any main page to navigate to this page 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46167867/4034cbde-b175-499d-9a77-fdfc14409e87)

6. Run the app and navigate to `BrokenSwitchBug` page.
7. After navigating to the page, you should see that the switch is toggled on as it should be from `initialSwitchValue` var.

The switch value should be true, but it's false. This `true/false` value is coming from before we set a variable to set initial switch value 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46167867/1c4b0ace-3d27-4fea-89c4-372f8791dd93)
In this image, if you were to set "Switch Initial Value" to true, and then set it to use `initialSwitchValue` variable, then it will default to true. The flutterflow code generation used to be `bool? switchValue;` which would allow it to use value from `initialSwitchValue` var bc of this line `_model.switchValue ??= _model.initialSwitchValue,`, however, it no longer sets variable as null (`bool switchValue = false;`).

**Comment by mark-fran** [comment]
I have the same issue. It looks like the Initial Value is not pulling the data from queries, but instead it is merely reflecting whether the initial value tickmark was ticked, and not based on the Initial Value query.

I tried using the Tickmark Widget and it correctly reflected the queried data. In the below screenshot, you can see that the Switch was set to True, while the Tick Box was set to False. 

![Screen Shot 2024-05-03 at 7 30 52 pm](https://github.com/FlutterFlow/flutterflow-issues/assets/108987006/51a71165-a355-45a8-9834-2f14546c4665)

**Comment by rzambroni** [comment]
Hi @deepanchal, thanks for the additional details, we replicated the issue you are describing and will send it to the team so they can take a look. We will update the status here when we have news.

Thanks for the report!

**Comment by pollux-choh** [comment]
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/108918384/8b6a1164-323d-46ed-a174-7e2616d03d30)
I have the same issue.

> Hi @deepanchal, thanks for the additional details, we replicated the issue you are describing and will send it to the team so they can take a look. We will update the status here when we have news.
> 
> Thanks for the report!

**Comment by tmgnr75** [comment]
Hey everyone,

I have the same issue and found the probable cause + workaround while they're working on a solution.

The cause seems to be the release of new widget [SwitchTile](https://docs.flutterflow.io/widgets-and-components/widgets/base-elements/switchlisttile) (the documentation was updated 3 days ago).

I tried to use a SwitchTile widget instead of a Switch and the values are correctly initialized.

Hope it helps a few fellow builders ✌️

**Comment by anoos1973** [comment]
I have the same issue

**Comment by anoos1973** [comment]
> I have the same issue. It looks like the Initial Value is not pulling the data from queries, but instead it is merely reflecting whether the initial value tickmark was ticked, and not based on the Initial Value query.
> 
> I tried using the Tickmark Widget and it correctly reflected the queried data. In the below screenshot, you can see that the Switch was set to True, while the Tick Box was set to False.
> 
> ![Screen Shot 2024-05-03 at 7 30 52 pm](https://private-user-images.githubusercontent.com/108987006/327713904-51a71165-a355-45a8-9834-2f14546c4665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4Mjc3MDUsIm5iZiI6MTcxNDgyNzQwNSwicGF0aCI6Ii8xMDg5ODcwMDYvMzI3NzEzOTA0LTUxYTcxMTY1LWEzNTUtNDVhOC05ODM0LTJmMTQ1NDZjNDY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxMjU2NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGRmMmMzYjQyOGFiZWEyYjI3ZDM2YzEzMWEzZGFkOWNlNzU0OWE5NWFjYTI5MTFmNGY4YmI4ZGNiMzQxYmZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TsEH0Tl9sl-yvmwA-SFacK0QoWHZErOb3CRD63guoUE)

EXACTLY

**Comment by d6p2b** [comment]
The issue is the use of the **??=** operator to set the switch value.  The model defaults switch values to true so using the null assignment operator will never do anything as the left hand side (model's switch value) is never null.

Here's a bit of Switch.adaptive code with the offending operator:

```
              Switch.adaptive(
                    value: _model.switchValue1 ??= _model.foobar == 1,
                    onChanged: (newValue) async {
                      setState(() => _model.switchValue1 = newValue!);
                    },
                    activeColor: FlutterFlowTheme.of(context).primary,
                    activeTrackColor: FlutterFlowTheme.of(context).accent1,
                    inactiveTrackColor: FlutterFlowTheme.of(context).alternate,
                    inactiveThumbColor:
                        FlutterFlowTheme.of(context).secondaryText,
                  ),
```

The fix would be to use a normal assignment operator not the if-null operator.

**Comment by maxi069** [comment]
Mismo error! Lo solucione usando el Widget SwitchTile dejando solo el titulo. De todas formas estimo no pasara mucho para que solucionen!

**Comment by htsnet** [comment]
Same issue. I realized that only the visual was wrong. If my variable is OFF, the switch shows ON, but if I save, the value saved continues OFF. 
If I change to OFF and return to ON, then save, the value saved turns ON (correct).

![switchIssue 2024 05 06](https://github.com/FlutterFlow/flutterflow-issues/assets/9755885/a24971db-e935-4557-9e7b-3e0489cd36b1)

In this image, I am passing TRUE for the first block and FALSE to the second. Visually, both are TRUE.

**Comment by request-tickets** [comment]
Not sure but I think a possible cause for this is when it's querying from a backend data

**Comment by htsnet** [comment]
No, in this case, I passed the values (1 and 2) by parameters. And the same field (1 and 2) is used to text and switch.

**Comment by mark-fran** [comment]
@request-tickets @htsnet This has already been flagged as a confirmed bug.

**Comment by mmearly** [comment]
Hi all! Sorry for the delay here -- this fix was actually finished on Friday, but we had some issues with deployment. It should now be out to everyone and you should get the expected initialization behavior for both Switches and SwitchTiles. Thanks for your patience!

**Comment by htsnet** [comment]
@mmearly Thank you!

**Comment by metalik** [comment]
just download the latest Flutterflow Window Desktop and the problem still existing

The generated code is still using the ??= operator

`                            Switch.adaptive(
                              value: _model.mySwitchValue ??=
                                  widget.user!.mySwitchValue,`

**Comment by Thesergiolg99** [comment]
I can confirm the issue is still there on .49 FF build

**Comment by mmearly** [comment]
Hey @metalik and @Thesergiolg99, thanks for the feedback, I will investigate. Are you both on Windows desktop?

Quick note that the presence of the `??=` operator doesn't necessarily indicate a problem -- it was the combination of this with the switch being non-nullable that resulted in the bug. The fixed version that it sounds like you don't have yet will still generate code with `??=`.

**Comment by d6p2b** [comment]
I still see the problem with .49 on macOS.  The generated model code is initializing the underlying bool to true and still using the ??= operator.

**Comment by mmearly** [comment]
@d6p2b The traditional behavior with code generation for switches in FF is that their underlying bool is nullable (this bug was caused by something causing this bool to become non-nullable). It begins as null and if there is an initial value associated with the switch, instead of setting the value here (this is not trivial because this value can depend on other variables only scoped in the widget, not the model), we use the `??=` operator in the widget to set the value of the switch because it lets us detect that the underlying bool is null, indicating the switch has not yet been initialized. This lets us easily tell when to overwrite the value in the bool (because it represents an uninitialized value) and when to keep it (because it does actually represent the state of the user's switch). Finally, in the widget, we are able to use the Switch's `onChanged` function to update the underlying boolean whenever the switch is toggled, and since a switch toggle can only be on or off, the boolean will not be null after this point.

The initial fix was just to get switch behavior back into this paradigm, but we've realized that this is a less-than-ideal way to be handling the initial values of switches, and so this section of code generation is being more drastically reworked. But the first priority is getting the current paradigm back to a working state.

**Comment by mmearly** [comment]
Reopening until redeploy

**Comment by metalik** [comment]
confirm that the issue is fixed, thanks

**Comment by Souffleur-de-Reves** [comment]
I still have this issue. With both switch widgets. I have tried two things to set the initial value :
- list contains item, and it did not work when the item was in the list
- I created a custom function that return "true" when the item is in the list. Same thing.

On the same page, I display values in the list in order to debug, and I can check that the items are indeed in the list.

**Comment by Garciconx** [comment]
I still have this issue 😞

**Comment by Sissadaniel** [comment]
Same issue here, the variable state changes but the switch always go to either on or off.

**Comment by lcundiff** [comment]
I set the switch based off page state and then triggered page rebuild with a different state, and the switch does not change. @mmearly is this a confirmed issue?

**Comment by nckswt** [comment]
Experiencing this same issue -- had tried updating the switch initial value multiple ways, and constantly getting `null` issues and page not loading. Had to swap to a checkbox and I can't use switches any more until this is _actually_ fixed 😢

**Comment by andreslopas** [comment]
Same issue here.

**Comment by andreslopas** [comment]
Update: It works when I set the variable using the component parameter, but not when I use the component’s state value.

**Comment by buildthick** [comment]
the issue persists...

**Comment by athryzorian** [comment]
~~Issue persists for quite a few of us. @mmearly , did this really get fixed ? Are we missing something ? I would really like to use switch instead of checkbox. @andreslopas , didn't quite get it when you said it works when you set the variable using the component parameter. I am reading a boolean value from FireStore document and simply trying to apply it to a switch to toggle it on and off and getting null reference exception invariably.~~

I retested my code and sounds like the issue is not with the switch. The switch is working fine. My bad I didn't RCA the issue correctly earlier. Issue is in some other place, not relevant to this thread.
