### ISSUE TITLE
Mux Broadcast won't load on Android Device

### ISSUE THREAD

**Issue by ozan-celebi** [FlutterFlow/flutterflow-issues#2853]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Mux Broadcast view wont load on a real android device.

The device is a Samsung SM-A115F and it is running Android 12.0

Below is a screenshot from the device where the Page only has the MuxBroadcast Widget

![Screenshot_20240503-195705](https://github.com/FlutterFlow/flutterflow-issues/assets/138249319/3a7551d3-6e9b-4bff-92cf-48dd0f8486db)

### Expected Behavior

The expected behaviour is for the streaming view to load so that the streamer can start the live stream

### Steps to Reproduce

1- Create a page
2- Only put the Mux Broadcast Element
3- Open on a real android device preferably with the system descriptions described above
4- Observe functionality

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeysmBz4dNpbxI17XxbvlGrwMzJDt+bJA3m+0bZxMgfZzkOph/e8nsbk1CXf2+SmlhHGebmlkGweDtudnIU8ddMkyCbNla/6huTD3jXXq8SqawEcyaQ3QkJ8BWGGqc1Kar2hNTLvRpLWBlw0+HeueQZBPaN5+/Zwh9f6PHaOI=

### Context

I am building a livestream commerce platform and livestream is the main feature. So it is mission critical.

### Visual documentation

![Screenshot_20240503-195705](https://github.com/FlutterFlow/flutterflow-issues/assets/138249319/99db0138-920c-44ff-b6ef-c73b8c605144)

### Environment

```markdown
- FlutterFlow version: v4.1.46
- Platform: Android Physical Device
- Browser name and version:
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [X] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ozan-celebi** [comment]
Any updates regarding this issue?

**Comment by ozan-celebi** [comment]
Hello, is there a potential solution to this problem?

**Comment by sbis04** [comment]
This should have been fixed in the latest Flutter upgrade, are you still facing it now?

**Comment by sbis04** [comment]
Closing this, since this issue was fixed in the last Flutter version upgrade of FlutterFlow.

**Comment by ozan-celebi** [comment]
I am still facing this. The Mux Broadcast Widget will not load on a Physical Android Device.

The widget tree of the page only has the Broadcast widget in it. The loading indicator keeps spinning and wont load.

**Comment by ozan-celebi** [comment]
Here is the entire debug panel screenshots when a button is pressed to navigate to a page that only has Mux Broadcast Widget.

<img width="790" alt="image" src="https://github.com/user-attachments/assets/d1e8f220-71ee-4e3d-9446-52f366ca3d1d">
<img width="788" alt="image" src="https://github.com/user-attachments/assets/a469801f-2334-4577-a84a-4e539022f439">
