### ISSUE TITLE
View reload each time I switched back to the app on MacOS

### ISSUE THREAD

**Issue by ustikya** [FlutterFlow/flutterflow-issues#2855]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

MacOS. Use the full-screen app, switch to the emulator to test the app, switch back to FlutterFlow, and see the loading animation. After this, the app "loses" the emulator status. It cannot see that the app is running.

### Expected Behavior

No loading screen or saved state of the emulator after switching back to the app.

### Steps to Reproduce

1. Go fullscreen
2. Launch the app in test mode on the emulator
3. Switch to the emulator to test the app
4. Switch back to FlutterFlow app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gocdJ1anTKsZQhQAkQzM8bYJMl9dTRUsgfZzvE7Mider+VFNvOcuzYAtUE1magXExpdrHvtr1EO4VCE2CUoNowbpAYRbJUTmhb8ybO7ueSGpfGtJUFXKG4J+Jvx55CMB1SEJnw1r/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

I am just trying to use the app and this issue becomes annoying.

### Visual documentation

<img width="1772" alt="Screenshot 2024-05-03 at 21 29 46" src="https://github.com/FlutterFlow/flutterflow-issues/assets/18728053/f857bf91-ec67-43d7-8dfb-5fbd5e47c524">

### Environment

```markdown
- FlutterFlow version: 4.1.46
- Platform: iOS
- Browser name and version: Chrome 124.0.6367.119 (Official Build) (arm64)
- Operating system and version affected: MacOS 14.4.1 (23E224)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @ustikya thanks for your report. We have already got a complain about this new reload on MacOs, so the technical team is already checking it. I will link your issue to the internal ticket so they keep you updated when it's fixed. <br>To avoid confusion, I'm closing this ticket as duplicate. Have a great day!

**Comment by ignalauret** [comment]
Reopening issue and marking the other one as duplicate, since this one is public and can help anybody else that is getting the same experience.

**Comment by leighajarett** [comment]
Thanks for this! The issue has been resolved and should be deployed to production soon

**Comment by aruana-dev** [comment]
@leighajarett has this been resolved? I still experience the very same bug having the newest version installed on macos somona on an M1-macbook air

**Comment by leighajarett** [comment]
Yes it has been resolved, can you confirm the version number on macoS?

**Comment by leighajarett** [comment]
Hmm, can you provide more details on what you experienced?

**Comment by aruana-dev** [comment]
I'm trying to capture the process via screen-recording and will attach it here asap .. in short: I'm using macos-spaces in between which I use to switch 'all the time' .. on switching from one to another 'space', flutterflow just reloads .. AND disconnects from any running local test run, which is annoying ..

pls wait for the screen recording

**Comment by leighajarett** [comment]
Thanks for sending!

**Comment by aruana-dev** [comment]
I couldn't capture it yet, but noticed that it most likely happens after the screen gets locked automatically due to inactivity and then re-logging in ..

**Comment by leighajarett** [comment]
Hmm interesting, I have tested this out on my computer and couldn't reproduce

**Comment by sbis04** [comment]
**Note:** the app will only reload if you are inactive for more than 10 minutes on the MacOS app. We do that just to make sure the data on the current project version is in sync with any other active sessions (for preventing any data loss).
