### ISSUE TITLE
Video and Youtube Player videos continue playing after navigating to another page

### ISSUE THREAD

**Issue by katherineqian** [FlutterFlow/flutterflow-issues#3]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.
Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

## Expected behavior

When a user plays a video and navigates to another page, the video from the first page should stop playing. 

## Current behavior

When a user plays a video and navigates to another page, the video keeps playing, and you can still hear the sound. This can happen with more than one video as well.

## To Reproduce

1. Create 2 new blank pages, and add a YouTubePlayer widget to Page 1.
2. Add a button to Page 1. Add a "Navigate to Page 2" Action to this button.
3. Click "Run" (or "Preview").
4. Press Play on the video on Page 1. 
5. Navigate to Page 2 by pressing the button. 
6. Observe that the video from Page 1 is still playing.

## Context

This makes building any video-focused application difficult because the end user must manually stop videos to avoid having lingering video sounds playing. Because the issue can happen with more than 1 video player, the number of layered video sounds can get very unpleasant.

## Screenshots

N/A

## Your environment

* Version of FlutterFlow used: N/A
* Platform (e.g. Web, MacOS Desktop): N/A
* Browser name and version: N/A
* Operating system and version (desktop or mobile): N/A

**Comment by katherineqian** [comment]
test

**Comment by bulgariamitko** [comment]
Just to clarify. If you press the back button in Android the video will stop, if you Navigate to a new screen the sound/video will continue playing.

**Comment by hariprasadms** [comment]
Hi @bulgariamitko - I think its been fixed isn't it. Can we close this issue?

**Comment by bulgariamitko** [comment]
@hariprasadms , last time I check it was not fixed, but I will check it again and let you know.

**Comment by hariprasadms** [comment]
Hi, I hope this issue is fixed in latest FF builds. We are closing this issue. Let us know if issue persists again we can re-open the issue and start investigating. Thanks

**Comment by aemelyanovff** [comment]
Fixed, finally!

**Comment by aaronmt93** [comment]
hi all, still some issues with this. I am autoplaying videos within a a tab bar. when i navigate to a different tab, the video keeps playing if the new tab doesnt have video. also, when i go back to the original tab, the video doesn't autoplay again and is paused.

**Comment by laughingbuddha24** [comment]
I am still experiencing this issue when I navigate away from the page via a bottom sheet link
