### ISSUE TITLE
Failed to compute merge conflicts

### ISSUE THREAD

**Issue by FCMHUB** [FlutterFlow/flutterflow-issues#3248]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We are receiving the error ‘Failed to compute merge conflicts’ every time we attempt to merge the main branch into the sales-flow branch.

### Expected Behavior

No errors.

### Steps to Reproduce

Branching menu
Branching options
Click Merge [main] into [sales-flow]

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40ss+D5bZ6xtd30bXUdsIyoGAQNlAla5BEs9xBaCsofePrOpkAf8/7UFtUOLDiYEFfMGCjmnsX/Mr3uePQG/E4IQiYfKJi+JZ2bjvLXkGmabLREa63b3BAHeFXf0yd0Im3oxVCKtR1SmwH1zqEfO7IdDDUO5D1OmwvPeaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/33237325/7958e60d-8d85-4268-bf95-e00f62939228)

### Environment

```markdown
- FlutterFlow version: 4.1.64
- Platform: -
- Browser name and version: - 
- Operating system and version affected: Win and Mac (Desktop versions)
```

**Comment by ignalauret** [comment]
Hey @FCMHUB thanks for your report. This could happen because sometimes after merging some branches you can get to a state were the merge conflicts to solve are really complex for the editor to show. To confirm this, you should go to your GitHub and check if the PR says "These conflicts are too complex to resolve in the web editor". <br>Sadly if this is the case, you will have to go to a code editor, clone the project, and resolve the conflicts there. <br>If you need any help with this, please feel free to contact our Customer Support team, they can help you with this. <br>I hope this was helpful, have a great day!

**Comment by FCMHUB** [comment]
Hi @ignalauret, thanks for the response. But correct me if I’m wrong. I’m not using the Custom Code flow:

https://docs.flutterflow.io/customizing-your-app/manage-custom-code-in-github

I have made all changes inside FlutterFlow.
I know I can always fix and merge the generated code if needed, but then those changes will never be reflected in the FlutterFlow branch.

In other words:

	•	I started a new branch inside FlutterFlow (FF).
	•	I’ve made several changes (inside FF) to this new branch.
	•	I want to merge those changes back to the main branch inside FF.
	•	If FF is not able to merge those changes back to the main branch and I have to resolve the conflicts in the generated code, the main branch will never have the updated code.

Did I get it right, or is there any way to resolve the conflicts using an external editor and have those changes persisted inside FF?

If this is not the case, we indeed have a critical bug, because I’m stuck on a branch without being able to merge back to the main branch inside FF.

Thanks in advance.

**Comment by FCMHUB** [comment]
@ignalauret 
We have another branch that we cannot merge. There is no error message, but it gets stuck in an infinite loading state.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/33237325/3d782c1b-0b8f-406d-b3fb-f039d1e9340d)

In other words, we have two features being developed in two different branches, and neither of them can be merged back into the FF main branch.

Please change the ticket status. This is definitely a (severe) bug.

**Comment by FCMHUB** [comment]
Even with these infinite loadings, we marked the option to accept the changes from Main because there were no changes on the new branch for these pages. We could finish the merge, but a lot of content was lost on the main branch, similar to this issue:

https://github.com/FlutterFlow/flutterflow-issues/issues/3177

@msusviela

**Comment by FCMHUB** [comment]
So, there are three critical problems:

1. Failed to compute merge conflicts (Merge [main] into [sales-flow]).
2. Infinite loading when resolving merge conflicts (Merge [Calendar1] into [main]).
3. If you ignore these infinite loadings and finish the merge, content is lost on the main branch (Merge [Calendar1] into [main]).

**Comment by Alezanello** [comment]
Hello!

I've been investigating this issue, and it appears to be more project-related rather than a bug. I created several blank projects with different additions in branches and merged \[Branch1\] into \[main\] and \[main\] into \[Branch1\] multiple times, but I couldn't replicate the problem.

We will continue to test these cases. If the issue happens again, I strongly recommend contacting support via the in-app chat or at support@flutterflow.io. They can take a closer look at your specific case and determine the cause.

Best regards,<br>Azanello

**Comment by gianverdum** [comment]
Hi everyone,

I wanted to contribute to this discussion because my issue (#3177) was cited here. From my experience, the problem is not project-related but rather a fundamental issue with Flutter Flow.

In our case, we've experienced significant problems with merging branches, resulting in lost content and infinite loading states. We had to manually redo weeks of work, leading to major setbacks for our startup.

The support response here suggests that the issue is within the project, but I strongly believe this is not the case. The consistent occurrence of these problems across different projects indicates that there might be an underlying issue with Flutter Flow itself.

Additionally, I want to point out that @Alezanello might not be able to reproduce the problem with a new project simply. To replicate the issue, they need to be on the version of Flutter Flow prior to the last major release, create multiple branches with distinct changes, and then migrate to the current version of Flutter Flow before attempting the merges. There are strong indications that the problem was caused by the Flutter Flow update.

Is there any concrete plan to address these recurring merge conflicts, or will similar issues continue to be marked as "project-specific" without a deeper investigation?

Best regards,
Giancarlo

**Comment by FCMHUB** [comment]
Thanks @gianverdum for your statement.

@Alezanello 

We completely disagree with the classification ‘this is not a bug,’ just because it was not reproduced in a blank project.
The project is available for further investigation. We are open to assisting with any debugging and deeper analysis.
Flutter Flow is an awesome tool, but the branching process is definitely corrupted, as noted in other GitHub issues.
Without the ability to use a trustworthy branching mechanism, larger teams will struggle to adopt Flutter Flow.

Ultimately, the ticket was closed, but the following issues are still present:

1. Failed to compute merge conflicts.
2. Infinite loading preventing the merge to be completed.
3. Loss of content after completing the merge. (We have many years of experience with GIT branching and know how a merge should work, so this is not ‘expected behavior.’)
4. Conflicts in pages or components that were not touched. Even components that are present in only one branch show as conflicts.
5. If you abort the merge, the code shows numerous errors as if the merge is still in progress. You have to close the project and open it again.

I emphasize that we are open to working with the development team and helping to investigate all these issues further.

The most critical part is that we don’t have any workaround besides redoing the work on the main branch. There is no way to perform the merge manually in text mode because Flutter Flow project files (meta files) are not exposed to customers.

**Comment by Alezanello** [comment]
Hello!

First of all, thank you for reaching out with your concerns. I take these cases very seriously and have tested everything from new blank projects to other projects created specifically for testing branches.

Please note that this tracker is specifically for bugs that are reproducible from blank projects. Issues that cannot be replicated from a blank project are typically considered project-specific, unless they occur across all projects.

We genuinely want to resolve this issue thoroughly. I recommend reaching out to our support team via the in-app chat or email. They can provide more targeted assistance, help determine the root cause of the issue, and collaborate with the development team to prevent this from happening in the future.

It's not that I want to close this thread without taking action. As I mentioned in my first comment, "We will continue to test these cases. If the issue happens again, I strongly recommend contacting support via the in-app chat or at support@flutterflow.io. They can take a closer look at your specific case and determine the cause."

Our goal is to make FlutterFlow a perfect product for everyone, and with your help, we can achieve that!

Best regards,<br>Azanello

**Comment by FCMHUB** [comment]
Thanks @Alezanello!

We have opened a ticket, I’ll keep this issue updated with the resolution.

**Comment by Alezanello** [comment]
Hello!

Just checking in, how is everything going? Has your issue been resolved with the support team?

**Comment by FCMHUB** [comment]
@Alezanello
We are still facing some problems, but the support has been helpful so far.

**Comment by Alezanello** [comment]
I'm glad to hear that!<br><br> did you and the support team found anything that could be replicated?

**Comment by FCMHUB** [comment]
Testing the latest FF version (4.1.70) to check if branching problems were fixed, but unfortunately, they were not.
There are still many problems such as:

- Grey screens.
- Infinite loading.
 - Stuck conflicts that prevent merges.
 - In the branch where we managed to finish the merge by ignoring the infinite loading, the results were incorrect, with wrong pages being merged despite being correctly selected during the conflicts step.

**Comment by leighajarett** [comment]
So sorry about that. We have already put out a fix for some of these issues - but we are continuining to investigate

**Comment by Alezanello** [comment]
Hello!! <br><br>Just passing by to check if the latest updates of FF fixed some of your issues!

**Comment by vinicius-felip** [comment]
I had the same problem when trying to resolve the conflict with Actions. 
When trying to resolve Actions conflict, the FF has a completely gray screen and this makes it impossible to complete the Merge, as I cannot resolve any conflicts.


![image](https://github.com/user-attachments/assets/4ca240da-e13a-4a6c-8488-c073e1b3ed6b)

**Comment by leighajarett** [comment]
Oh no, that's not good! Can you send over the bug report code?
