### ISSUE TITLE
Browser Test Mode not working

### ISSUE THREAD

**Issue by jaarend** [FlutterFlow/flutterflow-issues#3270]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to run the test mode on the web using the Brave browser on Windows I get the following errors in the browser console:

GET https://ff-debug-service-frontend-pro-ygxkweukma-uc.a.run.app/assets/packages/flutter_inappwebview_web/assets/web/web_support.js net::ERR_ABORTED 404 (Not Found)

main.dart.js:3950 Uncaught 
    at Object.v (https://app.flutterflow.io/main.dart.js:3950:19)
    at Object.c8_ (https://app.flutterflow.io/main.dart.js:6490:9)
    at cv0.lz (https://app.flutterflow.io/main.dart.js:180059:21)
    at cv0.dE (https://app.flutterflow.io/main.dart.js:180061:21)
    at Object.n0P (https://app.flutterflow.io/main.dart.js:82280:28)
    at hCe.$1 (https://app.flutterflow.io/main.dart.js:385187:16)
    at hKK.$1 (https://app.flutterflow.io/main.dart.js:183770:21)

### Expected Behavior

This error causes test mode to not work at all. I can't see anything on my screen, nothing loads like it should.

### Steps to Reproduce

I am simply running a test mode like we've done before. This error only started occurring when flutter was updated to 3.22.2 seems like. I am able to get a test run working on chrome using a local run. I don't get any other error other than the ones I listed before. I don't get any other error in the flutterflow builder so I'm not sure what other context to provide.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ozcrlw4Z1obgA+Kr2ccAxnSQRHH02bLgelcpBZywgfZzzBLN/fPfQPhNvOfXmdEFMMWCMp14e0tr9huLLUsBdBwqCGoRe+pBqdgn/XTqVVcyTF7q8Vn99EdhYI33HyqSFuxQnWddZWFICwE+IDeyXVj/cGZCyIWo4Sq/LZO4=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/40446017/43d9da80-99d1-4114-a3b1-cd8dba25f206)

### Environment

```markdown
- FlutterFlow version:  v4.1.63+
- Platform: Web
- Browser name and version: Brave Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Home 23H2
```

**Comment by msusviela** [comment]
Hi @jaarend - Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue.<br><br>If it's not replicable from blank, it's a project specific issue. Our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.<br><br>Thanks!

**Comment by Tecta-J** [comment]
I'm getting the same errors since last night. Unable to use test mode anymore.

main.dart.js:6490 Uncaught 
    at Object.v (https://app.flutterflow.io/main.dart.js:3950:19)
    at Object.c8_ (https://app.flutterflow.io/main.dart.js:6490:9)
    at cv0.lz (https://app.flutterflow.io/main.dart.js:180065:21)
    at cv0.dE (https://app.flutterflow.io/main.dart.js:180067:21)
    at Object.n0Q (https://app.flutterflow.io/main.dart.js:82280:28)
    at hCe.$1 (https://app.flutterflow.io/main.dart.js:385195:16)
    at hKK.$1 (https://app.flutterflow.io/main.dart.js:183776:21)

sometimes followed by or proceeded by these errors:

require.js:168 Uncaught 

require.js:168 Uncaught Error: Script error for "packages/.../backend/push_notifications/push_notifications_util.dart", needed by: web_entrypoint.dart
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168:17)
    at HTMLScriptElement.onScriptError (require.js:1738:36)

require.js:1959 
 GET https://ff-debug-service-frontend-pro-ygxkweukma-uc.a.run.app/wk9mOyr00savL…/backend/push_notifications/push_notifications_util.dart.js net::ERR_SSL_PROTOCOL_ERROR 200 (OK)

Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR

Was working fine earlier. Run mode works.

**Comment by abhibalani** [comment]
I am facing the same issue. Along with that, changes are not reflecting in test mode. This is really frustrating. I spend so much time in an issue which randomly occurred and randomly fixed. My changes have stopped reflecting in run mode as well.

Update: It started working for me few hours ago.

**Comment by AM0100101010** [comment]
I'm also facing the same issue, I've also tried publishing to web and the website crashed even though it builds successfully for iOS and android and both apps working fine 
![Image 29-06-2024 at 8 59 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/95685898/c421a190-778a-4b1e-aa19-75fea1d105ed)

**Comment by AM0100101010** [comment]
when I downloaded the code to vs, I found that web uses flutter_test and FileUpload that are not compatible when I tried to remove the flutter_test that uses that some web beta version and was not in use anyway the project failed to build @msusviela

**Comment by AM0100101010** [comment]
@msusviela 
Because file_picker >=8.0.1 depends on web ^0.5.1 and every version of flutter_test from sdk depends on web 0.1.4-beta, file_picker >=8.0.1 is  
  incompatible with flutter_test from sdk.
So, because campaign_tracker depends on both flutter_test from sdk and file_picker 8.0.3, version solving failed.

**Comment by dkubicahitachi** [comment]
I am facing the same issue. Tt doesn't matter whether I use debug mode or run mode. Please roll back to the last stable version :(

**Comment by dajana0** [comment]
I am facing the same issue. Tt doesn't matter whether I use debug mode or run mode. Please roll back to the last stable version :(

**Comment by msusviela** [comment]
Hi @dajana0. Could you please share more details? Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue.

**Comment by msusviela** [comment]
Hi @AM0100101010, could you please share the steps to reproduce from blank or a bug report code? We are still unable to reproduce the issue from our side.

**Comment by dajana0** [comment]
> Hi @dajana0. Could you please share more details? Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue.

This is the error that I see in the console:
```
main.dart.js:6490 Uncaught 
    at Object.v (https://app.flutterflow.io/main.dart.js:3950:19)
    at Object.c8_ (https://app.flutterflow.io/main.dart.js:6490:9)
    at cv0.lz (https://app.flutterflow.io/main.dart.js:180065:21)
    at cv0.dE (https://app.flutterflow.io/main.dart.js:180067:21)
    at Object.n0Q (https://app.flutterflow.io/main.dart.js:82280:28)
    at hCe.$1 (https://app.flutterflow.io/main.dart.js:385195:16)
    at hKK.$1 (https://app.flutterflow.io/main.dart.js:183776:21)
```
    It occurred in a few minutes above 1500 times
    
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/33000816/944766a2-4ecc-4927-bd93-dd6a6dafe06a)

The page is constantly refreshed or redirected to the home page and behaves like it is frozen.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/33000816/c3a5eb89-fe7c-4f3d-9742-cfe61dcb0421)


What else information would you like to know to reproduce the issue? You can also go ahead and access my project to look for more information.

**Comment by computerfreak84** [comment]
> Uncaught at Object.v (https://app.flutterflow.io/main.dart.js:3950:19)

I get a very similar error in my console. a few of the line numbers differ, but many are exactly the same, also starting with 3950:19

It started appearing 2-4 weeks ago and I've been spending the last few hours trying to figure out where it's coming from. In my case the app still works flawlessly in test mode, but I don't like bugs...

As far as I know so far, it started with either me putting in some custom code OR it started appearing after there was a new flutterflow version.

So far I've tried running some older version of my project, which doesn't have much custom code, and I still get the error. Also I'm pretty sure this exact older versions did not produce the error before, so it seems to be rooted in one of the recent flutterflow updates.

I'm not sure if I'm going to invest more time in finding the cause as long as my project seems to work.

**Comment by computerfreak84** [comment]
One more thing:

I just noticed that the same / similar thing even happens in a completely blank project when using test mode.

Also the first time I noticed was on June 19th.

![flutterflow_console_error](https://github.com/FlutterFlow/flutterflow-issues/assets/16098457/9169608e-e50c-42a8-a649-47da7b3639ee)

**Comment by msusviela** [comment]
Hi. A new version of FlutterFlow just came out minutes ago. Is this still an issue with the new version?

**Comment by computerfreak84** [comment]
> Hi. A new version of FlutterFlow just came out minutes ago. Is this still an issue with the new version?

Yes unfortunately.

Even the blank project still looks like my screenshot above. The same block of errors appears twice when loading or doing instant reload.

**Comment by msusviela** [comment]
Thanks. Now I could replicate this. Will send it to ENG so they can work on this as soon as possible.

**Comment by computerfreak84** [comment]
> Thanks. Now I could replicate this. Will send it to ENG so they can work on this as soon as possible.

in the latest version it is now uncaught at 3955:19 instead of 3950:19

**Comment by dajana0** [comment]
Still, many errors are thrown in version FlutterFlow v4.1.72+ released July 12, 2024 Flutter version is 3.22.2:
```
main.dart.js:3955 Uncaught 
    at Object.v (https://app.flutterflow.io/main.dart.js:3955:19)
    at Object.c9k (https://app.flutterflow.io/main.dart.js:6497:9)
    at cwv.lr (https://app.flutterflow.io/main.dart.js:181688:21)
    at cwv.dD (https://app.flutterflow.io/main.dart.js:181690:21)
    at Object.n8Y (https://app.flutterflow.io/main.dart.js:140161:21)
    at hGM.$1 (https://app.flutterflow.io/main.dart.js:388684:16)
    at hPS.$1 (https://app.flutterflow.io/main.dart.js:185441:21)
```

When we can expect the working version??

**Comment by dajana0** [comment]
I still have an error during tests. I have decided to deploy my application and have many errors - `[Violation] 'requestAnimationFrame' handler took <N>ms`.

You can see yourself - https://do-now.flutterflow.app/HomePage

**Comment by leighajarett** [comment]
Hi all, so sorry about this. Is this specific to Brave browser? Or are you seeing this on chrome as well?

**Comment by leighajarett** [comment]
Oh no, so sorry about this! We just deployed a fix - can you check and see if it's working now?

**Comment by dajana0** [comment]
@leighajarett still the same :( :
![image](https://github.com/user-attachments/assets/ddb96394-5a64-4100-9ecc-3aab37728005)
```
Uncaught 
    at Object.v (https://app.flutterflow.io/main.dart.js:3955:19)
    at Object.ca9 (https://app.flutterflow.io/main.dart.js:6497:9)
    at cxl.lx (https://app.flutterflow.io/main.dart.js:182804:21)
    at cxl.dF (https://app.flutterflow.io/main.dart.js:182806:21)
    at Object.ndU (https://app.flutterflow.io/main.dart.js:141216:21)
    at hJA.$1 (https://app.flutterflow.io/main.dart.js:390889:16)
    at hSD.$1 (https://app.flutterflow.io/main.dart.js:186560:21)
```

My version: FlutterFlow v4.1.76+ released July 24, 2024
Flutter version is 3.22.2

If you want you can access my test app which has the same problem - test-5t5bwg

**Comment by wenkaifan0720** [comment]
@dajana0. The errors you see are probably not critical (they are valid errors, for sure, and I can see many of them are due to missing asset images). But the reason why your home page is stuck is because you have a on component load action that nagivates to the home page in your component `logo2Large`. The would cause a infinite navigation and that is why you see so many `/homePage` routes in the debug panel.

**Comment by ahnsunnyyoung** [comment]
https://github.com/FlutterFlow/flutterflow-issues/issues/3470#issue-2427627270

**Comment by ahnsunnyyoung** [comment]
https://github.com/FlutterFlow/flutterflow-issues/issues/3470#issue-2427627270

I still have issue with running test mode. My other flutterflow project is running fine, but just this project is not working, and other coworker is struggling same issue with me. Seems like code problem somehow.

Emulator, local run, deployment on stores are all working fine. Also test mode debugging panel get all the values but ui is just not shown.

Please HELP...

**Comment by leighajarett** [comment]
Taking a look!

**Comment by leighajarett** [comment]
I am going to reopen your other issue @ahnsunnyyoung

**Comment by vereggen** [comment]
I'm also having the same issue. 
![TestMode](https://github.com/user-attachments/assets/a83d74ae-4c79-41d9-aeef-f31f13938d68)

**Comment by wenkaifan0720** [comment]
Hi @vereggen. Could you provide a bug report code (or open a new issue)?

**Comment by unofficialdxnny** [comment]
### 🛠️ **Quick Fix: Clear Cache and Cookies**

Hey everyone! This is a simple fix, and you can do it too! I'll guide you through the process using **Google Chrome**, but the steps are similar for other browsers. ✅

### 📖 **Step-by-Step Guide**

1. **Open Chrome Settings:**
   - Click the three-dot menu (⋮) in the top-right corner.
   - Select `Settings` from the dropdown.

2. **Search for "cache":**
   - Type `cache` in the search bar at the top.

3. **Access the "Clear Browsing Data" Menu:**
   - Click on `Delete browsing data`.

4. **Select Only the Necessary Options:**
   - Ensure **only** the following are selected:
     - ✅ `Cookies and other site data`
     - ✅ `Cached images and files`

5. **Clear the Data:**
   - Click the **`Delete data`** button.

### 📸 **Reference Images**

1. **Open Chrome Settings**

   ![Step 1](https://github.com/user-attachments/assets/2a008d5a-b1a8-4ba9-a126-87b3c20412db)

2. **Search "Cache"**

   ![Step 2](https://github.com/user-attachments/assets/d8bfe88f-17fb-4f67-9490-4c4b0397f186)

3. **Clear Data**

   ![Step 3](https://github.com/user-attachments/assets/fb2c1534-d88e-4362-8472-ff1a92cd65ff)

If you encounter any issues or have questions, feel free to ask! 🚀
