### ISSUE TITLE
Error debug serializing parameter: NoSuchMethodError

### ISSUE THREAD

**Issue by thomasallnice** [FlutterFlow/flutterflow-issues#3366]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am getting this error in FF Test Mode:

Firebase initialized successfully

dart_sdk.js:37972 Error debug serializing parameter: NoSuchMethodError: 'toDebugSerializableMap'

method not found

Receiver: Instance of 'JSArray<ListingImagesRecord>'

Arguments: []

dart_sdk.js:37972 Error debug serializing parameter: NoSuchMethodError: 'toDebugSerializableMap'

method not found

....

If I publish to web I do not get these issues.

The issue slow down the website and even cause memory issues on my machine (at least that´s what I think causes my memory problems)

### Expected Behavior

Website preview should perform better

### Steps to Reproduce

preview mode ff project

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ok8/6x8pgrsdY1pDLbcdajSQWNUs4RL8/lspBZywgfZzzBLN/fPfQP1BvZMCoT1V+e2Ccp140p/D7iYThDvZfITCuY4Ri+M9udAyVJUinbKmTF7m8Q3MmEcRgf2KZ1KS3sxYlFNFsWkIF6mCQC+eiQXLUHrn6DVQ8Sq/LZO4=

### Visual documentation

<img width="795" alt="Bildschirmfoto 2024-07-10 um 13 59 17" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6171130/f96cf711-1a6b-48df-8488-48d675e2d431">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by computerfreak84** [comment]
I'm getting the same error.

**Comment by dinesh-brilworks** [comment]
Same error, I think last two FlutterFlow versions are not stable, got Lottie issue yesterday.

**Comment by msusviela** [comment]
Hi, thank you for your report. We're unable to reproduce this from our side. Could you please tell us in which screen it's currently happening?<br><br>For the users with the same error, it would be very helpful for us if you could provide a Bug report code (you can generate one by clicking right on the widget tree and select the option to generate it) and by indicating in which screen is this happening, so we can investigate this issue.<br><br>Thank you!

**Comment by tiagosilveiransj** [comment]
> Hi, thank you for your report. We're unable to reproduce this from our side. Could you please tell us in which screen it's currently happening?For the users with the same error, it would be very helpful for us if you could provide a Bug report code (you can generate one by clicking right on the widget tree and select the option to generate it) and by indicating in which screen is this happening, so we can investigate this issue.Thank you!

Hi, here's my bug report code ITFTisjLuIxOxMBJ+KncasJ4p2A6M0MdXOczitVEew4bCIj4P5kMZuPBYhBtOL2zaHxqDU6j/X4G0vDHv/LmUPo3ISerG9xx1Yd2EBPPbD+gMbqsPc+WQkBCLJ5YCG6F4Z2JuyZ7Ns5vdEZhw1OuP/CUaz6Cf9qOYwx5e6fDbOY= the page is 'ordemServico'

**Comment by thomasallnice** [comment]
here is mine:
IT4ok8/6x8pgrsdY1pDLbcdajSQWNUs4RL8/lspBZywgfZzzBLN/fPfQP1BvZMCoT1V+e2Ccp140p/D7iYThDvZfITCuY4Ri+M9udAyVJUinbKmTF7m8Q3MmEcRgf2KZ1KS3sxYlFNFsWkIF6mCQC+eiQXLUHrn6DVQ8Sq/LZO4=

click on "loop scarf": You will experience the lag and errors in the console

if you cannot reproduce due to errors in the code (currently working on it) please visit the webpage and navigate to "test" (debug symbol in nav column) click on "loop scarf" there

**Comment by msusviela** [comment]
@thomasallnice in which screen is loop scarf located? I can't find it

**Comment by thomasallnice** [comment]
> @thomasallnice in which screen is loop scarf located? I can't find it

<img width="476" alt="Bildschirmfoto 2024-07-11 um 17 21 04" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6171130/3a9e268a-9576-4652-89eb-1a1c6b7e5d4d">

test mode is now available again

**Comment by TidoGarnier** [comment]
Exactly the same here! FYK.

**Comment by laughingbuddha24** [comment]
I have the same issue. Bug report code:

IT4shcmAx491ofpE0LruY8dB/WIUH198RoE8scp/bxIgGIDzPOw+ZPXsbltDXdfkdAh+J0SmmXwE+N7uieP9V8EDNRCbGZh4wbVicw2VUka6a5OBEpCwen95BeFRBW6DyqWRnxRCIuhqdVY72Du6BOmUZ3TfHpy0ImdISq/LZO4=

**Comment by EladioRocha** [comment]
I have the same issue

Bug report code: IT4WiMmA5YpItbxG7pSJY/pVtDw5KUQnUIZMmMN+VQI3fbXpO4wPXfikSEpWZ9+kTHxcL2KWgmYd+sqPkYaXA+UpCy2YfLpIwodbWBfye3KhVqXRC6ioSmpREp5JJVzGyJmjmh4lANZvcUZi2zupONnLTTDBK4/6O0YsRP2jBKHVjkmrQ0SLb3kNh1JWeC/v

**Comment by paulperez-dev** [comment]
Hi everyone! The team is working on a fix 😀 I will keep you posted here!

**Comment by laughingbuddha24** [comment]
Is there any update on this? I can't test any new dev work therefore I can't deploy anything until this bug is fixed, and I have a few important updates to release.

** is there a workaround? Can we disable the debug panel somehow?

**Comment by Arkhemis** [comment]
Same issue. Thought it was because of a mistake in my code but I'm pretty sure it's because of the new debug panel. Pretty annoying since it's cluttering the debug console.

**Comment by yairpe** [comment]
same here

**Comment by MahmoudIsmail88** [comment]
same issue here now

**Comment by Wittrup90** [comment]
Same issue - ended up here after hours in support with you guys... come on.. i'm actually trying to run a business with FF, this is not a hobby project. And you keep making me consider to get the hell out of FF with all these bugs that slow down progress.

**Comment by celiostat** [comment]
I am having the same issue, and this is completely a bummer. I have been stuck for more than 2 weeks. 
Bug report code : ITFXi/Lqw5VIrsBE7arhKe1anj8wGUwbUOc7j9VEGAsjCePvPbADPs/Cbk5tYuqHeW9MOWKGkng0w/zHjYTpCcIrGAWbftk6wqhPUxDhVkCuV82vDqWWdH9ATPxRfUyh05iRrR15OtdpciRh7EOMFty+Y3qCf9qOYwx5e6fDbOY=

**Comment by laughingbuddha24** [comment]
Hi @paulperez-dev please provide an update on this issue. You've acknowledged that this is a bug and advised that the team is working on a fix then given us no updates. This issue is two weeks old and is a breaking issue that has stopped work for many developers. It should be a priority and we should be getting updates.

**Comment by abbasali-io** [comment]
Hello Flutterflow team, @paulperez-dev , how can you still be 'waiting for user's response' while so many users have provided the debug report code, we are all being bogged down with this issue, could you suggest, either a resolution, a workaround, or a timeline so we can plan our production. Guys, dont go cold on us!

**Comment by paulperez-dev** [comment]
Hi everyone! The team fixed the issue but it still needs to pass QA/Beta. Tags updated.

**Comment by leighajarett** [comment]
Hi there! I think this should be resolved now - can you all check and let us know if you're still running into issues?

**Comment by EladioRocha** [comment]
> Hi there! I think this should be resolved now - can you all check and let us know if you're still running into issues?

Thank you, FF team! Everything is correct on my side.

**Comment by Wittrup90** [comment]
4.1.76 did not solve it for me. 
<img width="547" alt="Screenshot 2024-07-25 at 08 37 44" src="https://github.com/user-attachments/assets/37676829-94ae-4233-9027-e586dbe0e924">

**Comment by leighajarett** [comment]
Can you send your bug report code so we can take a look?

**Comment by wolfhoundgelert** [comment]
@leighajarett hey!

Is this kind of errors being from the Debug Panel feature?

> Error debug serializing parameter:

Is there a way to disable this feature? It's too buggy and shoudn't be in production.

**Comment by wolfhoundgelert** [comment]
And I have an error on the project that was working well for months and now I can't even run it in the test mode:

> Error debug serializing parameter: TypeError: Instance of 'JSArray<DefaultUserSettingsRow>': type 'List<DefaultUserSettingsRow>' is not a subtype of type 'SupabaseDataRow'

It's f...ng disaster

**Comment by wenkaifan0720** [comment]
Hi @wolfhoundgelert. Sorry for the inconvenience. Could you share a bug report code?

The error you see is coming from the logging call of debug panel, which shouldn't affect the running of your app. Debug panel is more like adding print statements in places of your app, it shouldn't change the logic of your app. 

But if you want to disable debug panel, you can use local run (which has the option to disable it).

**Comment by wenkaifan0720** [comment]
> 4.1.76 did not solve it for me. <img alt="Screenshot 2024-07-25 at 08 37 44" width="547" src="https://private-user-images.githubusercontent.com/146844329/351990580-37676829-94ae-4233-9027-e586dbe0e924.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTA4NzksIm5iZiI6MTcyMTkxMDU3OSwicGF0aCI6Ii8xNDY4NDQzMjkvMzUxOTkwNTgwLTM3Njc2ODI5LTk0YWUtNDIzMy05MDI3LWU1ODZkYmUwZTkyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxMjI5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTZlMjA3ZWViMjVlNDkxYTI3YjExM2QwZDM3MTNhMzQwN2NiOWYyYzQzYTQ3NjBiOWZmMTc3N2ZlNGFhZTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VxZ_plesauFVoSLO9bkp7W-ntv4EhPUpR2oQriU4NbI">

@Wittrup90. The `Error serializing doc` you see is not coming from debug panel. It could be that your firebase schema is different from the one in the FF app. Or are you still seeing the `Error debug serializing parameter` log in test mode?

**Comment by leighajarett** [comment]
The option to turn it off in local run will actually be available in a week and half, sorry for confusion!

**Comment by wolfhoundgelert** [comment]
@wenkaifan0720 Hi!

ITFTzPLq4otOxdsA+KXubPpWpCc7GUMcWOdEl+tuZwgbIoznBuwXPs+lRFJuTsO7aVNcGk6Z+VgE0aH9uNmXUsc3GxSdGrk6z7p+dAv0e2i6abrTC7rpe3N6HdpWCB2gyJ6Jmx5+NbN1ciEBw06PNuyuYHbDIuu/Zwh9f6PHaOI=

> The error you see is coming from the logging call of debug panel, which shouldn't affect the running of your app. Debug panel is more like adding print statements in places of your app, it shouldn't change the logic of your app.

Can't agree with you on that matter)

As I see, there's an error with some paint operation. And I can see some painting in the DB panel (see the screenshot). Also my project doesn't use any CustomPainters as it  mentioned in the console - maybe some FF components do, but I don't know and this is the project that runs on production for months.

![Screenshot 2024-07-25 171818](https://github.com/user-attachments/assets/41b4a8aa-ec80-43f3-8468-28431001cbb4)

**Comment by wenkaifan0720** [comment]
Thanks for the info! I'll look into your project now.

**Comment by wenkaifan0720** [comment]
The uncaught error seems to be coming from the `smooth_page_indicator` package which we use for the `PageView` widget. If I remove the `PageView` on your home page, then this error would go away. It might be that there are some variable value that is not set properly. 

The slowness of your app is indeed due to debug panel, but for a different reason. There are too many items on the home page (>500), and debug panel hit a character limit when trying to serialize your page's data (to visualize it on the frontend). We will soon let you disable debug panel so the performance is back to before.

**Comment by wolfhoundgelert** [comment]
@wenkaifan0720 

> The uncaught error seems to be coming from the smooth_page_indicator package which we use for the PageView widget. If I remove the PageView on your home page, then this error would go away. It might be that there are some variable value that is not set properly.

Could this be related to the transition to a new version of Flutter? Did you check your components when switching to the new Flutter? Because I realy don't know what else it could be as I haven't touched this functional recently.

> The slowness of your app is indeed due to debug panel, but for a different reason. There are too many items on the home page (>500), and debug panel hit a character limit when trying to serialize your page's data (to visualize it on the frontend). We will soon let you disable debug panel so the performance is back to before.

Ok, I can bypass that by limiting the query for those items. And I will look forward for a switcher for the Debug Panel.

Thank you!

**Comment by wolfhoundgelert** [comment]
@wenkaifan0720 PageView is good - found the issue in data from the server after getting the ability to use the test mode.

Thank you again! Hope we'll get the switcher for the DB panel soon) ❤
