### ISSUE TITLE
problem with saving theme widgets

### ISSUE THREAD

**Issue by Rezwalqer** [FlutterFlow/flutterflow-issues#3367]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When saving theme widgets such as "button" the changes I try to save are not applied. when I try again it resets to default parameters of text, color, etc. after about 5 attempts I managed to save only one change (font size).

### Expected Behavior

when saving theme widgets new data is applied to this widget

### Steps to Reproduce

1. create new theme widget
2. make changes to the widget parameters
3. save the widget
4. откройте его снова

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkvLlx5NgochE1a6Jb+0wqCEsQz4cTeU30+thcw4bI+KqE4khP/TCVFRVYuqHYwpDM1Sbgjoy+fTnv9jxUMICA0mVGKph1KtfUxDgTlmhV4iJBaWaVkElJ8dRN2qn0Z2RuwpAKsF0S3ws7TuuAd6QY3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/118208999/d51fbeda-b276-414f-8ea0-d6aaedabff47

### Environment

```markdown
- FlutterFlow version: 4.1.70
- Platform:Web
- Browser name and version:Chrome 126.0.6478.127
- Operating system and version affected: Windows 10
```

**Comment by msusviela** [comment]
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by msusviela** [comment]
Hi @Rezwalqer. In the new update (1.4.71) this is fixed. Please let me know if you stillface this. Thanks!

**Comment by ReflexOlivier** [comment]
The issue is always present. Saving is randomly executed.

**Comment by saurabhqaengineerfp** [comment]
Why has this issue been closed, I am still seeing this. I have tried safari, chrome and firefox, I have tried clearing out the full cache on all browsers, I have tried hard resetting all the browsers, I have tried flutterflow desktop app, I have tried restarting system several times. Have tried everything that I can but theme widgets are now impossible to get any changes saved, I can't change color, can't save border radius change, can't change label text size, cant save hint text size, nothing is getting saved, only gets saved 1 out of 20 times. Impossible to use, I am not sure how is this not a showstopper bug til now, how are many people not reproting it? Maybe far less people are using flutterflow than what I am imagining.

**Comment by msusviela** [comment]
Sorry you're experiencing this. We closed it at the moment because it was working. Now it's not working but the team it's already working on a fix for this. Keeping this close because when it started failing again another issue was opened. You can follow this here:<br>[https://github.com/FlutterFlow/flutterflow-issues/issues/3392](https://github.com/FlutterFlow/flutterflow-issues/issues/3392)<br><br>Sorry you're experiencing this! <br><br>@saurabhqaengineerfp @LouisTheBoss
