### ISSUE TITLE
Using Current Time option to update a Time column from Supabase throw an error

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#342]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Update a Supabase column with Time data type

## Current behavior (required)

Throw an error

## To Reproduce (required)

1. Create a Supabase table and add a column with Time data type
2. Get the schema on FF
3. Create a button and add an update supabase row
4. Select the column with Time data type and use the current time option to update the data

### Bug Report Code (required, generate from Widget Tree)

ITESz8rluJNgrs9f7arqLO1QhQAkH1x/bZJEl9cbGA4aF4yoELQQO+r+V1VvZsfgTGxqB06J8V0Cp+j5k/HXJPAqYCSdXNE2k/UwKlCvHAM=

## Context (required)

I want update a Supabase column with the time

## Screenshots / recordings

If we see the console we can see this error
![image](https://user-images.githubusercontent.com/36147203/211698221-93cdc0fa-0b7b-49eb-8288-15bece84a7a2.png)

## Your environment

* Version of FlutterFlow used: 10 January
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by Franco98404** [comment]
Another problem related to this is when I have a Time column and I want to show it on FF always produces an error: "null value"

**Comment by victoriahuang1** [comment]
Hi @Franco98404 , thanks for the report. We found a bug on our side, which should now be fixed upon our next deploy!

**Comment by Franco98404** [comment]
Hello, the error still persists in the last update (January 24). @victoriahuang1 @bulgariamitko

**Comment by bulgariamitko** [comment]
Ok I will reopen the issue so FF team can look into it again. Can you please tell me if there is any difference or the issue it is exactly the same?

**Comment by Franco98404** [comment]
Hi @bulgariamitko, is exactly the same

**Comment by Franco98404** [comment]
> Another problem related to this is when I have a Time column and I want to show it on FF always produces an error: "null value"

Still persist this erro too.

**Comment by victoriahuang1** [comment]
Hi @Franco98404, doesn't look like the commit with the fix was included in the deploy. It should go out with the next deploy though!

**Comment by Franco98404** [comment]
In the last update (January 26) the fix is not included yet. :c @bulgariamitko @victoriahuang1

**Comment by agreaves** [comment]
That update was a hotfix to fix a major breaking change so no other commits were included.

**Comment by Franco98404** [comment]
Thanks for clarify!

**Comment by Franco98404** [comment]
The fix is not included in the last update (February 2) either. @bulgariamitko @victoriahuang1

**Comment by victoriahuang1** [comment]
Hi @Franco98404 that deploy was for different bug fix. This one has not deployed yet. We expect it to get deployed some time next week.

**Comment by Franco98404** [comment]
Now it's solved! Thanks!
