### ISSUE TITLE
Flutter Flow charts does not consider Date Data Types

### ISSUE THREAD

**Issue by minashawky** [FlutterFlow/flutterflow-issues#35]
## Expected behavior
When using the Chart widget I'm expecting to be able to specify a "Date" object in the value field for the chart data

## Current behavior 
The chart breaks when I specify a "Date" object type.

## To Reproduce 

1. Add a Chart Widget
2. Connect the chart with a Firebase collection that includes two fields (a date field and a numeric value field)
3. Link the date field to the X-Axis and the numeric value field to the Y-Axis of the chart

The following function won't be able to convert the date field to double as expected:

`List<double?> _dataToDouble(List<dynamic> data) { if (data.isEmpty) { return []; } if (data.first is double) { return data.map((d) => d as double).toList(); } if (data.first is int) { return data.map((d) => (d as int).toDouble()).toList(); } if (data.first is String) { // First try to parse as doubles if (double.tryParse(data.first as String) != null) { return data.map((d) => double.tryParse(d as String)).toList(); } if (int.tryParse(data.first as String) != null) { return data.map((d) => int.tryParse(d as String)?.toDouble()).toList(); } if (DateTime.tryParse(data.first as String) != null) { return data .map((d) => DateTime.tryParse(d as String)?.millisecondsSinceEpoch.toDouble()) .toList(); } } return []; }`

## Context (required)
I was not able to use the Chart widget out of the box without fixing the code manually... The fix I applied was an additional condition/check for the date as follows:

`List<double?> _dataToDouble(List<dynamic> data) { if (data.isEmpty) { return []; } if (data.first is double) { return data.map((d) => d as double).toList(); } if (data.first is int) { return data.map((d) => (d as int).toDouble()).toList(); } if (data.first is String) { // First try to parse as doubles if (double.tryParse(data.first as String) != null) { return data.map((d) => double.tryParse(d as String)).toList(); } if (int.tryParse(data.first as String) != null) { return data.map((d) => int.tryParse(d as String)?.toDouble()).toList(); } if (DateTime.tryParse(data.first as String) != null) { return data .map((d) => DateTime.tryParse(d as String)?.millisecondsSinceEpoch.toDouble()) .toList(); } } if (data.first is DateTime) { return data .map((d) => (d as DateTime).microsecondsSinceEpoch.toDouble()) .toList(); } return []; }`

**Comment by katherineqian** [comment]
Hi, 

In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided. 

Thank you!

**Comment by minashawky** [comment]
## Expected behavior
When using the Chart widget I'm expecting to be able to specify a "Date" object in the value field for the chart data


## Current behavior 
The chart breaks when I specify a "Date" object type.


## To Reproduce 

1. Add a Chart Widget
2. Connect the chart with a Firebase collection that includes two fields (a date field and a numeric value field)
3. Link the date field to the X-Axis and the numeric value field to the Y-Axis of the chart

The following function won't be able to convert the date field to double as expected:

`List<double?> _dataToDouble(List<dynamic> data) { if (data.isEmpty) { return []; } if (data.first is double) { return data.map((d) => d as double).toList(); } if (data.first is int) { return data.map((d) => (d as int).toDouble()).toList(); } if (data.first is String) { // First try to parse as doubles if (double.tryParse(data.first as String) != null) { return data.map((d) => double.tryParse(d as String)).toList(); } if (int.tryParse(data.first as String) != null) { return data.map((d) => int.tryParse(d as String)?.toDouble()).toList(); } if (DateTime.tryParse(data.first as String) != null) { return data .map((d) => DateTime.tryParse(d as String)?.millisecondsSinceEpoch.toDouble()) .toList(); } } return []; }`

## Context (required)
I was not able to use the Chart widget out of the box without fixing the code manually... The fix I applied was an additional condition/check for the date as follows:

`List<double?> _dataToDouble(List<dynamic> data) { if (data.isEmpty) { return []; } if (data.first is double) { return data.map((d) => d as double).toList(); } if (data.first is int) { return data.map((d) => (d as int).toDouble()).toList(); } if (data.first is String) { // First try to parse as doubles if (double.tryParse(data.first as String) != null) { return data.map((d) => double.tryParse(d as String)).toList(); } if (int.tryParse(data.first as String) != null) { return data.map((d) => int.tryParse(d as String)?.toDouble()).toList(); } if (DateTime.tryParse(data.first as String) != null) { return data .map((d) => DateTime.tryParse(d as String)?.millisecondsSinceEpoch.toDouble()) .toList(); } } if (data.first is DateTime) { return data .map((d) => (d as DateTime).microsecondsSinceEpoch.toDouble()) .toList(); } return []; }`

**Comment by agreaves** [comment]
Thank you @minashawky for the bug report and apologies for the late fix! This should be fixed upon our next release! 🙂

**Comment by minashawky** [comment]
Thank you @agreaves and the team... Keep up the great work 👍

**Comment by GersonFuentes** [comment]
How many years since this, and the charts still don't receive datetime in X-axis
@minashawky @agreaves @katherineqian @asmengistu
