### ISSUE TITLE
List View with scroll gets error and hangs on test & run modes, does not load the list on real device (Another exception was thrown: PersistedOffset: is in an unexpected state.)

### ISSUE THREAD

**Issue by irfan-ahmed-1982** [FlutterFlow/flutterflow-issues#351]
## Expected behavior (required)
List view to generate the children dynamically and scroll up and scroll down. The Rest API Response is perfect when tested but when in run mode there comes the error.

## Current behavior (required)
Keep on getting error **"Another exception was thrown: PersistedOffset: is in an unexpected state."**

## To Reproduce (required)

1. Create new page
2. Add container widget
3. Add list view with scroll enabled, add a backend call using **full text search supabase search  API (https://YOUR_PROJECT_NAME.supabase.co/rest/v1/YOUR_TABLE?state=eq.[state]&or=(YOUR_COLUMN.wfts(english).[SearchString],YOUR_ANOTHER_COLUMN.wfts(english).[SearchString],YOUR_ANOTHER_COLUMN.wfts(english).[SearchString]))** and then generate children dynamically with API call response
4. Click Run
5. Scroll on the List and observe the scroll brings down the error **"Another exception was thrown: PersistedOffset: is in an unexpected state."** and hangs the screen.

### Bug Report Code (required, generate from Widget Tree)

IT8Cls/l5Yx2sdtJ14SJd8BvoDs5KWk7apZNm8JAEBAdGL6vPe0Xe+D8R1tBY7TidHw7JWKJnVgVweDPv4f1NcI4B06XGZx5/roJFxXgQXGzaq6KEZCweHZ9GdhgCWbA3Im0kxBAFMtfWCUX7Vr/cq3qNleeY8aSfxBlZ7vfcPo=

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/118018023/212470126-0056e1f3-4090-46d5-96a9-9e0dbbbf5147.png)

## Your environment

* Version of FlutterFlow used: 3.3.4 (13 January 2023)
* Platform (e.g. Web, MacOS Desktop): Desktop
* Browser name and version: Chrome Desktop
* Operating system and version (desktop or mobile): Windows 11.

**Comment by Pepino-GR** [comment]
Hi irfan-ahmed-982,

In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
Thank you!

**Comment by nicmohr25** [comment]
I think i ran into the same issue and could trace it back to the rating bar. As soon as a removed the rating bar the list view worked as expected.

https://github.com/FlutterFlow/flutterflow-issues/issues/215

**Comment by irfan-ahmed-1982** [comment]
> 

Thank you for the information. I think you are right as I can trace it on the same rating bar. Rating bar expects value type double with precise decimal. I have the ratings column with data type as double. But the problem is if I insert 5.0 the column accept as 5 and flutterflow could possibly reading it as integer ( I am not sure on this though). But when I change the value to 4.99, list view works as expected. FlutterFlow team please consider looking into this.

**Comment by nicmohr25** [comment]
Definitely interesting behavior. Maybe with two cases this will help the FF Team to fix the bug

**Comment by irfan-ahmed-1982** [comment]
I have further broken this issue, In **SUPABASE** you have an option of DATA TYPE **# numeric** this accepts the data into precision decimals. You just need to change your rating's DATA TYPE to **# numeric** and change the **Default Value to 0.00**. when you call that **API** and pass the parameter **rating** to the rating bar it will accept as double and your problem is solved.

![image](https://user-images.githubusercontent.com/118018023/212846365-c204794f-6d61-480a-9943-9b537278c983.png)

@nicmohr25 I thank you for putting me on the right direction.

**Comment by wenkaifan0720** [comment]
Hi @irfan-ahmed-1982. Is your issue resolved now? Is your app only freezing in run/test mode or on all platforms?

**Comment by irfan-ahmed-1982** [comment]
Its still exists but not only on List View but on the back buttons also. The TestMode is only having this bug its going good on RunMode and actual devices.

**Comment by wenkaifan0720** [comment]
I see. This might be a Flutter web issue then as in TestMode we are running Flutter web in debug mode. And this mode should be less stable and performant than other platforms (but allows you to do hot reload).

**Comment by luizfelipevbll** [comment]
I have a very similar problem in the PWA version of the app on Safari IOS
So is not only on test mode.

**Comment by luizfelipevbll** [comment]
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/40257388/11b0111f-8c30-4337-96f4-79a67ff854db)

I still have the same issue on Run/test mode and PWA. deployed App
Tested on Chrome, Brave and Safari, problem occurs in all of them

**Comment by luizfelipevbll** [comment]
Probably related to the **404 Not Found** of the dart_sdk.js.map ?
https://storage.googleapis.com/flutterflow-prod-hosting/debugger-cache/1687572676/dart_sdk.js.map

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/40257388/b213e4f6-65b8-475f-b3cb-774abf8dab6d)

**Comment by wenkaifan0720** [comment]
Hi @luizfelipevbll. Could you try toggle on the Use Canvaskit (beta) setting in web publishing and see if the issue persists? We are in the process of migrating to the Flutter canvaskit web renderer which is supposed to have better performance and consistency.

**Comment by agreaves** [comment]
Hi @irfan-ahmed-1982 and all, thanks for the bug report and all of the useful information. It appears this is simply an issue with the Rating Bar widget when it goes back on screen after going off screen in Flutter Web.

There unfortunately isn't a lot we can do as an issue with the [package](https://pub.dev/packages/flutter_rating_bar) we are using, but fortunately as @wenkaifan0720 mentioned we are moving toward using CanvasKit by default, which you should be able to set in the Platform and Web Publishing settings. The issue is not present when using CanvasKit.

I'm going to close this issue for now as we have a fix (and there isn't much we can do otherwise). Apologies for the inconvenience with this issue!
