### ISSUE TITLE
Network Disconnected / Project no Synced Again

### ISSUE THREAD

**Issue by VargasPiensa** [FlutterFlow/flutterflow-issues#3599]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Dear FlutterFlow Support Team,

I would like to report again 
a critical issue we're experiencing with our project. When attempting to make new updates, we notice that after every two actions, or even fewer, the project disconnects or desynchronizes, preventing us from saving the changes made. This is blocking our progress, and we cannot move forward with the development of the project, which we urgently need to complete.

This issue is not isolated, as other team members have reported the same problem. We would appreciate a prompt resolution or guidance on how to address this situation, as it is significantly affecting our workflow.

Thank you for your attention, and we look forward to your prompt response.

Best regards,

Daniel Vargas
Sailer App CEO

![photo_5001359880434593618_x](https://github.com/user-attachments/assets/9bced21f-3fed-4ae7-8fcb-7e7f2a6c69db)
![Captura de pantalla 2024-08-04 131613](https://github.com/user-attachments/assets/3b1cb2fe-1ea7-40d6-b98c-8fc73b1d6782)

### Expected Behavior

The expected behavior of our project is for it to operate regularly and stably within FlutterFlow. This means that we should be able to perform any action available on the platform without issues, including creating components and widgets, as well as adding information to the project.

It is crucial that the project maintains a continuous and uninterrupted connection, allowing us to save changes and updates smoothly. Every action, from the simplest to the most complex, should be able to be completed without the project disconnecting or desynchronizing.

We hope this issue can be resolved so we can efficiently continue our development tasks.

Thank you in advance for your assistance.Thank you in advance for your assistance.

### Steps to Reproduce

Just try to perform more than 4 actions and you will see that it is not possible.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48hfLl5Yx2rsRE7ZPuY8JV+TwWQkc7bbg4mOtEFAg8J5zKB+wAYvf7P1FWTL3iT1ViemKKhmE01vfqjd7pU/kEITaBGaZgzpABbxXyLVGjb5vWO5DofW1RO+lTGW6F5KaVuAhAPuteSnwi6k2YCOevFwzbQYDKIUgzMsqlJdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![photo_5001359880434593618_x](https://github.com/user-attachments/assets/7cddf82b-ec04-4510-9208-31a4d1260b34)
![Captura de pantalla 2024-08-04 131613](https://github.com/user-attachments/assets/511adbbc-f88b-473b-8c36-6f93cc3b3714)

### Environment

```markdown
- FlutterFlow version: v4.1.79+ released August 4, 2024 Flutter version is 3.22.2
- Platform:Web
- Browser name and version:Chrome
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!!

First of all, I’m sorry you’re experiencing this issue. I noticed from your screenshot that it says v4.1.79+, but we are currently on v4.1.81+. Could you please try pressing **CTRL + SHIFT + R** to refresh and load the latest version, or try clearing your cache and reopening the project? I was able to open it without any issues on my end.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b887e99b-9c3b-42df-99d7-2f7fd31e86bb/7b784bd4-1242-4f01-9177-4290ca1e986d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iODg3ZTk5Yi05YzNiLTQyZGYtOTlkNy0yZjdmZDMxZTg2YmIvN2I3ODRiZDQtMTI0Mi00ZjAxLTkxNzctNDI5MGNhMWU5ODZkIiwiaWF0IjoxNzIzNDY1NTk2LCJleHAiOjMzMjk0MDI1NTk2fQ._CoRvblxB77S4KYyWzVlFuMZR5vL67qvyIzv0yAmSfI " alt="image.png" width="233" height="142" />

**Comment by VargasPiensa** [comment]
The screenshot was old, the error persists.
![Captura de pantalla 2024-08-12 153402](https://github.com/user-attachments/assets/7e1c6d72-20c3-49b5-ba3c-f95a3e65dc2b)

**Comment by khomya** [comment]
I have the same problem for the last 48 hours!

I created a ticket (Ticket ID #5777) with techsupport more then 24 hours ago and its still not even read by anyone.

I cant do anything in my project!

I tried web - on Chrome and Safari with 4.1.81 and on Mac App 4.1.82 - NOTHING.

Pls. Do something! Its VERY annoying that i pay money but dont have a possibility to work and not even get a response to posted problems.


Error code: IT4wkfHlsIZ2xOFY+KXqdcFv+SAWCDp/aJ0/lu4aRis9GYjyO5YUac7BQBBBOfWgTW9XKEWIuDoEwfCKjezuU+1eH0mtRb5Hys9yVTrdRj+/aoTXO7jhQUB9I+FPG1Sd37W0kxB+BNdZdE443UOhevOQdCzsQJP6Zwh9f6PHaOI=

https://app.flutterflow.io/project/georgia-tennis-4hpmkx

**Comment by khomya** [comment]
<img width="282" alt="Screenshot 2024-08-13 at 10 48 56" src="https://github.com/user-attachments/assets/c8351c10-afa5-4c17-b061-0622311e8ec0">
Still dont sync

**Comment by khomya** [comment]
And in Safari - I even get a "Syncing..." and then "Saved".
But in fact - nothing is saving!
<img width="236" alt="Screenshot 2024-08-13 at 11 41 19" src="https://github.com/user-attachments/assets/cb7e3aee-526f-457d-867f-75e5eefeed23">

**Comment by VargasPiensa** [comment]
The Issue persist, I need this resolved as quickly as possible. Please

**Comment by Alezanello** [comment]
Hello Again!

It appears to be very specific to some projects. Since this GitHub Issue Tracker is primarily for bugs that can be replicated in a new blank project, I wasn’t able to find a way to assist you directly.

For a more tailored solution, I strongly recommend reaching out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). They’ll have the right tools and insights to help you resolve this issue.

Best regards,

Azanello

**Comment by khomya** [comment]
I wrote to in-app chat - and now its 2 days - i still didnt get a response that anyone is on this problem.
So I write here!

**Comment by br0nk** [comment]
This should be resolved for this project.  Thank you for your patience, and please let us know if you see this again.

**Comment by khomya** [comment]
Until I use translation feature - the FF is working.
But when I try to translate anything - I still get the "Network Disconnected" message.

**Comment by Alezanello** [comment]
Hi Khomya, are you still experiencing this issue on the latest updates?

**Comment by khomya** [comment]
> Hi Khomya, are you still experiencing this issue on the latest updates?

Hi! For last 2 week everything is OK! :)

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
