### ISSUE TITLE
Can't deploy to app store - stuck in queue

### ISSUE THREAD

**Issue by arniigreat1** [FlutterFlow/flutterflow-issues#3770]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Stuck in queue and other people are also running into this major issue

See string of users impacted:
https://community.flutterflow.io/ask-the-community/post/code-magic-deployment---queued-for-hours-jyMprGVs9xmeBlu

### Expected Behavior

Deploy to app stores without waiting in queue for hours

### Steps to Reproduce

1. deploy to app store

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXk8n13811rsRE7ofibMZVgWMwGUwbUOc7j9VEGAsjCePvPYocYfSkVBBWSOqHSmNMP1D/mnoDpvTQiIaSGMIqYA2Vc4RAyLVhUxDvczmiM4yOPLigYncmN/hYCW6y5omrqx1CNslZdCFl32CMfueQb3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1056" alt="Screenshot 2024-09-07 at 12 03 15 AM" src="https://github.com/user-attachments/assets/19e940b3-3a76-4647-8baa-1b744d0940f7">
<img width="1061" alt="Screenshot 2024-09-07 at 12 03 17 AM" src="https://github.com/user-attachments/assets/47323575-1d39-44c6-b3cc-508b04a0445e">

### Environment

```markdown
- FlutterFlow version: v4.1.88
- Platform: macOS
- Browser name and version: 128.0.6613.119 
- Operating system and version affected: macOS sonoma 14.3 (23D56)
```

**Comment by abhibalani** [comment]
Facing same issue.

**Comment by sergevb** [comment]
Unfortunately same for me.

FlutterFlow v4.1.88 released September 6, 2024
Flutter version is 3.22.2

**Comment by michelflight** [comment]
Unfortunately same for me.

FlutterFlow v4.1.88 released September 6, 2024
Flutter version is 3.22.2

**Comment by arniigreat1** [comment]
My app got deployed to app store, but FF is still stuck in queue now

**Comment by Samoon-Digital** [comment]
Same Issue Here Fix Asap

**Comment by Samoon-Digital** [comment]
The Biggest Bug Is In flutterflow . Support Service very poor

**Comment by Samoon-Digital** [comment]
<body style="background-color:#14161C">
<style>
body {
  color:#C8C8C8;
  overflow-x: hidden;
  padding-top: 0px;
  padding-right: 5px;
  padding-bottom: 5px;
  padding-left: 5px;
  font-family: monaco;
}
h4 {
  margin-bottom: 4px;
  font-weight: bold;
  color: #DF3F3F;
}
</style>
<h4>Failed Step: Generate Launch Icon</h4>
<div style="white-space: pre-wrap;line-height: 1.5">
════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)                               
  ════════════════════════════════════════════
  
• Creating default icons Android

✕ Could not generate launcher icons
PathNotFoundException: Cannot open file, path = 'assets/images/app_launcher_icon.png' (OS Error: No such file or directory, errno = 2)


Build failed :|
Step 6 script `Generate Launch Icon` exited with status code 2
</div>
</body>
  
also this error occured

**Comment by itsstevenliu** [comment]
Same problem

**Comment by rzambroni** [comment]
Hi everyone,

Thank you for reaching out and for your patience. It appears the recent issue with builds being stuck in the queue was due to an outage on Codemagic's side. Unfortunately, in these situations, there's not much we can do directly as it's related to a third-party service rather than a bug within FlutterFlow.

The good news is that it looks like Codemagic has resolved the issue on their end, so everything should be back to normal now. If anyone is still experiencing issues, please let us know and we'll do our best to assist you!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/390b7386-4bf4-4b2e-9747-f8925d2298f0/4f3adb08-5dc4-4eb9-8b69-b864e3892acd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zOTBiNzM4Ni00YmY0LTRiMmUtOTc0Ny1mODkyNWQyMjk4ZjAvNGYzYWRiMDgtNWRjNC00ZWI5LThiNjktYjg2NGUzODkyYWNkIiwiaWF0IjoxNzI1NzM1ODYzLCJleHAiOjMzMjk2Mjk1ODYzfQ.PzCRGNSx1wh3C62tA2-5cuMP2IBy1nptACXw_21gPPw " alt="image.png" width="857" height="397" />

**Comment by Samoon-Digital** [comment]
still this issue is presist  please check carefully

**Comment by Samoon-Digital** [comment]
can not deploy to app store stuck in queue fix this asap

**Comment by abhibalani** [comment]
@rzambroni It is still not fixed.

**Comment by rzambroni** [comment]
Hi folks,

It looks like Codemagic experienced another issue with some builds earlier today, but it was resolved a few hours ago.

Were you able to continue with the deployments afterward?

here is codemagic's satus page for future reference: [https://status.codemagic.io/](https://status.codemagic.io/)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/359b706e-120c-49ac-b561-5c110672c705/90765f7d-ebcd-459f-a5d4-c69b5d5d9877?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNTliNzA2ZS0xMjBjLTQ5YWMtYjU2MS01YzExMDY3MmM3MDUvOTA3NjVmN2QtZWJjZC00NTlmLWE1ZDQtYzY5YjVkNWQ5ODc3IiwiaWF0IjoxNzI1ODA3MDgwLCJleHAiOjMzMjk2MzY3MDgwfQ.UT_nYRdVPAS6PdLYmWuu8Jr9Um-_14q-v-6FdSJjjWc " alt="image.png" width="877" height="468" />

**Comment by Samoon-Digital** [comment]
Still same issue presist

**Comment by Samoon-Digital** [comment]
this problem is still persisted for last three days what devloper team doing

**Comment by Samoon-Digital** [comment]
this issue not solved ok first check and then reply

**Comment by sambondareff** [comment]
I have this issue too, deployed a couple of days ago (its in Testflight), made a basic text change to a title and re-deployed and now it is stuck in queue.

**Comment by rzambroni** [comment]
Hi everyone! Could you please share your bug-report codes here? Our engineering team will need to review each individual project that is still experiencing issues to determine if a manual status reset is needed. Thank you for your cooperation!

**Comment by arniigreat1** [comment]
@rzambroni Mine works now but with a huge lag. One version took 10hours to be in queue, and last night was in queue for 2-3hours. But nicely, I'm not in a huge rush (deploying at EOD) for testing in the morning right now

**Comment by rzambroni** [comment]
Thank you for the update, @arniigreat1. It seems like Codemagic has been experiencing degradation issues over the past couple of days, which is likely causing the delays in the releases. As long as you are not stuck it should be resolved at some point by them. 🙏

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8dda15e6-7507-48bf-a93e-89a8118ef3ee/bff64266-7e99-45dc-865a-a49810783ed2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84ZGRhMTVlNi03NTA3LTQ4YmYtYTkzZS04OWE4MTE4ZWYzZWUvYmZmNjQyNjYtN2U5OS00NWRjLTg2NWEtYTQ5ODEwNzgzZWQyIiwiaWF0IjoxNzI1OTAxODMzLCJleHAiOjMzMjk2NDYxODMzfQ.3v-EdMvxonh_rexgI85fZ0-UdQv9My3ecx91mN78d9c " alt="image.png" width="847" height="616" />
