### ISSUE TITLE
Deployment Failing Since October 22 Update

### ISSUE THREAD

**Issue by cartworthy** [FlutterFlow/flutterflow-issues#4449]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Deployment is failing to the App Store. The error recommends downgrading the version of two dependencies but those versions also fail to deploy (along with any other version attempted).

<img width="709" alt="Screenshot 2024-10-22 at 4 46 18 PM" src="https://github.com/user-attachments/assets/2e74898f-486a-48f0-8c4e-9938b84b8567">

After downgrading, I get this error:
<img width="523" alt="Screenshot 2024-10-22 at 12 24 02 PM" src="https://github.com/user-attachments/assets/3c07ef9e-3232-415a-94fa-b786dbaef862">

### Expected Behavior

I would expect to be able to deploy to the App Store — and for the error output recommendations to work but they do not.

### Steps to Reproduce

1. Click "Deploy"
2. Wait a few minutes and observe Failed Logs

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

-

### Visual documentation

<img width="709" alt="Screenshot 2024-10-22 at 4 46 18 PM" src="https://github.com/user-attachments/assets/b9399151-5c51-45d5-96f4-51625293f298">

^ The first error

<img width="523" alt="Screenshot 2024-10-22 at 12 24 02 PM" src="https://github.com/user-attachments/assets/f5d07e42-350d-41d3-9bd0-e1c4e1b106d2">

^ The error I get after downgrading versions according to the previous errors recommendation.

### Environment

```markdown
- FlutterFlow version: 5.0.8+
- Platform: Mac (Desktop app or web both with the latest update)
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

### Additional Information

I am feeling incredibly stressed because my app is a camera app that depends heavily on the camera functionality and this error has completely halted my progress. I've wasted this entire day hoping to find a solution on my own. I'm also not a developer so if this dependency issue isn't able to be resolved easily I'll have no idea how to fix it.

**Comment by paulperez-dev** [comment]
Hi @cartworthy,

Could you please try upgrading the **camerawesome** dependency to its latest version and let us know if that resolves the issue?

Thanks!

**Comment by chicacode** [comment]
**### FlutterFlow v5.0.8 + released October 22 2024 + Flutter 3.24.2 Package Upgrades - Failed  App Deployment on App Store & Play Store.**

After upgrading FlutterFlow to version 5.0.8 and Flutter to version 3.24.2, I encountered issues while deploying my app to both the App Store and Play Store. The recent changes in Flutter and package upgrades seem to be causing compatibility or build-related problems, preventing successful deployments. These issues were not present prior to the upgrade.

**Environment:**

FlutterFlow Version: 5.0.8
Flutter Version: 3.24.2
Target Platforms: iOS (App Store) & Android (Play Store)
Package Manager: pubspec.yaml
Issue Occurred On: Build and Deploy

**Steps to Reproduce:**

Upgrade FlutterFlow to version 5.0.8 and Flutter to version 3.24.2.
Implement the changes in an existing project or create a new one.
Try to deploy the app to the App Store or Play Store.
Observe build or deployment failures many times since yesterday.


**Expected Behavior:**
The app should build and deploy successfully to both the App Store and Play Store without errors.

**Actual Behavior:**
The app fails to build or is rejected during deployment, either due to compatibility issues with Flutter packages or unhandled exceptions in the latest upgrade.

**Error Logs/Output**

Failed Step: Install pods

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ The Google Privacy Policy describes how data is handled in this service.   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/to/crash-reporting                                     ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ║                                                                            ║
  ║ To disable animations in this tool, use                                    ║
  ║ 'flutter config --no-cli-animations'.                                      ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Resolving dependencies...
Because vivi depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.dev), version solving failed.


Build failed :|
Step 6 script `Install pods` exited with status code 69


**Potential Causes:**

Compatibility issues between new package versions and Flutter 3.24.2.
Build script changes introduced in the recent FlutterFlow upgrade.
Additional Notes:

This issue is affecting both iOS and Android platforms.
Reverting to the previous versions of FlutterFlow and Flutter resolves the issue.
![Screenshot 2024-10-23 at 8 11 57 AM](https://github.com/user-attachments/assets/3465fd2c-7851-4290-81b2-97d46a90030d)
![Screenshot 2024-10-23 at 9 02 37 AM](https://github.com/user-attachments/assets/e6cce754-177a-4f30-b62c-a287d2f9334f)

**Comment by rzambroni** [comment]
Hey @chicacode, that's a different issue, it has been resolved and it should now be fixed according to the [original ticket](https://github.com/FlutterFlow/flutterflow-issues/issues/4444) status.

**Comment by cartworthy** [comment]
@paulperez-dev I have tried updating the [CamerAwesome package](https://pub.dev/packages/camerawesome/versions) to the latest version 2.1.0.

Deploying with the latest 2.1.0 version results in this error:
<img width="715" alt="Screenshot 2024-10-23 at 12 40 12 PM" src="https://github.com/user-attachments/assets/c1240426-f0f4-4887-94e3-fbdf9e3566bf">

There's also a [migration guide](https://docs.page/Apparence-io/camera_awesome/migration_guides/from_1_to_2) for upgrading to camerAwesome 1.X.X to 2.X.X. I'm guessing my code won't work with the latest version. I was using 1.4.0 before.

For reference, I am not a developer. I pay for FlutterFlow Pro because I am not a developer and I like the platforms ease of accessibility for non-technical people, while also being scalable with custom coding. It is frustrating running into these errors because of updates to the platform that I didn't accept or ask for. I am hoping this is something that can be solved without hiring more developers.

**Comment by chicacode** [comment]
> Hey @chicacode, that's a different issue, it has been resolved and it should now be fixed according to the [original ticket](https://github.com/FlutterFlow/flutterflow-issues/issues/4444) status.

No, it is not fixed. I still have the issue I cannot deploy the app in App Store or Play Store

**Comment by agreaves** [comment]
@chicacode, do you still face the same issue? The fix for the issue you encountered has been deployed, so wondering if it's fixed for you or if you're running into another issue now. If there's still an issue, please provide a Bug Report Code to help us debug! Thanks.

**Comment by cartworthy** [comment]
@agreaves Hi Alex, can I get an update on my issue? 🙏

**Comment by DevKursat** [comment]
I get this error when distributing my app on the App Store but I haven't had any issues with the Play Store. @agreaves 

Failed Step: Install pods

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ The Google Privacy Policy describes how data is handled in this service.   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/to/crash-reporting                                     ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ║                                                                            ║
  ║ To disable animations in this tool, use                                    ║
  ║ 'flutter config --no-cli-animations'.                                      ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Resolving dependencies...
Downloading packages...
+ _flutterfire_internals 1.3.44
+ archive 3.6.1
+ args 2.6.0
+ assets_audio_player 3.1.1
+ assets_audio_player_web 3.1.1
+ async 2.11.0 (2.12.0 available)
+ auto_size_text 3.0.0
+ before_after_image_slider_nullsafty 1.0.1
+ boolean_selector 2.1.1 (2.1.2 available)
+ cached_network_image 3.4.1
+ cached_network_image_platform_interface 4.1.1
+ cached_network_image_web 1.3.1
+ carousel_slider 5.0.0
+ characters 1.3.0 (1.3.1 available)
+ checked_yaml 2.0.3
+ chewie 1.8.5
+ cli_util 0.4.1
+ clock 1.1.1 (1.1.2 available)
+ cloud_firestore 5.4.4
+ cloud_firestore_platform_interface 6.4.3
+ cloud_firestore_web 4.3.2
+ cloud_functions 5.1.3
+ cloud_functions_platform_interface 5.5.37
+ cloud_functions_web 4.10.2
+ collection 1.18.0 (1.19.1 available)
+ cross_file 0.3.4+2
+ crypto 3.0.6
+ csslib 0.17.3 (1.0.0 available)
+ csv 6.0.0
+ cupertino_icons 1.0.8
+ custom_image_crop 0.0.13
+ dbus 0.7.10
! device_info_plus 10.1.2 (overridden) (11.1.0 available)
! device_info_plus_platform_interface 7.0.1 (overridden)
+ dropdown_button2 2.3.9
+ emoji_flag_converter 1.1.0
+ extension 0.6.0
+ fake_async 1.3.1 (1.3.2 available)
+ ffi 2.1.3
+ file 7.0.1
+ file_picker 8.1.2 (8.1.3 available)
+ file_selector_linux 0.9.3
+ file_selector_macos 0.9.4+2
+ file_selector_platform_interface 2.6.2
+ file_selector_windows 0.9.3+3
+ firebase_auth 5.3.1
+ firebase_auth_platform_interface 7.4.7
+ firebase_auth_web 5.13.2
+ firebase_core 3.6.0
+ firebase_core_platform_interface 5.3.0
+ firebase_core_web 2.18.1
+ firebase_dynamic_links 6.0.8 (discontinued)
+ firebase_dynamic_links_platform_interface 0.2.6+44
+ firebase_messaging 15.1.3
+ firebase_messaging_platform_interface 4.5.46
+ firebase_messaging_web 3.9.2
+ firebase_storage 12.3.2 (12.3.4 available)
+ firebase_storage_platform_interface 5.1.31
+ firebase_storage_web 3.10.2 (3.10.3 available)
+ fixnum 1.1.1
+ flutter 0.0.0 from sdk flutter
+ flutter_animate 4.5.0
+ flutter_blurhash 0.8.2
+ flutter_cache_manager 3.4.1
+ flutter_card_swiper 6.0.0 (7.0.2 available)
+ flutter_google_places 0.4.0 from git https://github.com/ShehanYjoz/flutter_google_places.git at 52ddef
+ flutter_keyboard_visibility 6.0.0
+ flutter_keyboard_visibility_linux 1.0.0
+ flutter_keyboard_visibility_macos 1.0.0
+ flutter_keyboard_visibility_platform_interface 2.0.0
+ flutter_keyboard_visibility_web 2.0.0
+ flutter_keyboard_visibility_windows 1.0.0
+ flutter_launcher_icons 0.13.1 (0.14.1 available)
+ flutter_lints 4.0.0 (5.0.0 available)
+ flutter_localizations 0.0.0 from sdk flutter
+ flutter_plugin_android_lifecycle 2.0.20 (2.0.23 available)
+ flutter_secure_storage 9.2.2
+ flutter_secure_storage_linux 1.2.1
+ flutter_secure_storage_macos 3.1.2
+ flutter_secure_storage_platform_interface 1.1.2
+ flutter_secure_storage_web 1.2.1
+ flutter_secure_storage_windows 3.1.2
+ flutter_shaders 0.1.3
+ flutter_slidable 3.0.1 (3.1.1 available)
+ flutter_spinkit 5.2.0 (5.2.1 available)
+ flutter_staggered_grid_view 0.7.0
+ flutter_test 0.0.0 from sdk flutter
+ flutter_web_plugins 0.0.0 from sdk flutter
+ flutterflow_colorpicker 0.0.1+1 from git https://github.com/FlutterFlow/flutterflow_colorpicker.git at 7e9ae2
+ font_awesome_flutter 10.7.0
+ freezed_annotation 2.4.4
+ from_css_color 2.0.0
+ gesture_x_detector 1.1.1
+ go_router 12.1.3 (14.3.0 available)
+ google_api_headers 2.0.3 (4.2.5 available)
+ google_fonts 6.1.0 (6.2.1 available)
+ google_identity_services_web 0.3.1+4
+ google_maps_webservice 0.0.20-nullsafety.5 from git https://github.com/ShehanYjoz/google_maps_webservice.git at 1588c2
+ google_mobile_ads 4.0.0 (5.2.0 available)
+ google_sign_in 6.2.1
+ google_sign_in_android 6.1.30 (6.1.33 available)
+ google_sign_in_ios 5.7.7 (5.7.8 available)
+ google_sign_in_platform_interface 2.4.5
+ google_sign_in_web 0.12.4+2
+ html 0.15.4
! http 1.2.2 (overridden)
+ http_parser 4.0.2 (4.1.1 available)
+ image 4.2.0 (4.3.0 available)
+ image_gallery_saver 2.0.3
+ image_picker 1.1.2
+ image_picker_android 0.8.12+13 (0.8.12+17 available)
+ image_picker_for_web 3.0.5 (3.0.6 available)
+ image_picker_ios 0.8.12 (0.8.12+1 available)
+ image_picker_linux 0.2.1+1
+ image_picker_macos 0.2.1+1
+ image_picker_platform_interface 2.10.0
+ image_picker_windows 0.2.1+1
+ in_app_review 2.0.9
+ in_app_review_platform_interface 2.0.5
+ in_app_update 4.2.3
+ infinite_scroll_pagination 4.0.0
+ internet_connection_checker_plus 1.0.1 (2.5.2 available)
+ internet_file 1.2.0
+ intl 0.19.0
+ iregexp 0.1.2
+ js 0.6.7 (0.7.1 available)
+ json_annotation 4.9.0
+ json_path 0.7.2 (0.7.4 available)
+ leak_tracker 10.0.5 (10.0.8 available)
+ leak_tracker_flutter_testing 3.0.5 (3.0.9 available)
+ leak_tracker_testing 3.0.1
+ lints 4.0.0 (5.1.0 available)
+ logging 1.3.0
+ lottie 2.7.0 (3.1.3 available)
+ map_launcher 3.5.0
+ matcher 0.12.16+1 (0.12.17 available)
+ material_color_utilities 0.11.1 (0.12.0 available)
+ maybe_just_nothing 0.5.3
+ meta 1.15.0 (1.16.0 available)
+ mime 1.0.6 (2.0.0 available)
+ mime_type 1.0.0 (1.0.1 available)
+ nested 1.0.0
+ octo_image 2.1.0
! package_info_plus 8.0.2 (overridden) (8.1.0 available)
! package_info_plus_platform_interface 3.0.1 (overridden)
+ page_transition 2.1.0
+ path 1.9.0 (1.9.1 available)
+ path_provider 2.1.4
+ path_provider_android 2.2.10 (2.2.12 available)
+ path_provider_foundation 2.4.0
+ path_provider_linux 2.2.1
+ path_provider_platform_interface 2.1.2
+ path_provider_windows 2.2.1 (2.3.0 available)
+ pdfx 2.8.0
+ percent_indicator 4.2.2 (4.2.3 available)
+ permission_handler 11.3.1
+ permission_handler_android 12.0.12 (12.0.13 available)
+ permission_handler_apple 9.4.5
+ permission_handler_html 0.1.3+2
+ permission_handler_platform_interface 4.2.3
+ permission_handler_windows 0.2.1
+ petitparser 6.0.2
! photo_view 0.15.0 (overridden)
+ platform 3.1.6
+ plugin_platform_interface 2.1.8
! pointer_interceptor 0.10.1+2 (overridden)
! pointer_interceptor_ios 0.10.1 (overridden)
! pointer_interceptor_platform_interface 0.10.0+1 (overridden)
! pointer_interceptor_web 0.10.2+1 (overridden)
+ provider 6.1.2
+ purchases_flutter 8.1.2 (8.1.6 available)
+ record 5.1.2
+ record_android 1.2.6
+ record_darwin 1.1.2
+ record_linux 0.7.2
+ record_platform_interface 1.1.0
+ record_web 1.1.3
+ record_windows 1.0.3
+ rfc_6901 0.2.0
+ rxdart 0.27.7 (0.28.0 available)
+ screenshot 2.5.0 (3.0.0 available)
+ share_plus 10.0.2 (10.1.1 available)
+ share_plus_platform_interface 5.0.0 (5.0.1 available)
+ shared_preferences 2.3.2
+ shared_preferences_android 2.3.2 (2.3.3 available)
+ shared_preferences_foundation 2.5.2 (2.5.3 available)
+ shared_preferences_linux 2.4.1
+ shared_preferences_platform_interface 2.4.1
+ shared_preferences_web 2.4.2
+ shared_preferences_windows 2.4.1
+ shimmer 3.0.0
+ sign_in_with_apple 6.1.2 (6.1.3 available)
+ sign_in_with_apple_platform_interface 1.1.0
+ sign_in_with_apple_web 2.1.0
+ simple_gradient_text 1.2.3 (1.3.0 available)
+ sky_engine 0.0.99 from sdk flutter
+ slider_button 2.1.0
+ sliver_tools 0.2.12
+ smooth_page_indicator 1.1.0 (1.2.0+3 available)
+ source_span 1.10.0
+ sprintf 7.0.0
+ sqflite 2.3.3+1 (2.4.0 available)
+ sqflite_common 2.5.4+3 (2.5.4+5 available)
+ stack_trace 1.11.1 (1.12.0 available)
+ stop_watch_timer 3.0.2 (3.2.1 available)
+ stream_channel 2.1.2
+ stream_transform 2.1.0
+ string_scanner 1.2.0 (1.4.0 available)
+ synchronized 3.2.0 (3.3.0+3 available)
+ term_glyph 1.2.1
+ test_api 0.7.2 (0.7.3 available)
+ text_search 1.0.1 (1.0.2 available)
+ timeago 3.6.1 (3.7.0 available)
+ tuple 2.0.2
+ tutorial_coach_mark 1.2.11 (1.2.12 available)
+ typed_data 1.4.0
+ universal_file 1.0.0
+ universal_platform 1.1.0
+ url_launcher 6.3.0 (6.3.1 available)
+ url_launcher_android 6.3.10 (6.3.13 available)
+ url_launcher_ios 6.3.1
+ url_launcher_linux 3.2.0
+ url_launcher_macos 3.2.1
+ url_launcher_platform_interface 2.3.2
+ url_launcher_web 2.3.3
+ url_launcher_windows 3.1.2 (3.1.3 available)
! uuid 4.5.1 (overridden)
+ vector_math 2.1.4
+ vibration 1.9.0 (2.0.1 available)
+ vibration_platform_interface 0.0.2
+ video_player 2.9.2
+ video_player_android 2.7.13 (2.7.16 available)
+ video_player_avfoundation 2.6.2
+ video_player_platform_interface 6.2.3
+ video_player_web 2.3.2 (2.3.3 available)
+ vm_service 14.2.5 (14.3.1 available)
+ wakelock_plus 1.2.8
+ wakelock_plus_platform_interface 1.2.1
+ web 1.1.0
+ webview_flutter 4.9.0 (4.10.0 available)
+ webview_flutter_android 3.16.7 (4.0.0 available)
+ webview_flutter_platform_interface 2.10.0
+ webview_flutter_wkwebview 3.15.0 (3.16.0 available)
+ webviewx_plus 0.5.0
! win32 5.5.1 (overridden) (5.7.1 available)
+ win32_registry 1.1.5
+ xdg_directories 1.1.0
+ xml 6.5.0
+ yaml 3.1.2
+ youtube_player_iframe 4.0.4 from git https://github.com/FlutterFlow/youtube_player_flutter.git at 4c9c39 in packages/youtube_player_iframe
+ youtube_player_iframe_web 2.0.2 (3.1.0 available)
Changed 239 dependencies!
1 package is discontinued.
78 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Analyzing dependencies
Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `11.2.0`
cloud_firestore: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
cloud_functions: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
firebase_dynamic_links: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`

CocoaPods 1.15.0 is available.
To update use: `gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.15.0

[!] CocoaPods could not find compatible versions for pod "Firebase/Messaging":
  In Podfile:
    Firebase/Messaging

    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.1.3, which depends on
      Firebase/Messaging (= 11.2.0)

CocoaPods could not find compatible versions for pod "FirebaseCore":
  In Podfile:
    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 3.6.0, which depends on
      Firebase/CoreOnly (= 11.2.0) was resolved to 11.2.0, which depends on
        FirebaseCore (= 11.2.0)

    firebase_storage (from `.symlinks/plugins/firebase_storage/ios`) was resolved to 12.3.2, which depends on
      Firebase/Storage (= 11.2.0) was resolved to 11.2.0, which depends on
        FirebaseStorage (~> 11.2.0) was resolved to 11.2.0, which depends on
          FirebaseCore (~> 11.0)

CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_storage (from `.symlinks/plugins/firebase_storage/ios`) was resolved to 12.3.2, which depends on
      Firebase/Storage (= 11.2.0) was resolved to 11.2.0, which depends on
        FirebaseStorage (~> 11.2.0) was resolved to 11.2.0, which depends on
          GTMSessionFetcher/Core (~> 3.4)

    google_sign_in_ios (from `.symlinks/plugins/google_sign_in_ios/darwin`) was resolved to 0.0.1, which depends on
      GTMSessionFetcher (>= 3.4.0) was resolved to 4.0.0, which depends on
        GTMSessionFetcher/Full (= 4.0.0) was resolved to 4.0.0, which depends on
          GTMSessionFetcher/Core (= 4.0.0)

    google_sign_in_ios (from `.symlinks/plugins/google_sign_in_ios/darwin`) was resolved to 0.0.1, which depends on
      GoogleSignIn (~> 7.1) was resolved to 7.1.0, which depends on
        GTMAppAuth (< 5.0, >= 4.1.1) was resolved to 4.1.1, which depends on
          GTMSessionFetcher/Core (< 4.0, >= 3.3)

    google_sign_in_ios (from `.symlinks/plugins/google_sign_in_ios/darwin`) was resolved to 0.0.1, which depends on
      GoogleSignIn (~> 7.1) was resolved to 7.1.0, which depends on
        GTMSessionFetcher/Core (~> 3.3)

CocoaPods could not find compatible versions for pod "nanopb":
  In Podfile:
    FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `11.2.0`) was resolved to 11.2.0, which depends on
      FirebaseFirestoreBinary (= 11.2.0) was resolved to 11.2.0, which depends on
        FirebaseFirestoreInternalBinary (= 11.2.0) was resolved to 11.2.0, which depends on
          nanopb (~> 3.30910.0)

    google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 1.0.0, which depends on
      Google-Mobile-Ads-SDK (~> 10.11.0) was resolved to 10.11.0, which depends on
        GoogleAppMeasurement (< 11.0, >= 7.0) was resolved to 7.3.0, which depends on
          nanopb (~> 2.30906.0)


Build failed :|
Step 6 script `Install pods` exited with status code 1

**Comment by Alezanello** [comment]
Hello everyone!

To help us identify the issue more efficiently, could you please share a **Bug Report Code** from your project? This will assist us in debugging the dependency issues specific to your setup

**Comment by cartworthy** [comment]
@Alezanello I have provided all of the relevant deployment errors with descriptions above. What is a "Bug Report Code"? I am not a developer so please elaborate on how I can best help you help me.

**Comment by Alezanello** [comment]
To obtain the Bug Report Code, follow these steps:

1. Open any page in your project.
2. Go to the **Widget Tree**.
3. Right-click on the **Scaffold** widget to open the menu.
4. Select **Bug Report Code** from the menu.
5. Wait for the confirmation that the code has been copied to your clipboard.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f9854979-dd46-444c-b165-fa64b0520f08/1f08f50c-e19f-49c1-90ef-06249f0f2558?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mOTg1NDk3OS1kZDQ2LTQ0NGMtYjE2NS1mYTY0YjA1MjBmMDgvMWYwOGY1MGMtZTE5Zi00OWMxLTkwZWYtMDYyNDlmMGYyNTU4IiwiaWF0IjoxNzMwMTQxMjgwLCJleHAiOjMzMzAwNzAxMjgwfQ.lAhuYVq5zc-8Est1kf-wW62qbbD_F0xXamlMe8kHH2k " alt="image.png" width="532" height="727" />

**Comment by cartworthy** [comment]
@Alezanello Does this look right?

ITFfhvHlz4xOocsA7q6IYPlsiiEWHDIcTIMziNZ+exUbfaL1BuwcOsz7VBRDTcvhaVNcPlejoE010639ktrmUccrFz6qbNlHyZdQFgzke2iQM4yUBpCWX3FtN51PIGKw5ruR2BJNPftoWF0jw0OYG+ysYBLDFOu/Zwh9f6PHaOI=

**Comment by Alezanello** [comment]
Perfect!!<br><br>Yes this is it!<br><br>Thank you!

**Comment by Alezanello** [comment]
@cartworthy <br><br>If I have this packages is going to throw error:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/569cb799-cd5b-4fa3-bffc-40ad8cc913c7/ada080f3-7a08-4de9-a3c9-fed39145d999?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81NjljYjc5OS1jZDViLTRmYTMtYmZmYy00MGFkOGNjOTEzYzcvYWRhMDgwZjMtN2EwOC00ZGU5LWEzYzktZmVkMzkxNDVkOTk5IiwiaWF0IjoxNzMwMTQzNTE2LCJleHAiOjMzMzAwNzAzNTE2fQ.cmfMZV-f8gznfhS_Co9KtNwf4QiPTOWrFza8IbOHkMg " alt="image.png" width="1024" height="501" />

If I downgrade camerawesome to 1.1.0 and leave carousel_slider in 5.0.0 it should compile without any issues:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/deae4c1f-229d-46fb-9ec0-ec6461f168fa/a39a6b58-2f47-45c4-be49-832dd2e6d12e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZWFlNGMxZi0yMjlkLTQ2ZmItOWVjMC1lYzY0NjFmMTY4ZmEvYTM5YTZiNTgtMmY0Ny00NWM0LWJlNDktODMyZGQyZTZkMTJlIiwiaWF0IjoxNzMwMTQzNTE2LCJleHAiOjMzMzAwNzAzNTE2fQ.-ccR3tiw6wFnL-9a_qf1SsOp80l8nOLDWc-sjKbDpHg " alt="image.png" width="767" height="616" />

**Comment by cartworthy** [comment]
@Alezanello I'm pretty sure I've tried that combination last week and it still didn't work but I just attempted to build it again just to get you the exact errors but building timed out after about an hour:

<img width="381" alt="Screenshot 2024-10-28 at 1 36 47 PM" src="https://github.com/user-attachments/assets/eabc650d-051b-4de5-a6d2-34db5b5da8c6">

**Comment by cartworthy** [comment]
@Alezanello Here's the error. Second build failed with this error.

<img width="711" alt="Screenshot 2024-10-28 at 3 43 19 PM" src="https://github.com/user-attachments/assets/f5da02fd-d1c0-4888-8b5d-c7a8de36c3ae">

The code has a green check like it's compiling correctly, but there are red marks throughout the code for padding, alignment, and buttons:

<img width="1047" alt="Screenshot 2024-10-28 at 3 46 24 PM" src="https://github.com/user-attachments/assets/a79a06bc-9d2c-406a-a8ad-a12c463b1694">

I hired a developer to build this. I'm hoping there is some solution here that does not require hiring another developer to fix this code just because FlutterFlow pushed an update. 

Also — I'm a bit disappointed that because FlutterFlow pushed an "update" I have to downgrade packages in my app. That doesn't seem right, does it? 

Ideally I would like to be using more recent version of the packages in my app.

**Comment by mtruebe** [comment]
Hi, also having the same issue "ios/Runner/AppDelegate.swift uses the deprecated @UlApplication Main attribute, updating."

**Comment by Alezanello** [comment]
Hello @cartworthy,

First, I apologize for the issues you're experiencing with your project. We previously notified users about the update to Flutter version 3.24.2, which also brought updates to several SDK packages and dependencies used in projects.

In your project, you’re using the Carousel Slider package in the "Buy Points," "Profile," and "Image Loader" pages. This package now requires an update to version 5.0.0 to remain compatible with other FlutterFlow widgets. However, updating the Carousel Slider package also requires updating the `rxdart` package, which the Carousel depends on. Unfortunately, the other package you are implementing requires an older version of `rxdart`, creating a compatibility issue.

To resolve this, you have two options:

1. **Remove the Carousel Slider** from your project and replace it with another component, such as PageView, to achieve a similar functionality.
2. **Update the custom widget code** to ensure compatibility with Carousel version 5.0.0, including adjustments for any dependencies.

Let us know if you need further assistance with implementing these changes, and we’ll be happy to help.

**Comment by cartworthy** [comment]
@Alezanello Words can not describe my frustration and anger in this situation. I appreciate your patience and thoughtful reply, but you're giving me these two options:

1. Spend my time re-designing and removing widgets that are native features provided by FlutterFlow — which will likely result in sacrifices of the UX.
2. Pay developers to DOWNGRADE a core custom-code feature in my app to an OLDER version — which I have no idea what that will cost or other barriers may arise from that.

My frustration is that this is because of a breaking "update" from FlutterFlow that I did not consent to and I am unable to go back from. None of the new features FlutterFlow is pushing are of any use for me. I just want to know that what I'm investing my time into building on the platform is stable and not going to be broken because of so-called "updates" that are forced upon me from FlutterFlow.

You "notified users" the update was coming. That's the most frustrating part. So what? What was I supposed to do with that information? Brace myself for impact?! I don't remember being given any options to decline this update. It was involuntary and forced upon on me.

I want my app to just continue working once it's working. I've been paying for FlutterFlow Pro for over 2 years and this is by far my most disappointing experience with the platform. I would like to continue loving the platform, but this is going to change the way I tell others about it.

If there is any other support you can offer, please let me know. Are your developers able to fix my camera feature for me? Free months off my subscription? Any other creative solutions for possibly fixing my app so I can continue working on it after over a week of down-time?

**Comment by leighajarett** [comment]
Hi there! So sorry you're experiencing this issue. I totally understand your frustration and we're working on a better solution for opting into these sort of updates in the future - it's a hard thing to support but we know it's super important to everyone to prevent issues like this. Can you please send me an email leigha@flutterflow.io so we can discuss how we can help with your specific custom code? Thanks so much!
