### ISSUE TITLE
FlutterFlow Windows Application > Local Run: Error accessing Flutter SDK version (Reproducible where Widows Local Username has a space in it)

### ISSUE THREAD

**Issue by aminnayel** [FlutterFlow/flutterflow-issues#4958]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://github.com/user-attachments/assets/c4e7146a-b2d8-4d92-9936-05c61f79aa6e)

### Expected Behavior

Having Flutter installed correctly and Local Run working properly

### Steps to Reproduce

This is reproducible only when the Widows Local Username has a space in it (example: C:\Users\Fire Dragon).

The issue doesn't occur with Windows accounts where the Local Username is one word.

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Visual documentation

![image](https://github.com/user-attachments/assets/b50c0a6d-138f-45ab-a1cf-c41d690c8b0c)

### Environment

```markdown
- FlutterFlow version: N/A 
- Platform: N/A
- Browser name and version: N/A
- Operating system and version affected: Windows, Latest
```

**Comment by Alezanello** [comment]
Thank you for bringing this to our attention! I’ve confirmed the issue and will escalate it to our engineering team for further review. <br><br>We’ll work on resolving this as quickly as possible!

**Comment by azharbinanwar** [comment]
Any news?

**Comment by sbis04** [comment]
This issue should be fixed in this week's release!

**Comment by aurelio-remy** [comment]
Hello, I'm experiencing the same issue and my user's name doesn't have a whitespace.

**Comment by KomalPatel-github** [comment]
@sbis04 I still face this issue. Probably because I had manually setup flutter SDK using android studio and flutter environment myself.

Also I don't have any whitespaces in my Username

I followed the instructions for uninstalling as given by Flutter documentation https://docs.flutter.dev/install/uninstall and then restarting the app and that fixed it for me
