### ISSUE TITLE
Login button becomes unresponsive after an unsuccessful login due to unverified email id 

### ISSUE THREAD

**Issue by x-crimson** [FlutterFlow/flutterflow-issues#4995]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

my login page does the following action, it validates the form, it then logs the user in and checks if the email is verified or not, then according to the condition if verified, redirects to the homepage but if unverified, logs out and tells the user to verify and log in by a Snackbar popup. now the problem is below:
whenever i am trying to log in with an unverified email id , after showing me the error snackbar message the login button stops working , I have to then restart the app by clearing it from background, but the form is completely working ok in test mode and in build mode , but in apk installed in an android this button unresponsive thing is happening. 

### Expected Behavior

the app should allow the user to log in without making the button unresponsive, 

the button is only becoming unresponsive in an apk installed in an device, but its working ok in Test Mode and build mode of flutter flow

### Steps to Reproduce

1. download the apk and install it on a physical android device (I don't know in emulator it wii show the bug or not)
2. create an account in signup page .
3. don't verify the email sent to your email id
4. now try to login using the unverified email and password
5. It will show the "email is not verified" message .
6. now you can see that when you tap again on login button nothing is happening, even the form validation is not working.
7. even now if you verify your email id and try to login its not responding.
8. the only way its will respond is by restarting the app, clear the app from recent apps and restart it, now the button will work.   

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CjcnfsMxOsdtb7s/tbfpVhikXQ0wkRYERiexDSkkcDZPOD7AQP8nRP1dUOdOkTEFHe1mgq3MX/MrliIX2UvE7HyqVbKZEzYd+dA3iIUe6WpCmO663b2tQI+NYCWae4cOs3SNDIstiLFYG1DuuB+/LcHHDNKbYNVgZGuaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/ba92e51e-cd6a-487a-a7a2-a62c33b354a4

### Environment

```markdown
- FlutterFlow version: latest
- Platform:android
- Browser name and version:
- Operating system and version affected: android and almost all version
```

**Comment by Alezanello** [comment]
Hello!!

If you have actions set to occur after logout and the logout action keeps the user on the same page, simply disable the "Navigate Automatically" option. That should resolve the issue!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9bb07ce9-8c2e-4455-9d48-5a2ef0d6a96c/0c277453-80ac-416e-bfe5-40098f385546?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85YmIwN2NlOS04YzJlLTQ0NTUtOWQ0OC01YTJlZjBkNmE5NmMvMGMyNzc0NTMtODBhYy00MTZlLWJmZTUtNDAwOThmMzg1NTQ2IiwiaWF0IjoxNzMyNzk1Njc4LCJleHAiOjMzMzAzMzU1Njc4fQ.3kXlYhFDtrLSRrLXnBqk10J3zZNq53W9Lld4rlWYrIM " alt="image.png" width="1083" height="770" />

**Comment by x-crimson** [comment]
No its still has the same problem, Still the button is not working after unsuccessful login due to unverified email.

**Comment by x-crimson** [comment]
I have tried all possible combinations and fixes, but the bug is still there, it only showing in installed versions on phones, its not showing on Test mode or build mode.

**Comment by Alezanello** [comment]
Try to set the Logout at the end of the action flow, maybe is trying to perform actions AFTER the Logout condition

**Comment by x-crimson** [comment]
Recently tried this one also, same problem. You can check my actions flow.

**Comment by Alezanello** [comment]
I have a flow that works perfectly as follows:

1. **Validate the form**
2. **Log in**
3. **Check if the email is verified**

If the email is **not verified**, the flow proceeds like this:

1. Display a **confirmation dialog** informing the user that the email isn't verified and asking if they'd like to receive a new verification email.
2. If the user clicks **Confirm**, send a **new email verification link**.
3. Show an **alert dialog** confirming that the verification email has been sent.
4. **Log out**, ensuring that the **Navigate Automatically** option is disabled.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c26f2460-7884-430b-aa73-9aad652219c7/045efa8d-84cc-4a9b-acb3-4297b67deb50?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jMjZmMjQ2MC03ODg0LTQzMGItYWE3My05YWFkNjUyMjE5YzcvMDQ1ZWZhOGQtODRjYy00YTliLWFjYjMtNDI5N2I2N2RlYjUwIiwiaWF0IjoxNzMzNDkyMzYyLCJleHAiOjMzMzA0MDUyMzYyfQ.RNugshTb7L5UCQz4UjBcNB7a9L3axSvTksJ6MImxW7c " alt="image.png" width="398" data-linear-height="727" />

**Comment by x-crimson** [comment]
it works completely fine when tested in Test mode or Build mode, But after I download the apk file and install it , then when I try to login with an unverified email id then it shows the dialogue of email id not verified, please verify and then logs the user out , Now when the user is logged out the button stops working , It doesn't even validate the form fields.

to fix this there is only one solution, that is to restart the app. 

because I have tried switching from login page to signup page back and forth so that it may refresh the page and the button should work , but once an unverified email login is attempted the button totally stops working until you restart the app. 

the problem I have mentioned only shows up in an app which is installed in a device (Android) . But if you will run my app in test or build mode then it will work smoothly and perfectly without button becoming unresponsive.

**Comment by x-crimson** [comment]
Hello, Thank you for sharing your login page Action flow, I have implemented it and the bug is resolved, I think the bug appeared due to the snack bar I used  as an alert for " email not verified" message.

now its resolved.

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
