### ISSUE TITLE
We can't open links from the HTML Viewer widget

### ISSUE THREAD

**Issue by kicsijohn** [FlutterFlow/flutterflow-issues#501]
## Expected behavior (required)
If I click on a link in the HTML viewer widget, the app opens the link

## Current behavior (required)
The widget doesn't recognize my tap

## To Reproduce (required)
1. Create new page
2. Add HTML viewer widget
3. add a hyperlink: 
`<b><a href="https://flutterflow.io">Flutterflow HTML Viewer</a></b>`
4. test on device (I won't tested in test mode)
5. Observe that link doesn't opens

### Bug Report Code (required, generate by right clicking inside Widget Tree and clicking "Get Bug Report Code")
IT4gjufqyIt1m8ta1c7ubu9aoCcWQ0x/bJc0sNxhcwwbCYDuBIYiac/7N1ZtQs+9TwhPKEWIikADw+jSjezpVPJdFyqsbohHyM9AcRaXXlHkEuzyT+3IHDUHZbsSXTTm

## Context (required)
I want to place hyperlinks in a long HTML text

## Your environment
* Version of FlutterFlow used:  1.1.43
* Platform (e.g. Web, MacOS Desktop): iPhone
* Operating system and version (desktop or mobile): ios

**Comment by shelpert** [comment]
Hello,

This bug has been fixed and will be available in a future release!

**Comment by siddharthshah3030** [comment]
This issue is still happening for below HTML in HTMLView component
I am using flutterflow v4.0.2

```
<ul><li><a rel="noopener noreferrer" href="https://www.crfb.org/press-releases" target="_blank">https://www.crfb.org/press-releases</a></li></ul>
```

**Comment by awarsing** [comment]
Using HtmlView widget, FlutterFlow v3.10.4

### Expected Behaviour
Properly rendered HTML with clickable links

### In Practice Experience
HTML renders correctly using various methods, no clickable links in any method

### Testing Examples
The first paragraph in the image below is text from the API response (which is from the default WordPress API), into a custom function that removes all HTML tags except `<p>` tags.

The second paragraph in the image below is the same text from the API response, into a custom function that removes `<iframe>` and empty `<p>` tags.

The third paragraph in the image below is from pasting test text direct into the HtmlView box.

Only the third example is clickable. (I also took the test output from the custom function and pasted that into the HtmlView box, and the links were clickable.)

I have tried setting the return value from the custom function as a string and JSON, both fail to produce a clickable link.

I tried the Text Combination widget and added this code to the first text entry, then the return value from the same custom functions as above, and it renders, but no clickable links (see second image below):
`<head> <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet"> <style> h3 { font-family: 'Open Sans', sans-serif; font-size: 80px; font-weight: bold; } p { font-family: 'Open Sans', sans-serif; font-size: 16px; line-height: 1; } </style></head> `

![screenshot - 000246](https://github.com/FlutterFlow/flutterflow-issues/assets/46063907/1f1de8c9-21ee-4d6c-8432-19feb043e0f6)
![screenshot - 000247](https://github.com/FlutterFlow/flutterflow-issues/assets/46063907/90e9f872-6a6e-4b3c-aee2-3433d6328409)
