### ISSUE TITLE
Tooltip doesn't show text on Android v.14

### ISSUE THREAD

**Issue by JuraskiBart** [FlutterFlow/flutterflow-issues#5141]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After tapping on a tooltip on Android 14 device, it doesn't show anything: any text nor empty tooltip

### Expected Behavior

After tapping a info button should show tooltip with a text defined in FlutterFlow project

### Steps to Reproduce

1. Go to Google Play & download test app: https://play.google.com/store/apps/details?id=inis.polecamprodukt
2. Login as a test user: 
- L: b.jurkiewicz+testaccount@inis.pl
- P: 123456
3. Go to "Rozliczenia" page
4. Tap on any info button -> it should show a tooltip

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48iMmA8ZN1xMtE+KX6YMEwnmEUQls7RK83luptbEg8J5jLPOx/fMnRalVUOLymT1ZYe2KGkmYX/MmPvYaeOMBcBxydRb5qwpFIewyUTkmVbpubC5S3b3ZAGcBVIECw15izuCMkAPdZcnAlwGGABt6REwnYCbrGNVc/OeaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/1e402fd0-fd25-4fd2-a675-aa43bab88781)

### Environment

```markdown
- FlutterFlow version: v5.0.15+ released December 17, 2024 + Flutter version is 3.24.2
- Platform: Samsung Galaxy A52
- Browser name and version: Google Play mobile app
- Operating system and version affected: android 14 / One UI 6.1
```

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate this issue on a new blank project. Interestingly, I tested it on the exact same real device—a Samsung A52 running Android 14 with One UI 6.1—and everything seems to be working as expected.

Here’s the project I used for testing:

[https://app.flutterflow.io/project/qa-3318-nygoum](https://app.flutterflow.io/project/qa-3318-nygoum)

You can clone it and compile it!

[Video Tooltip.mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/070ad70c-c6d1-4421-b069-97ad22fcab7c/afcb8cf4-0d58-4772-9658-fb680378780b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wNzBhZDcwYy1jNmQxLTQ0MjEtYjA2OS05N2FkMjJmY2FiN2MvYWZjYjhjZjQtMGQ1OC00NzcyLTk2NTgtZmI2ODAzNzg3ODBiIiwiaWF0IjoxNzM0NjM1NzM0LCJleHAiOjMzMzA1MTk1NzM0fQ.YM0WNWjLlysaMC6xe-5EVILRIVJxeL_mu8BaGu0YuNM)

**Comment by JuraskiBart** [comment]
Resolved! I was adding iconButtons to the tooltip widges - and tis combination doesn't work.
When I changed to icon it works as planned.
Thanks a lot Alezanello for your time and engagement!

**Comment by DanLika** [comment]
I tested your app and it works. But in my case, it doesn't work. I tried with text and component. And if I use component text isn't showing, but icons yes. I still can't see the text if I use text, not component. The problem isn't in font or color. 
However I have enabled the Canvas Kit and WebPublish features, and maybe this is why I can't see the text in the toolkit. Now, I'm not able to test the same in your project because I get a grey screen on settings from FlutterFlow.
