### ISSUE TITLE
Mobile deployment on Apple not working anymore

### ISSUE THREAD

**Issue by Phobie53** [FlutterFlow/flutterflow-issues#515]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

When I use the automatic publish on store feature, I expect my app to be published to App Store and Google Play Store.

## Current behavior (required)

When I deploy on App Store, the app is in "building" status, and a few seconds later I got a red toast "Checking build status failed :/".
The app doesn't load on App Store.

## To Reproduce (required)

1. Go to the mobile deployment section
2. Simply press "Deploy to App Store" button
3. Wait or click "Check build status" a few seconds later

## Context (required)

Just trying to deploy on App Store with the deploy tool in FlutterFlow. I did it like 50 times already and was working well until two weeks ago. I didn't changed any key, and all my key are up to date in my AppStore Developer Page (they expire in 6 months).

I am not alone, 3 or 4 threads in the community site are referencing this issue :
https://community.flutterflow.io/c/discuss-and-get-help/publish-appstore-error
https://community.flutterflow.io/c/discuss-and-get-help/fix-ios-build-error
https://community.flutterflow.io/c/discuss-and-get-help/codemagic-deploy-problem

I also got two console error when I refresh the status of my build in the FlutterFlow app : 
![image](https://user-images.githubusercontent.com/6780510/220402918-53d77198-5cc2-4147-aa99-a10e1f57f393.png)

And this 500 error in details : 
![image](https://user-images.githubusercontent.com/6780510/220403033-cdd2ffc8-0720-4a1d-99aa-8fe24bb5c837.png)

## Your environment

* Version of FlutterFlow used: v3.1 released feb. 17
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome 110.0.5481.104
* Operating system and version (desktop or mobile): Windows 11

**Comment by katherineqian** [comment]
Hi @Phobie53, 

This may be a duplicate of issue #124, since it is also a problem with deploying to the iOS App Store. Can you please check out the comments and instructions in that issue, and see if this solves your problem?

Otherwise, please provide us with a bug report code (generated from anywhere in your project where you are experiencing this issue), so we can help assess. Thanks!

**Comment by EnzoPHF** [comment]
I don't think it's duplicate since as I said I don't have the line : "FAILED (VIEW LOGS)"
So all the logs I got are in this ticket. 

For the bug report code, I will once I will be able to subscribe again to FlutterFlow Pro Plan, but the payment is broken and stuck in an infinite loading so I can't subscribe anymore (https://community.flutterflow.io/c/discuss-and-get-help/after-canceling-pro-can-t-subscribe-again)

**Comment by Phobie53** [comment]
I don't think it's duplicate since as I said I don't have the line : "FAILED (VIEW LOGS)"
So all the logs I got are in this ticket.

For the bug report code, I will once I will be able to subscribe again to FlutterFlow Pro Plan, but the payment is broken and stuck in an infinite loading so I can't subscribe anymore (https://community.flutterflow.io/c/discuss-and-get-help/after-canceling-pro-can-t-subscribe-again)

**Comment by katherineqian** [comment]
You should still be able to open your project, go to the widget tree, right click and select Generate Bug Report Code on a free plan.

I’m happy to look into the billing issue, however, we cannot assess the error you’re encountering without the bug report code.

**Comment by Phobie53** [comment]
Is that the complete log you need with the bug report ?
`ITEehvLq+cl1pbxA+pDXYexFpwMwJ0QlUIInj+0bWRMhfevnPJkxPcz8XEtLYteYeX5ceGH+pEUK/92Oi+OeDcEqCwqeUaJMzZRXQQmUVmSlWr6IOpGCW3wmPNFnG3Kj58O3miRAC7FtdU4T7F2IfPCrG3qCf9qOYwx5e6fDbOY=`

**Comment by katherineqian** [comment]
Can you please try to deploy it again and see if it works? I checked, and a fix to this issue was released since the time you (and the other users on Community) reported this bug. It should be resolved.

**Comment by Phobie53** [comment]
Once I am able to subscribe to the Pro Plan again I will give it a try.

**Comment by Phobie53** [comment]
This issue is still on my project. The last bug report code is on the previous message

**Comment by katherineqian** [comment]
Hi! It says your last successful deploy was on Dec 28, 2022. So I can understand the situation correctly, did you try pressing "Deploy to App Store" again?

**Comment by Phobie53** [comment]
Sure, since this date I can't release new versions of my app on the AppStore.
The process and the error I have are able.

**Comment by agreaves** [comment]
Hi @Phobie53, thanks for the bug report and apologies for the inconvenience! At last I've been able to identify the error which we were experiencing when retrieving the build failure logs. This will be deployed later today, but in the meantime the proper logs have been populated for your project.

Closing this issue for now, as the build failure itself is unrelated to this (from a brief glance I'm guessing it's likely due to one of the custom pubspec dependencies used).
