### ISSUE TITLE
Component state with multiple widget do not work

### ISSUE THREAD

**Issue by polenvinagre** [FlutterFlow/flutterflow-issues#518]
I have a componente with two Text Field input box. I can not access my second Input Box state. It only allows me to select the first widget state on the componente.

## Expected behavior (required)
Select the second widget state on a componente.

## Current behavior (required)
It only allows me to select the first widget state on the componente.

## To Reproduce (required)
1. Create new Componente_A with: Text_Field_1 and Text_Field_2
2. Add this Componente_A to a page
3. Add a Text and Set from Variable to Widget State > Componente_A > Text_Field_2 
4. Observe that select is only to Text_Field_1

## Your environment
* Version of FlutterFlow used:  v3.1-Flutter 3.7.3
* Platform (Web): 
* Browser name and version: Chrome Versão 110.0.5481.104 (Compilação oficial) (64 bits)
* Operating system and version (desktop): Windows 10 Home

**Comment by organicnz** [comment]
Hi @polenvinagre. Thank you for adding this issue, mate 🙂

Yeah, I could reproduce this issue. Looks like a bug :)

![image](https://user-images.githubusercontent.com/4765090/221113729-81791445-37bf-4149-a425-8cdca2809d62.png)

![image](https://user-images.githubusercontent.com/4765090/221113773-aef2c832-637d-447a-a9e9-49bb1bde0fc7.png)

**Comment by KamyMouss** [comment]
Having this problem with ChoiceChips as well, as well as any custom component created.

**Comment by wenkaifan0720** [comment]
Hi @polenvinagre. This should be fixed in our next update. Thank you for reporting it.

**Comment by polenvinagre** [comment]
The update released today March 2, 2023. Did NOT solve the bug.
Please reopen the ticket.

**Comment by wenkaifan0720** [comment]
Oh, I meant the next update after todays. The fix has just been merged today and is not live yet.
