### ISSUE TITLE
Enums in a library that is inside another library are causing undefined error

### ISSUE THREAD

**Issue by TimNjeru** [FlutterFlow/flutterflow-issues#5312]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When building a project lets call it TEST PROJECT that has a library called TEST LIB2 which has a library called TEST LIB 1 and TEST LIB 1 has an enum, we get an undefined error like this this one: lib/backend/schema/enums/enums.dart:18:11: Error: Undefined name 'testlib1_3j96z2_enums'.
    case (testlib1_3j96z2_enums.GoodFriends):

### Expected Behavior

I was expecting the project to build normally.

### Steps to Reproduce

1. Create a Project
2. Create Library 1
3. Create Library 2
4. Add enums to Library 2
5. Add Library 2 to Library 1
6. Add Library 1 to Project
7. Try to run the app

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sz/Hqx89PvsdG1ZDuc8dB/TkvJls3ar88scpCbw4bIYj2P4lzY876P1BBZ9O8dHxUe2e2p14C0uj4i+zxIfI3OQWZQNlj/qhqWjyUcE2mWrGTF7mSOEBSL9tXBW7H5p6RsxFCCMVvSFoM6mGqf+/KSh7qNb7IPGo4Sq/LZO4=

### Visual documentation

![Image](https://github.com/user-attachments/assets/1c087b5b-8671-4f70-9e97-3f95e05c8330)

### Environment

```markdown
- FlutterFlow version: v5.0.26 

- Platform: Web
- Browser name and version: Edge/ Chrome
- Operating system and version affected: Windows 11
```

### Additional Information

None

**Comment by Alezanello** [comment]
Hello!

You’re absolutely right—this is causing significant issues. I’ll escalate this to the engineering team right away. Thank you so much for bringing this to our attention!

**Comment by TimNjeru** [comment]
Hello @Alezanello , is there an indicate date of getting an update for this?

**Comment by john-chen-flutterflow** [comment]
Hi @TimNjeru ,

I pushed a fix for this last week and it should be on its way to prod.

Thanks,

John

**Comment by TimNjeru** [comment]
Who is sleeping on his job then? Why are we not getting an update?

**Comment by jonl-percsolutions-com** [comment]
Still seeing this in 5.2.0 released Feb 19th. @Alezanello please take a look!

**Comment by aemelyanovff** [comment]
@jonl-percsolutions-com Please reply with a bug report code.
