### ISSUE TITLE
I can't log in to the desktop version - [WINDOWS - BRAZIL ONLY]

### ISSUE THREAD

**Issue by wrogerio** [FlutterFlow/flutterflow-issues#5395]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When authenticating with the Google account, there is an internal error in the system and when I try to use email and password, there is a validation error, even though I have already reset the password about 10 times.

### Expected Behavior

LogIn with google successfuly

### Steps to Reproduce

1 . LogIn with Google Account
2. Authorize by web windows
3. Error Internal

![Image](https://github.com/user-attachments/assets/9d226bc0-dd8c-4091-89e4-5b622697a284)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

with out code

### Visual documentation

![Image](https://github.com/user-attachments/assets/434efb0f-995e-4518-b33a-d03667020593)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
**Hello!**

I wasn't able to replicate this issue on my end. If you're still experiencing it, please reach out to our support team via the in-app chat (web only) or email us at **support@flutterflow.io** for further assistance.

**Comment by Rafamach56** [comment]
same error here

**Comment by samirpegado** [comment]
same error here. did anyone find a solution?

**Comment by tudotubestudio** [comment]
same here in Brazil

**Comment by zonaro** [comment]
Same error here

**Comment by rzambroni** [comment]
Hey everyone,

We wanted to update you that our team is actively investigating this issue, as it appears to be affecting a significant number of users in Brazil. Our initial suspicion is that it may be related to a specific Brazilian ISP, but this has not been confirmed yet.

We’ll share further updates here as we learn more. Thanks for your patience!

**Comment by jsalvadorf** [comment]
I am experiencing the same error. And I'm also from Brazil.
This happens only on the windows desktop aplication, exactly as described by @wrogerio.

Sign in with Google > went through Google auth and reach "Credentials successfully verified." but the app doesnt go further "Error: An internal error has occurred."

Sign with email and password > Signing in through here returns "Incorrect email or password. Please double check and try again."


I tried erasing firebase authentication cache /uninstalling flutterflow several times, without success.
![Image](https://github.com/user-attachments/assets/cbef3406-7dd4-4cff-b6a3-09adc9ad7993)

**Comment by renanolidev** [comment]
Pessoal do brasil com problema de login. Baixem urban vpn (é gratis, loguem no proprio brasil, está funcionando o flutterflow)

**Comment by jsalvadorf** [comment]
As suggested by @renanolidev I changed vpn and google auth worked again.

**Comment by zonaro** [comment]
It is back for me, with and without VPN

**Comment by sbis04** [comment]
> It is back for me, with and without VPN

Glad to hear that! We’re still investigating the root cause of this issue — apologies for the inconvenience. Could others also test and confirm if it’s resolved on their end?

**Comment by samirpegado** [comment]
> > It is back for me, with and without VPN
> 
> Glad to hear that! We’re still investigating the root cause of this issue — apologies for the inconvenience. Could others also test and confirm if it’s resolved on their end?

this issue happened again here as well.

**Comment by evertone2** [comment]
Unfortunately for me is still not working.. ( test made right now, February 15 - 10:00 Brasil ( GMT -3)

**Comment by samirpegado** [comment]
Still not working.. February 17 - 10:19 Brasil ( GMT -3)

**Comment by syg-eliseu** [comment]
Same error

**Comment by evertone2** [comment]
hello. Any news about ? I really need the local app..

**Comment by sbis04** [comment]
Anyone who is still facing the issue, can you try out a VPN solution to set the location to a different country, then give it a try? Let me know if the authentication then works for you.

From our initial understanding, the issue seems to be related to some specific ISPs in Brazil, we are still unsure why this issue persists but are actively looking into it.

**Comment by evertone2** [comment]
solution: first I have to connect through VPN ( on Netherlands). Then after this I can log in, and even not using VPN anymore it works well. So for me its solved, but its necessary to make one first log in from another place.

thanks for the support.

**Comment by JoaoVtrxx** [comment]
Even with vpn i am still facing the problem

**Comment by JoaoVtrxx** [comment]
After restarting my computer and connecting to the VPN again, the issue is now resolved. My previous comment was incorrect. Thanks!

**Comment by jsalvadorf** [comment]
Today I was able to login without VPN. 
But I can't tell for sure this issue is gone.

Edit: Issue persists. I am currently only able to login in the desktop app combining google authentication + VPN.

**Comment by Rafamach56** [comment]
login over vpn does not able anymore

**Comment by htsnet** [comment]
I am from Brazil. Same issue.
Then, reading this post, I activated my VPN to EUA and it worked. I am logged in.

**Comment by andersonrocha** [comment]
I am facing the same issue in BRAZIL. When I enable the VPN to the USA, it works normally. Any estimated time for a fix?

**Comment by evertone2** [comment]
Hello
Again with the problem in Brazil. To logging in its necessary use VPN ( in my case I used Netherlands).

**Comment by zonaro** [comment]
In the last week it happened a few times. sometimes it entered without VPN, sometimes only with VPN

**Comment by sbis04** [comment]
Did anyone try out the solution Cristiano mentioned here: https://community.flutterflow.io/ask-the-community/post/an-internal-error-has-occurred-when-logging-into-flutterflow-desktop-0jlj7QJoxxJPkTo#replies? Let us know if that works for anyone.

**Comment by jsalvadorf** [comment]
> Did anyone try out the solution Cristiano mentioned here: https://community.flutterflow.io/ask-the-community/post/an-internal-error-has-occurred-when-logging-into-flutterflow-desktop-0jlj7QJoxxJPkTo#replies? Let us know if that works for anyone.

A bit late on this but the issue seems fixed using Google DNS on Windows as in the post linked by @sbis04. 
No VPN needed, also could login either using email and password or google authentication.

Thank you!

**Comment by sbis04** [comment]
Thanks everyone, for testing various workarounds and solutions! 🙏🏻 
Closing this issue since there's no actionable item from the FlutterFlow side.
