### ISSUE TITLE
RadioButton widget: text overflow

### ISSUE THREAD

**Issue by Alexandre-Lemyre** [FlutterFlow/flutterflow-issues#550]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

The text overflows when using the RadioButton widget. 
See the following threads for reference:
https://community.flutterflow.io/c/discuss-and-get-help/radio-button-text-overflow
https://community.flutterflow.io/c/discuss-and-get-help/radio-button-text-wrapping

### Expected Behavior

There should be a way to wrap the text. 

### Steps To Reproduce

Insert a RadioButton widget anywhere and write more than one line on one of the option.

### Bug Report Code

N/A

### Context

This widget is problematic as soon as you have an option that is longer than the user's screen's width. 

### Additional info

N/A

### Environment

```markdown
Chrome, windows 11, Flutter 3.7.3
```

**Comment by hariprasadms** [comment]
Hi @Alexandre-Lemyre  - This is not bug. This can be a feature request. This can be achieved using checkbox with text widgets combinations. Below is the quick sample I have created. 

![image](https://user-images.githubusercontent.com/17435678/221929841-7a403741-1e31-4f28-8107-c3274ce29085.png)

**Comment by Alexandre-Lemyre** [comment]
Hi.

I do not understanding how a feature that is lacking and makes a widget unusable in most use cases is not a "bug".
Does the FF team consider that text overflow on a RadioButton widget is an expected behavior?

I made a feature request.

Thank you for your time.

**Comment by mellunar** [comment]
> Hi @Alexandre-Lemyre - This is not bug. This can be a feature request. This can be achieved using checkbox with text widgets combinations. Below is the quick sample I have created.

That is a workaround to an issue that is in fact a bug.

**Comment by mellunar** [comment]
I would also appreciate if this issue were solved

**Comment by katherineqian** [comment]
Hi all, I'm happy to take a look at this. I'll go ahead and mark this request/issue as confirmed so it won't go stale.

**Comment by chandrasekhar3279** [comment]
radio button text getting overflow issue not yet fixed,?could you please update me on the resolution?,i need eaxct solution for radio text with full of my content?
