### ISSUE TITLE
'SubscriptionPeriod' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by itsstevenliu** [FlutterFlow/flutterflow-issues#5635]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since updating to the **latest MacOS 15.4 (24E248) and latest Xcode**.

getting this error launching app: Swift Compiler Error (Xcode): 'SubscriptionPeriod' is ambiguous for type lookup in this context /Users/stevenliu/Library/Application%20Support/io.flutterflow.prod.mac/voice_f_i_t/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProduct+HybridAdditions.swift:95:50

### Expected Behavior

Should be able to run local run on iOS simulator fine when RevenueCat is enabled

### Steps to Reproduce

1. Create project
2. Enable revenuecat
3. Local run iOS simulator

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4szcmA5ZV2pbxd+KrTbcdB/T0sQlh9ao0SscsZbw4bB4zqPLJ/OszSUE5uTdO6TGlhHFmGoE4x+fTshYbpM/JfJRasbYQ7zJNqTgryJHq8RpStO7u7OGskPNxjI3a45sCg3CJQIslZLUFl21+mIe+XTjPBJ5u/Zwh9f6PHaOI=

### Visual documentation

Swift Compiler Error (Xcode): 'SubscriptionPeriod' is ambiguous for type lookup in this context
/Users/stevenliu/Library/Application%20Support/io.flutterflow.prod.mac/voice_f_i_t/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProduct+HybridAdditions.swift:95:50

### Environment

```markdown
- FlutterFlow version: 3.27.3
- Platform: MacOS
- Browser name and version: Chrome Version 134.0.6998.166
- Operating system and version affected: MacOS 15.4 (24E248)
```

### Additional Information

*No response*

**Comment by nvimalraj** [comment]
Yes same error for me as well after upgrading to 18.4 ios simulator

**Comment by UNTITLEDPROJEKT** [comment]
> Yes same error for me as well after upgrading to 18.4 ios simulator

Update your purchases_flutter and purchases_ui_flutter to 8.7.0 on pubspec.yaml and 
on terminal, navigate to /ios and run 
`rm Podfile.lock`
`rm -rf Pods`

then run 
`flutter clean` and `flutter pub get`. 
next, install pods on /ios using 
`pod install --repo-update`
not `pod install`. 

make sure minimum target is set to ios 15.0 on Podfile!!! (not sure but purchases_ui_flutter requires 15.0 minimum)

**Comment by zappyle** [comment]
Getting the same error as well since updating the simulator to 18.4

**Comment by simone142** [comment]
Same. I was able to test my app in the iOS 18.4 Simulator with your solution @UNTITLEDPROJEKT , however I always get this error message from RevenueCat:

```
flutter: Error loading offerings info: PlatformException(23, There is an issue with your configuration. Check the underlying error for more details. There's a problem with your configuration. None of the products registered in the RevenueCat dashboard could be fetched from App Store Connect (or the StoreKit Configuration file if one is being used). 
More information: https://rev.cat/why-are-offerings-empty, {code: 23, readable_error_code: CONFIGURATION_ERROR, message: There is an issue with your configuration. Check the underlying error for more details. There's a problem with your configuration. None of the products registered in the RevenueCat dashboard could be fetched from App Store Connect (or the StoreKit Configuration file if one is being used). 
More information: https://rev.cat/why-are-offerings-empty, underlyingErrorMessage: , readableErrorCode: CONFIGURATION_ERROR}, null)
```

**Comment by zappyle** [comment]
How do you update purchases_flutter? I can't edit the version in FF

**Comment by simone142** [comment]
> How do you update purchases_flutter? I can't edit the version in FF

You can edit the pubspec.yaml downloading the code and running the app through your IDE instead of using the FlutterFlow local run.

**Comment by Alezanello** [comment]
Hi everyone! 👋

It looks like updating the packages resolved the issue. I’ll go ahead and pass this along to the engineering team so they can work on implementing a proper fix.

**Comment by finallyfit** [comment]
@Alezanello do you have an idea how long it'll take to resolve this bug? I can't use local run with my app at the moment so I have no other way to continue work on the app.

**Comment by UNTITLEDPROJEKT** [comment]
> Same. I was able to test my app in the iOS 18.4 Simulator with your solution [@UNTITLEDPROJEKT](https://github.com/UNTITLEDPROJEKT) , however I always get this error message from RevenueCat:
> 
> ```
> flutter: Error loading offerings info: PlatformException(23, There is an issue with your configuration. Check the underlying error for more details. There's a problem with your configuration. None of the products registered in the RevenueCat dashboard could be fetched from App Store Connect (or the StoreKit Configuration file if one is being used). 
> More information: https://rev.cat/why-are-offerings-empty, {code: 23, readable_error_code: CONFIGURATION_ERROR, message: There is an issue with your configuration. Check the underlying error for more details. There's a problem with your configuration. None of the products registered in the RevenueCat dashboard could be fetched from App Store Connect (or the StoreKit Configuration file if one is being used). 
> More information: https://rev.cat/why-are-offerings-empty, underlyingErrorMessage: , readableErrorCode: CONFIGURATION_ERROR}, null)
> ```

ahhh i apologies, didn't know it's FlutterFlow. but seems it has been fixed already :)

**Comment by dennistdk** [comment]
Still an issue in FlutterFlow 5.3.5 (released 1st of April).

**Comment by finallyfit** [comment]
Still an issue in FlutterFlow 5.3.7.

**Comment by simone142** [comment]
Yeah, not fixed yet. You can see the `purchases_flutter` version is still 8.1.2 in the `pubspec.yaml` file.
They've probably fixed other issues in the latest releases.

**Comment by ahmedtanjim** [comment]
What a problem I've spend a day trying to slove it

**Comment by DanielGiraldoMontes** [comment]
Is there any ETA on fixing this issue? how long can it take? and it is very interesting why while deploying my app to App Store from FlutterFlow i am not seeing such issue.

**Comment by smplfy** [comment]
This issue is affecting me as well. Any updates?

**Comment by lordlugo** [comment]
Same, annoying af...

**Comment by mrn42** [comment]
Any ETA FF team?

**Comment by sbis04** [comment]
We are testing the newer version of the `purchases_flutter` to make sure it doesn't cause any other side effects. But if there's a newer version working properly for your project, a workaround for now can be going to the Settings > Project Dependencies >  Add Pub Dependency, and adding the `purchases_flutter: 8.7.0` (or which ever version works for you):

<img width="1030" alt="Image" src="https://github.com/user-attachments/assets/30594523-19fe-45df-a555-852ed699aa5b" />

If the newer version passes the testing phase, we'll soon update to use that version!

**Comment by finallyfit** [comment]
Can confirm the solution @sbis04 shared above is a decent workaround. Pages with Revenuecat crashes, but it's a decent workaround for everything else until the FlutterFlow team ships the complete fix. 

Wish I realized it was this simple 3 days ago but just glad to be able to use Local Run again 🙌

**Comment by Stuartwastaken** [comment]
I've tried the steps from @sbis04 of adding a specific custom pub dependencies and I get a warning that this will break.

I have also tried this response and to no avail, I come up with different issues, despite setting Podfile ios target to 15.0.0, I get an error that FirebaseStorage cannot work on ios version 14.0.0 ?


> > Yes same error for me as well after upgrading to 18.4 ios simulator
> 
> Update your purchases_flutter and purchases_ui_flutter to 8.7.0 on pubspec.yaml and on terminal, navigate to /ios and run `rm Podfile.lock` `rm -rf Pods`
> 
> then run `flutter clean` and `flutter pub get`. next, install pods on /ios using `pod install --repo-update` not `pod install`.
> 
> make sure minimum target is set to ios 15.0 on Podfile!!! (not sure but purchases_ui_flutter requires 15.0 minimum)

**Comment by jonsata** [comment]
Still not fixed.

**Comment by finallyfit** [comment]
Update: still not fixed with the 5.4.2 update. Still need the workaround above to deploy to Local Run. Most likely referring to the same issue here: https://github.com/RevenueCat/purchases-capacitor/issues/421

**Comment by king-anna** [comment]
I have the same issue, new update didn't help

**Comment by ricsantos** [comment]
No idea what FlutterFlow is, but wanted to say this issue would be due to Apple introducing a new typealias called `SubscriptionPeriod` in iOS 18.4, which I guess clashes with an existing class in RevenueCat, because namespacing in Swift is fun.

https://developer.apple.com/documentation/storekit/subscriptionperiod

So if the code is in RevenueCat, they will need to prefix it with `RevenueCat` eg `RevenueCat.SubscriptionPeriod`.

**Comment by paulVu** [comment]
All my apps, built on FlutterFlow and live in production, were checked today. I found that all packages are not displaying, and there’s only a gray screen.

**Comment by deep526** [comment]
I have my app build on Flutter using Android Studio, i added platform :ios, '15.0', removed pod and updated it.... does anyone have the solution yet to this?

**Comment by a0m0rajab** [comment]
Updating to 8.6.2 should solve the issue!
