### ISSUE TITLE
“Map List Items” Transform Cannot Be Finalized

### ISSUE THREAD

**Issue by Storm-dose** [FlutterFlow/flutterflow-issues#5859]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When configuring an Update Page State → Set action to map a Firestore query output (fetchedRightNowList) into a List Page State variable (rawScores), the editor forces a Map List Items → Get Document Property → mood_score step but never lets you exit. After confirming the mood_score mapping, the transform dialog immediately re-opens into another “Filter/List/First Few/Sort…” menu with no way to return to the main action editor. The action cannot be saved, blocking any list-mapping workflow.

### Expected Behavior

After choosing Map List Items → Get Document Property → mood_score and clicking Confirm, the dialog should close and return to the main Update Page State editor, showing: rawScores = fetchedRightNowList.map(e => e.mood_score.toDouble()).toList(); The action should then be savable without requiring additional transforms.

### Steps to Reproduce

Create New Blank Project in FlutterFlow.

Add Page → Blank → name TestPage.

Page State → Add Variable:

Name: rawScores

Type: List of Double

Firestore → Add Collection TestDocs with a field:

mood_score (Number)

Firestore Data → add two documents to TestDocs with mood_score = 1, 5.

On TestPage, add On Page Load actions:

Action 1: Firestore → Query Collection TestDocs → Output fetchedRightNowList (List of Documents)

Action 2: Update Page State → Set rawScores → Value → From Variable → Action Outputs → fetchedRightNowList

Observe: Immediately after selecting fetchedRightNowList, the editor forces you into Map List Items, you pick Get Document Property → mood_score, click Confirm, and the transform dialog loops back into another transform menu with no “Done” or “Back” option.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ei8mAsJRgobhG0LruY+9VgiMvJkw6RYIzlOxhSgwgG4+sPZYDOuj+TGZuOLDid2xiPFmWgm0x+v+NudrpDflcNhyJbNxxzblubTrieGKQV66NEbiKXXElAp5mf0yZzpuZgRN7C/hpLFYf3GaTfeetQhTtJZD2DHokRvyZEJ7MjAupLADoGn0Jg1ZSfCvr

### Visual documentation

![Image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f347256b-54c7-41a0-82e3-f5555f7c09ee/5da734c7-8705-4288-911c-f901b6969cf7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMzQ3MjU2Yi01NGM3LTQxYTAtODJlMy1mNTU1NWY3YzA5ZWUvNWRhNzM0YzctODcwNS00Mjg4LTkxMWMtZjkwMWI2OTY5Y2Y3IiwiaWF0IjoxNzQ3ODQ1OTA1LCJleHAiOjMzMzE4NDA1OTA1fQ.zVJLiGlBN3uCRLErqtunTcIbA3iX42_30OH2TttGsi4)

A short screen recording is available on request.

### Environment

```markdown
- FlutterFlow version: May 2025 PRO (web editor)
- Platform: FlutterFlow Web Editor
- Browser name and version: Google Chrome 114.0.5735.90
- Operating system and version affected: Windows 10 (build 19044)
```

### Additional Information

This bug prevents any workflow that needs to extract numeric arrays from document lists (e.g., chart data binding).

**Comment by Juansarmi** [comment]
Hi! <br>I'm sorry to hear you're experiencing this issue. I've tried to reproduce the error on my end but haven't been able to. Has the problem been resolved with the latest update?<br> Best regards.

**Comment by Storm-dose** [comment]
Hi there,

Thanks for looking into this. The issue is still present. Here’s a recap you can follow in a fresh project:

1 - custom function - CombineFunction:
QUOTE
/// Merges a list of JSON entries plus a single JSON entry into one
/// sorted list (by timestamp). Returns null if both inputs are empty.
List<dynamic>? combineFunction(
  List<dynamic>? listParam,
  dynamic        singleParam,
) {
  // If there are no list items and no single item, return null
  if ((listParam == null || listParam.isEmpty) && singleParam == null) {
    return null;
  }

  final result = <Map<String, dynamic>>[];

  // 1) Map each element in listParam (if any)
  if (listParam != null) {
    for (final entry in listParam) {
      final e = entry as Map<String, dynamic>;
      result.add({
        'timestamp':   e['timestamp']   ?? '',
        'value':       e['value']       ?? '',  // replace with your real fields
        'extra':       e['extra']       ?? '',
        'isSingle':    false,
      });
    }
  }

  // 2) Add the singleParam (if present)
  if (singleParam != null) {
    final s = singleParam as Map<String, dynamic>;
    result.add({
      'timestamp':   s['timestamp']   ?? '',
      'value':       s['value']       ?? '',
      'extra':       s['extra']       ?? '',
      'isSingle':    true,
    });
  }

  // 3) Sort by timestamp ascending
  result.sort((a, b) {
    final ta = (a['timestamp'] as String).isNotEmpty
      ? DateTime.parse(a['timestamp'] as String)
      : DateTime(0);
    final tb = (b['timestamp'] as String).isNotEmpty
      ? DateTime.parse(b['timestamp'] as String)
      : DateTime(0);
    return ta.compareTo(tb);
  });

  return result;
}

UNQUOTE

2 - ACTIONS: 
On a button tap or date-change event, add two Firestore queries:

Query A (alias queryAList): a “List of Documents” query on your collection filtered by type == "A" and date == selectedDate.

Query B (alias queryBSingle): a “List of Documents” query on the same collection filtered by type == "B" and date == selectedDate, with Limit = 1.

Immediately after those, add a State Management → Update Page Variable action to set a page var (alias combinedResult) from a custom function (combineFunction).

In the combineFunction dialog you’ll see two parameters: listParam and singleParam.

For listParam, click Action Output → queryAList. Instead of binding, FF opens the List Transform menu (map/filter) and won’t let you select the raw list.

You should be able to pass queryAList directly into combineFunction, but the UI forces you into a transform step and prevents the direct binding.

I had the same problem on a query / List of documents and on the page state update to allocate the result to a page state variable I have to go through a list transform when I select the query result.

Thanks

**Comment by Juansarmi** [comment]
Hi again!

I’ve tried to reproduce the issue on my end, but I’m getting the expected behavior. This error you mentioned should have been resolved with the latest update.

That said, I can confirm that the issue is indeed happening in your project specifically, which leads me to believe it might be something unique to your project. In this case, the best course of action is to reach out to support via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io) — they have the necessary tools to look into your specific case and assist you further.

Best regards
