### ISSUE TITLE
New release bug. cant check custom functions.

### ISSUE THREAD

**Issue by emilswan** [FlutterFlow/flutterflow-issues#5913]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

after the new release on the 29th I cant run my Apps.  I have an error that i need to check my custom functions.  The check button does not seem to complete the check. I can make a change on my custom functions to force the save and check but selecting the check terminates without completing or giving an error.  

### Expected Behavior

selecting the check  custom functions should run and produce a tick mark or error. 

### Steps to Reproduce

1. click on the (check your custom functions for errors) button
2. system checks and shows the error
3. system gives a tickmark

This used to at least show the function where the system thinks there is an error

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no bug report or tree produced

### Visual documentation

![Image](https://github.com/user-attachments/assets/672f1386-dc64-437f-ae09-8f2f74d390dd)

![Image](https://github.com/user-attachments/assets/8eccb804-2b8a-4cdc-89e4-affacd50e365)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Unity2Blender** [comment]
Do you have Library values in the project?

If any Library value has an Action block as Data type then the Custom functions won't compile, this issue was reported by me 2 days ago.

Issue related to custom funcs not compiling if Library value is Action block type: https://github.com/FlutterFlow/flutterflow-issues/issues/5897

**Comment by emilswan** [comment]
thank you Unity2Blender.  I do have libraries.  What is the best workaround for this. 
I still seem to have this even if i simplify my app.

**Comment by Alezanello** [comment]
Hi there!

Could you please share the **bug report code** from the widget tree? This gives us a complete snapshot of your project, which helps us better identify what might be going wrong.

Thanks in advance!

**Comment by emilswan** [comment]
Hi Alezanello .  Thanks for the help.
Bellow is the bug report link. Not sure if this will yield anything because i cant even get to the compile stage.


ITFThfLlvJR1m7QE+KnbYe14niIQGUMAWoJMitUbdx4YfIzkOpYQYfTOV0NKTNyoeX1UeWCggkQK/tbrhdrDIccVEyyefZxG0JVAeznybGeVRZubCKuddnNDO9ljG3Ks5omG2R1NPvNoLy0R7zuhNq3qNleeY8aSfxBlZ7vfcPo=

**Comment by emilswan** [comment]
i have reduced my project to a single custom function that does nothing.  I still have the same behaviour.
I have an error : Custom Functions need to be checked for errors. Click here to check for errors.

Refreshing the analyzer does not help. 


import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '/flutter_flow/custom_functions.dart';
import 'package:ff_commons/flutter_flow/lat_lng.dart';
import 'package:ff_commons/flutter_flow/place.dart';
import 'package:ff_commons/flutter_flow/uploaded_file.dart';
import '/backend/schema/structs/index.dart';
import '/backend/supabase/supabase.dart';
import '/auth/supabase_auth/auth_util.dart';

String? newCustomFunction() {
  /// MODIFY CODE ONLY BELOW THIS LINE

  return 'a';

  /// MODIFY CODE ONLY ABOVE THIS LINE
}

**Comment by emilswan** [comment]
update .. This has randomly corrected.  I managed to replicate this with a brand new project with a dummy custom function.
same error and then hours later it self corrected.
i see someone else posted on the same issue   #5914

**Comment by m-corderoy** [comment]
I still have this issue, in a project for mobile delivery. Code hasn't changed recently, but now custom function error as described above. Noticed this yesterday, hasn't 'self corrected'. Another project targeting web delivery does not have this problem?

![Image](https://github.com/user-attachments/assets/c8042f47-9fcf-46a6-8207-dcccd48f3b20)

**Comment by emilswan** [comment]
The teste project i build from scratch has not self corrected. It is 5 hours now. so it does seem a bit random unfortunatly.  The only thing i did different on my actual project was to reset the analyzer.  click on the tickmark top left and then the reset.

I might be clutching at straws though as  bug1 project is still giving the error.


![Image](https://github.com/user-attachments/assets/71a6e2c7-d322-4bff-b1f8-07bbf88c8a50)

![Image](https://github.com/user-attachments/assets/d3cec1be-c55a-4184-97ac-a030bc281b1e)

**Comment by emilswan** [comment]
After doing this i switched projects. going back to the the test project i then clicked the validate code.  button to the left of the save button below the preview app button.

**Comment by m-corderoy** [comment]
I have built a similar test project - built in safari this time, not chrome. A soon as i add a custom function the error appears

![Image](https://github.com/user-attachments/assets/cee05adb-cddb-4077-b543-7f795eb54a6a)

**Comment by m-corderoy** [comment]
The test function actually runs, but the error stops the project deploying

![Image](https://github.com/user-attachments/assets/c8c4a397-603c-4349-a3e1-deee9f002422)

**Comment by emilswan** [comment]
Well at least you get it to test.  I cant get it to test mode.  The frustrating thing is even if you just ad a blank comment to the function then you will be back to square 1.  and the error will not go away.  I am trying to time it to see if there is any time dependencies. 

but it seems that once you get the compiler to run you should not change any code.  which defeats the purpose of a development environment.

**Comment by emilswan** [comment]
I tried it in on microsoft internet explorer and it seem to allow me to check the code. So it might be related to chrome ??

![Image](https://github.com/user-attachments/assets/f1d7ea68-034a-40fa-90ce-1c866eb27c10)

**Comment by emilswan** [comment]
Does not explain your deployment problem though.

**Comment by emilswan** [comment]
False alarm .. In Explorer it worked when i initially opened the project but as soon as i changed something like adding a comment in the function i am back to the problem.

![Image](https://github.com/user-attachments/assets/4f42bb1d-5c27-4298-96ee-0bdfa836ad12)

**Comment by m-corderoy** [comment]
Not sure safari uses chrome (webkit?), Explorer(bing) does. However not working is safari or the flutterflow desktop App.

My frustration is project hasn't changed for a few days, deploying fine, no code changes, then upgrade to 6.0.2 and now fails! Have a demo scheduled for Monday!!

**Comment by m-corderoy** [comment]
Things seem to be fixed / working - thanks

**Comment by emilswan** [comment]
it seems to be working for me know ( i have not tested deployment ) . I noticed however that the analyzer is not running/ failing which could be why it is now allowing the code check to go through.

![Image](https://github.com/user-attachments/assets/44455ad1-5e48-49a1-8c6c-1d34b48bd6a5)

**Comment by m-corderoy** [comment]
### PROBLEM HAS NOT GONE AWAY
I started to edit project (not the custom function, UI stuff) and the error icon appeared with 'Custom functions need to be checked for errors. Click here to check for errors.' 

The analyser appear to work though...

Cycles through: 
                       Project Code Generating - Running pub get - Initialising Analyzer - Analyzer Ready

![Image](https://github.com/user-attachments/assets/40bcf24d-a1ee-4e2b-89bd-1a27cca37f69)

@Alezanello

**Comment by binaverse** [comment]
Also experiencing the same thing. Usually, when entering a project, the "custom functions need to be checked" error would be presented and clicking on it, would navigate to the custom functions section and the error would cleared in a couple of seconds. This is no longer the case. 

The code analyzer or function checker etc. is not running and simply spins for half a second then stops again.  

Attached is a console log after clicking "check errors". The error blocks builds from being tested.

<img width="1800" alt="Image" src="https://github.com/user-attachments/assets/bc8d6bc9-7efc-4f43-aa84-81a900fc663a" />

**Comment by skincoder** [comment]
I have the same issue:

![Image](https://github.com/user-attachments/assets/21f30989-e6bb-43b4-bf58-ab757ae77f01)

And when I try to test custom functions I see this:

![Image](https://github.com/user-attachments/assets/372c96e5-7d4e-45e1-8ebd-901d3810b4a4)


But I checked the file and everyting looks good there...

**Comment by itsstevenliu** [comment]
same issue...absolutely blocking my projects. Literally guinea pigs for FF's untested new releases

![Image](https://github.com/user-attachments/assets/425f4c4a-2d78-487d-a208-b53a8a992de6)

![Image](https://github.com/user-attachments/assets/8cadd21e-be58-4486-adc9-583d4494c6d0)

**Comment by skincoder** [comment]
FF TEAM CAN YOU DO SOMETHING ABOUT IT? AND STOP PUSHING NEW RELEASES WITH BUGS PLS.

**Comment by Alezanello** [comment]
Hello everyone,

The engineering team is aware of this issue and is currently working on a fix.

**Comment by artemKuch** [comment]
Go to dashboard and return to project, tap to check the errors, wait a bit.
Its some kind of cache issue

**Comment by czsday** [comment]
I am having the same issue for a few days now. The code had no error for months until a few days ago. When I add new custom code, and even it shows no error, if I exit and log back in after a few hours, it would get me this error.

**Comment by damiannorsoft** [comment]
Please do something about this issue. I cannot test or deploy app. There is no way to take out error message that says: "Custom functions need to be checked for errors. Click here to check for errors."

**Comment by emilswan** [comment]
Damannorsoft.   Try and refresh your analyser.  The button top right and before it completes it load, click on the check custom code button on the right.  I have been able to work around this bug in this way.

**Comment by Unity2Blender** [comment]
One of the bugs I have noticed is that if that project is a Published library and in the Library value: You make an Action block callback variable, then the custom functions won't compile as it imports /ibrary_values.dart and as it contains Future<> function of the Action callback, any async Future<> method won't compile under /custom_functions.dart.

This bug occurs when there are Custom functions in a Project & The Project is a Published library having a library value of Action block type.

More details: https://github.com/FlutterFlow/flutterflow-issues/issues/5897

**Comment by skincoder** [comment]
I heard that FF team is already working on this issue. I hope they will solve it quickly as I am totally blocked and my work is on hold.

**Comment by skincoder** [comment]
> Damannorsoft. Try and refresh your analyser. The button top right and before it completes it load, click on the check custom code button on the right. I have been able to work around this bug in this way.

@damiannorsoft it doesn't worked for me :(

**Comment by damiannorsoft** [comment]
> One of the bugs I have noticed is that if that project is a Published library and in the Library value: You make an Action block callback variable, then the custom functions won't compile as it imports /ibrary_values.dart and as it contains Future<> function of the Action callback, any async Future<> method won't compile under /custom_functions.dart.
> 
> This bug occurs when there are Custom functions in a Project & The Project is a Published library having a library value of Action block type.
> 
> More details: [#5897](https://github.com/FlutterFlow/flutterflow-issues/issues/5897)

I had a custom widget with a callback action. I deleted the custom widget and remove a library used by that custom widget in settings...project dependencies, restarted code analyzer, check functions for errors but everything continue with the same error in this project. Same error message about to ckeck custom functions. Also I tried to modify a custom functions, save and check errors but it doesn't work. Flutterflow team must release a new version to fix this important bug.

**Comment by skincoder** [comment]
There is a new FF release (v6.0.3), but the issue is still present. I still can't publish, even though no error is visible in the upper right corner.
![Image](https://github.com/user-attachments/assets/19a2847a-b393-46e1-89a1-b41c972f8b82)

**Comment by damiannorsoft** [comment]
Same for me, version 6.03 installed and still same error...

**Comment by tpersson** [comment]
If the team is not able to solve this in 4 days I really recommend a temporarily solution here, e.g. removing the checks or rolling back... this is not a minor bug, it is blocking development

**Comment by mpalomino** [comment]
same issue here in v6.0.3

**Comment by damiannorsoft** [comment]
version 6.0.4 just released and this bug is still there... cannot test or deploy project :(

**Comment by mpalomino** [comment]
> version 6.0.4 just released and this bug is still there... cannot test or deploy project :(

just confirming version 6.0.4 not working, same bug

**Comment by ntiyisombhalati** [comment]
@Alezanello, can the FF team, please rollback to previous working versions this is affecting development and reputational damage for some of us who have to deliver to our clients.

**Comment by damiannorsoft** [comment]
Version 6.0.5 released and this bug is not fixed yet

**Comment by mpalomino** [comment]
> Version 6.0.5 released and this bug is not fixed yet

is fixed on my end, I tried the web app and the macOs app and it is working in both

**Comment by damiannorsoft** [comment]
> > Version 6.0.5 released and this bug is not fixed yet
> 
> is fixed on my end, I tried the web app and the macOs app and it is working in both

I tried both (Mac OS desktop app and web) but error is still there :( trying restarting code analyzer, checking error on custom functions and also modify a custom function and save it...

**Comment by mpalomino** [comment]
> > > Version 6.0.5 released and this bug is not fixed yet
> > 
> > 
> > is fixed on my end, I tried the web app and the macOs app and it is working in both
> 
> I tried both (Mac OS desktop app and web) but error is still there :( trying restarting code analyzer, checking error on custom functions and also modify a custom function and save it...

try logging out and logging in again on FF

**Comment by damiannorsoft** [comment]
> > > > Version 6.0.5 released and this bug is not fixed yet
> > > 
> > > 
> > > is fixed on my end, I tried the web app and the macOs app and it is working in both
> > 
> > 
> > I tried both (Mac OS desktop app and web) but error is still there :( trying restarting code analyzer, checking error on custom functions and also modify a custom function and save it...
> 
> try logging out and logging in again on FF

@mpalomino I logged out and login again from web and Mac but it doesn't work

**Comment by skincoder** [comment]
I logged out, refreshed and tested 6.0.5... and the issue is still there - I can't publish my web app :(

**Comment by mpalomino** [comment]
The issue is back on 6.0.5 , it worked for a few hours

**Comment by damiannorsoft** [comment]
> The issue is back on 6.0.5 , it worked for a few hours

Ayyyy Miguel... estamos en el horno con esta gente de Flutterflow :)

**Comment by mpalomino** [comment]
> > The issue is back on 6.0.5 , it worked for a few hours
> 
> Ayyyy Miguel... estamos en el horno con esta gente de Flutterflow :)

I know... 
it started to work again on my end.... lets see for how long

**Comment by aliumutergin** [comment]
It was working barely ( if I refresh) but with upgrade to 6.05, it doesn't work now. My clients are waiting....Please

**Comment by arbithq** [comment]
The issue is back, and it's frustrating. I thought there was something wrong with the custom function, so I moved the functionality and deleted the custom function. Now, the error is showing up in the next custom function. It seems like it's just taking the first custom function and showing the error there.

I need to release a fix for an urgent production issue, but I can't. Please provide a workaround.

**Comment by arbithq** [comment]
FlutterFlow Team: you cannot block people from making progress in their own work. If it is impacting so many users, why don't you just roll back your release?

**Comment by skincoder** [comment]
This is definitely a tough bug to deal with, and it seems like it's taking a while to fix. Maybe we should reach out to support and suggest they allocate more resources to it? Or, if that doesn't help, maybe it’s time to dive into.. pure Flutter?

**Comment by MaximCosta** [comment]
Please, FF Teams, can you fix the bug? It is becoming really inconvenient for everyone, as it is blocking projects.

**Comment by EmilieD21** [comment]
I am having the issue too. Thanks for your support

**Comment by damiannorsoft** [comment]
I created a new blank project and added a single custom function with only return('ok'); and same error...

**Comment by pedrobuzzi** [comment]
it's blocking any progress and deploy with my app!

**Comment by PawelAntoniak** [comment]
I'm really rooting for this platform, FF is awesome... but this 6.0.0 release is something I just can't understand...

**Comment by Pylz** [comment]
FF version 6.0.6 has just been released and it finally fixes the bug that caused major issues all week. It was a really frustrating experience not being able to move forward with development, especially for those of us on tight deadlines. The bug basically brought everything to a standstill and made working in FlutterFlow nearly impossible. I was seriously getting angry at the thought of going into the weekend with this still broken, so I’m genuinely relieved it's now resolved. Thanks to the team for pushing through and getting the fix out before the weekend!

**Comment by damiannorsoft** [comment]
> FF version 6.0.6 has just been released and it finally fixes the bug that caused major issues all week. It was a really frustrating experience not being able to move forward with development, especially for those of us on tight deadlines. The bug basically brought everything to a standstill and made working in FlutterFlow nearly impossible. I was seriously getting angry at the thought of going into the weekend with this still broken, so I’m genuinely relieved it's now resolved. Thanks to the team for pushing through and getting the fix out before the weekend!

6.0.6 released just for web, no updates for MacOS desktop version yet

**Comment by pedrobuzzi** [comment]
in the MacOS desktop version is not fixed, but if you open the FF Web, it will fix the code analysis and then you can continue in the Desktop app. It's a workaround that worked out for me.

**Comment by damiannorsoft** [comment]
> in the MacOS desktop version is not fixed, but if you open the FF Web, it will fix the code analysis and then you can continue in the Desktop app. It's a workaround that worked out for me.

Yes, you are right, I did it and it worked, thanks a lot @pedrobuzzi

**Comment by skincoder** [comment]
Dammn I still can't publish my web app:

![Image](https://github.com/user-attachments/assets/39b8d92e-67e5-4cad-83c5-8f157b87e3d0)
