### ISSUE TITLE
Sev1: FF update strikes again

### ISSUE THREAD

**Issue by humbitious** [FlutterFlow/flutterflow-issues#6055]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Once again, we were toddling along, working on our looming release deadline, and the “update ff” alert popped up. We have come to live in fear of these, but nevertheless, we updated. Mac Mini m4 with latest sequoia os.  Was running iOS emulator in local run.  After update, ran local run test again, and got the dreaded “main not found alert”. Then something really unexpected happened.  Restarted everything, and now ff won’t even export project files. No logs error.  Just a small red oval alert widget that appears and disappears too fast to see what it says. Then nothing.  

Before you ask, we than proceeded to spend over an hour testing every combination of variables, including a complete rebuild and reinstall of both ff   And reinstall of Xcode from the ground up, taking care to clean and rebuild the environment step by step.  

No joy. 

But hey…why should we expect that this major crunch time for us should be any different than previous ones?  FF must extract its tax on wasted time. 

### Expected Behavior

See above

### Steps to Reproduce

See above

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40k+XY4YVNsbRI4KrQL+1F9TkXN0wKW4MNqe5RaCgofePtOol3evXsUBZoZ/W8TEFqP0SmmjoE08rekYXDCvYEGzObRrk/1s1iFwv/Vl25a5OBCcyJe3FtJ+xRClC1156rpxRdJvBaWF4H20yHeujIQgTdGIDNImdISq/LZO4=

### Visual documentation

See above

### Environment

```markdown
- FlutterFlow version: 16….not in front of computer…rebooting and decided to get away from the desk and write this on phone.  Today’s update. June 24, 2025
- Platform: Mac OS
- Browser name and version: chrome but not using for this issue…local run
- Operating system and version affected: sequoia latest
```

**Comment by boezeman** [comment]
same for me.  I tried deleted flutter flow from applications, removed flutter flow from the application support.  Reinstalled flutterflow, reinstalled flutter sdk, under the gear for local run.  And can't get any project to export.  Switched to other branches and still can't get project to export.  Completely DEAD right now!

Also #6054 is the same/related issue, that also fails for me too, when trying to refresh the analyzer.  Get Project code generation failed.

**Comment by boezeman** [comment]
I've also noticed, that even though i'm the owner of the project, i can't change anyone to owner, or change them anymore from read-only to editor.  Seems like permissions are messed up for our account.

**Comment by boezeman** [comment]
I have also tried this on a clean macbook. Installed flutterflow for first time, go to our project, and can't generate the project folder.

**Comment by boezeman** [comment]
and what is suspicious is "invite user" is greyed out, even though I have the Owner Role

**Comment by Alezanello** [comment]
**Hi there!**

We deployed a fix for this issue yesterday afternoon. Could you please check and let us know if everything is working correctly on your end now?

**Comment by boezeman** [comment]
hey @Alezanello  Was still failing last night at 9pm EST.  This morn at 9:15am EST, the browser webapp at app.flutterflow.io that i left on my project, showed my project information, but a big dialog which said: 

"**Project Access Restricted**. You are trying to access a project that doesn't exist or you don't have access to. If someone shared this link with you, pleaes ask to double check the URL and that you have been added as a collaborator to the project.  Return Home."  

Clicking return Home just spun forever.  Closing the browser tab, and going back to FF webapp, selecting my project, allowed the project to open. Also in the mac FF app, i had to reopen the project. 

I can now build again in the mac version of FF!  So that part is fixed, but not fully fixed, since on the project Settings->collaboration still seems broke.  I can't invite(its greyed out), i'm still set as owner, and colleague is set as editor.  I can't change him, i can't change me, and invite.

**Comment by boezeman** [comment]
Also @Alezanello i had a colleague that was readOnly in our project and asked him to see if he could leave the project, and it says he doesn't have permission to leave.

**Comment by boezeman** [comment]
Hey @Alezanello  toher than the security aspects not working,  after your change yesterday, i have been generating all day today, till 3:45PM EST.  I'm now completely blocked again, it won't export the project for build anymore.  So something on your side must have changed again

**Comment by Alezanello** [comment]
Hi there, and apologies for the delayed response. Are you still experiencing the issue, or has it been resolved with the latest FlutterFlow updates?

**Comment by luxthecreator** [comment]
@Alezanello I'm having this issue with the latest version v6.0.36 released July 3 2025 on Windows

I got an error message saying that main.dart file was missing.
After attempting a reexport, I get: Failed to export code

For v6.0.37 on Web, Test Mode shows: Error loading project for test mode. There may be a configuration issue in your project. Please check your project issues for more info.

Using the Download Code option fails with: Code Download Failed - Unknown Error
