### ISSUE TITLE
Code editor not working in Windows

### ISSUE THREAD

**Issue by webwurm** [FlutterFlow/flutterflow-issues#6147]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the code editor to eg. write Custom Functions, it is very often not responsive and doesn't accept keyboard inputs. After a few times and clicking around in the code with the mouse, it works. Sometimes a yellow square appears - then usually it doesn't work. Also when marking text with the mouse and pressing the delete-key, very often it doesn't react.

### Expected Behavior

Well, an editor should work...like it does online, but there the whole app is really, really slow...

### Steps to Reproduce

1. Open a custom action
2. Try to edit the code

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xl8nl3891pbxH1rXuY+9VijsXJmY6RY0/iu1Edws1GLbpBLAHdsnuT3FdOLynSnxIOWGjnnIIp9bXuOOTUu1dIgSIQ75Z1s1yEA/yWn+uVYigPYe8QUBPGcBjIG6s4bCOihVvAPV2LV5h3WGYI++8SjDcK4zONW0RQvL9Oob4+QOFLSO2LjhmtmNecCfn

### Visual documentation

![Image](https://github.com/user-attachments/assets/e829da7c-6304-426e-8230-c6550603d238)

### Environment

```markdown
- FlutterFlow version: 6.0.46+
- Platform: Windows
- Browser name and version: -
- Operating system and version affected: Windows 11
```

**Comment by nihatdemir79** [comment]
same here

**Comment by Juansarmi** [comment]
Hello!

I'm sorry you're experiencing this issue. I was able to reproduce the error and will be forwarding it to our engineering team for further investigation. I’ll let you know as soon as I have any updates.

Best regards

**Comment by hadibou** [comment]
same here

**Comment by woiq** [comment]
Hey team, the issue most likely lies with the 'focus' it brings into the coding textbox. 
As you can see on windows, the focus is lost when the title bar is white and doesnt allowed text input:

<img width="104" height="41" alt="Image" src="https://github.com/user-attachments/assets/e6835710-f158-4461-983d-c87ad61c9009" />


And when focus is regained on the coding field it correctly greys out, marking the active window:

<img width="112" height="39" alt="Image" src="https://github.com/user-attachments/assets/a6f659a4-103b-42fb-8bfd-66c4e524be48" />

Anyway, it seems to automatically unfocus the coding field upon entering, allowing only a split second of text entry before disabling.

**Comment by alessandro-diasn** [comment]
same here.

**Comment by gellert234-dev** [comment]
Same here

**Comment by polenvinagre** [comment]
Same here

**Comment by mr-lanzoni** [comment]
Same here, its difficult to make it work normally, sometimes ive clicked 4 ~ 6 times to focus and be able to edit the code on windows app.

**Comment by nihatdemir79** [comment]
Whats going on? I have received 5 updates since this issue and this issue still not fixed?

**Comment by nihatdemir79** [comment]
I CANT deploy my apps

**Comment by nihatdemir79** [comment]
FF Windows version has issue. FF Web version works.

**Comment by MartinLockheart** [comment]
I'm still dealing with this as well. Having to switch to web anytime I need to add or edit a custom action.

**Comment by Juansarmi** [comment]
**Hi everyone!**<br>Our engineering team is currently working on a solution. I’ll share updates with you as soon as I have them.<br>Best regards

**Comment by 1Elko1** [comment]
Hi, any news?

**Comment by MrPatben8** [comment]
How is this not fixed yet? I feel like I'm spending more of my time complaining about FlutterFlow and dealing with it's quirks instead of actually working on the projects that I pay to user FF for.

**Comment by gellert234-dev** [comment]
Any update on it ?

**Comment by jonl-percsolutions-com** [comment]
Issue still occurring in FlutterFlow 6.1.11+ updated today.

**Comment by smad-bro** [comment]
After the update the issue still persists! Don't you guys have testers before releasing something??

**Comment by ArachnaDigitalLtd** [comment]
I'm really disappointed this hasn't been fixed after the update.

**Comment by costagontijo** [comment]
@FlutterFlowEng @Juansarmi It's simply absurd that such a simple problem, which causes so much disruption, remains unresolved after weeks. This isn't a free tool, and it's actually very expensive for us Brazilians.

FlutterFlow has always had many bugs that take days, weeks, or even months to resolve. After all, this is the low-code platform Google is betting on?

**This is disrespectful to developers.**

**Comment by giujl** [comment]
Same here, the current environment makes productive work difficult, as each system upgrade introduces stability concerns.

**Comment by ArachnaDigitalLtd** [comment]
Still not fixed in update 6.1.12. I would consider this high priority, surely? Its a fundamental part of the whole point of FF?

**Comment by hadibou** [comment]
We still receive updates, but there's still no fix for this! Is this issue specific to certain accounts, such as those with free plans?

**Comment by 1Elko1** [comment]
Yeah now Im lost for words, how could those other bugs be a priority over this issue?

**Comment by MrPatben8** [comment]
> We still receive updates, but there's still no fix for this! Is this issue specific to certain accounts, such as those with free plans?

Nope, it's affecting everyone.

**Comment by Wapinpin** [comment]
As a workaround since these last few weeks, I open the code editor within my browser from https://app.flutterflow.io/ and I open my project on the desktop app at the same time for the Local Run.
When I update the code in the browser, I have to wait until it's synced and then reload my local run, it work seamlessly.

**Comment by sabatage3** [comment]
Any updates here? This is a big issue

**Comment by Joaquin-Mendoza-Eurekant** [comment]
The issue persists, and it's frustrating that it hasn't been resolved yet.

**Comment by OpaleCIA** [comment]
it seems to be fixed in desktop App 6.1.14 (Windows)

**Comment by smad-bro** [comment]
@OpaleCIA Yes, it's working now

**Comment by Joaquin-Mendoza-Eurekant** [comment]
Yes, I can see that it's already resolved in the latest version

**Comment by hadibou** [comment]
The title bar blinks when I click anywhere in the code editing area, but at least I can now add code.

**Comment by bob-reus** [comment]
The issue persists for me on v6.1.14+ released August 1, 2025.

**Comment by hadibou** [comment]
I'm experiencing high GPU usage when editing some Custom Actions. I'm done, I move to Flutter on VSCode.

<img width="492" height="290" alt="Image" src="https://github.com/user-attachments/assets/9c0c8bc7-36cb-4c44-88a9-d34c6496590a" />

**Comment by sbis04** [comment]
Closing this once since I believe the original issue is already fixed on Windows. Recently, we also pushed a fix for the high memory usage while editing custom code.
