### ISSUE TITLE
Unable to parse custom class

### ISSUE THREAD

**Issue by vdevc** [FlutterFlow/flutterflow-issues#6187]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Certain types of classes are not parsed and are not usable at all.
I have created two separate custom class files in the custom_code:

1. MyService class. Here's the code

```
    class MyService {
      Future<void> initialize() async {}
    }
```

   after saving the class I have ensured that analyzer was active and pressed the button to verify the code. The code has been validated and the class parsed correctly.

<img width="171" height="245" alt="Image" src="https://github.com/user-attachments/assets/cb25420f-9b67-433b-b272-4706fb0ae56f" />

1. MySingletonService class. Here's the code

```
    class MySingletonService {
      static final MySingletonService _instance = MySingletonService._internal();
      factory MySingletonService() => _instance;
      MySingletonService._internal();
      
      Future<void> initialize() async {}
    }
```

   after saving the class I have ensured that analyzer was active and pressed the button to verify the code. The code has been validated immediately (!!!!) but the class is not parsed at all.

<img width="531" height="157" alt="Image" src="https://github.com/user-attachments/assets/be592ab8-55e3-4e7f-9821-3e878176b3e2" />

### Expected Behavior

I would expect that any class without build errors shall be parsed correctly.

### Steps to Reproduce

Follow the steps in issue description. I just started from scratch

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slc/qx89OxL1E7c+BcvlR/SIROVA6ap0kscp/bxIgGIDzPOw+ZPWlVBJocM+mT2xfekSmmXEz0c7JjdntM/kpPUuaf6pZzJZ2Wg6VUlumQZOBDKmBPX9DO+FjfxGB07SzhBJQXctsc0UjwGWyBumuazDbHZe2ImdISq/LZO4=

### Visual documentation

<img width="409" height="287" alt="Image" src="https://github.com/user-attachments/assets/e392e7f5-2eb3-40d6-81aa-065dbd9326e8" />

### Environment

```markdown
- FlutterFlow version: 6.0.50
- Platform: macOS
- Browser name and version:
- Operating system and version affected:
```

**Comment by Juansarmi** [comment]
Hello!

I'm sorry you're experiencing this issue. I was able to reproduce the error and will be forwarding it to our engineering team for further investigation. I’ll let you know as soon as I have any updates.

Best regards

**Comment by vdevc** [comment]
Thanks a lot @Juansarmi 
As an additional information, please note that this bug started appearing after the recent upgrade of flutter version. Before of that, I was able to add classes using the same singleton pattern.
Also, consider that, when the class is not parsed, is not even eventually pushed to the github repository, if this is configured for the project.

**Comment by ArachnaDigitalLtd** [comment]
Same issue here, looking forward to a fix!

**Comment by ArachnaDigitalLtd** [comment]
Looks like this hasn't been fixed after the update. Pretty disappointed, as I'm blocked because of this issue

**Comment by DamusAI** [comment]
Same issue for me as well! Looking forward to the fix as currently custom code is pretty unusable. 

Will be a GOATED FEATURE once this gets sorted!

**Comment by vdevc** [comment]
Hi @Juansarmi, please note that also #5969 is another duplicate issue of this one. 💪🏻

**Comment by ArachnaDigitalLtd** [comment]
Looks like they have removed the ability to view custom classes altogether in 6.1.12 update, but you can still create them....

**Comment by MarcelKempf** [comment]
Is there no update from the FlutterFlow team? Is there a timeline for when FlutterFlow will start working again, or a refund for the period when it didn't work? Sometimes it parses some custom classes, but there is really no pattern to it.

**Comment by ArachnaDigitalLtd** [comment]
@wenkaifan0720 Do you have any update on this issue please?

**Comment by Eloks7** [comment]
@ArachnaDigitalLtd I have this issue too. You create these classes and use a custom action to call the methods pending when this will be fixed.

**Comment by smplfy** [comment]
Same issue here. Please give us an update.

**Comment by Juansarmi** [comment]
**Hi everyone!**<br>Our engineering team is still working to find a solution for this issue. I’ll make sure to keep you updated as soon as I have any news to share.

Best regards

**Comment by smplfy** [comment]
Any updates today? I'm stuck and can't move forward without a fix here. Thanks!

**Comment by wenkaifan0720** [comment]
Hi all. Sorry for the delayed response. This should be fixed by our next release.

**Comment by vdevc** [comment]
Hi @wenkaifan0720, do you mean 6.1.16, or the next one? I am asking because 6.1.16 does not seem to solve the issue in my case.

**Comment by DamusAI** [comment]
@wenkaifan0720 Can also confirm on Mac desktop app, 6.1.16 does not work still with the same error

**Comment by wenkaifan0720** [comment]
Hi. Sorry I meant the regular release next week. The releases this week are more for more urgent bug fixes.

**Comment by smplfy** [comment]
This week's release, 6.1.32 does not fix this issue. Can we please get an update @wenkaifan0720 ?

**Comment by wenkaifan0720** [comment]
Hi @smplfy. Could you provide a bug report code/project id? Happy to look into your project.

**Comment by smplfy** [comment]
Thanks @wenkaifan0720 

IT4klPHlz5RgodtF7rX1bcdKiiAUJnJ6TL07ttYbZxUjIuPtBJh/e+D4TBBoUsTiYHlhHGaGpHEy/62PkoflGMc3Fw+CfL47/5ZiVDvhVXq8RbKQPZCCYGt6MJlUGhGnyLuokSJCIsZYWk4O70+Tf+ytQh3dJ5+/Zwh9f6PHaOI=

**Comment by wenkaifan0720** [comment]
<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0e6f1077-8d35-448d-a8b9-f1a2316f6bc4/25df9d53-808e-487e-b5b2-a76319721352?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wZTZmMTA3Ny04ZDM1LTQ0OGQtYThiOS1mMWEyMzE2ZjZiYzQvMjVkZjlkNTMtODA4ZS00ODdlLWI1YjItYTc2MzE5NzIxMzUyIiwiaWF0IjoxNzU0NTE2NTUxLCJleHAiOjMzMzI1MDc2NTUxfQ.d8dOUyL23qZRG4jpdnt4YrQV1tRg_HitkQox5phgLYI " alt="iScreen Shoter - Google Chrome - 250806174056.jpg" width="2852" data-linear-height="1579" />

I can see the three classes now. Could you try incognito mode and see if the classes are parsed? Please wait until the green check mark shows up in the top left corner.

**Comment by MarcelKempf** [comment]
@wenkaifan0720 I'm still having trouble parsing. In VS Code, we have duplicate classes due to renaming, and it's not possible to delete invisible classes. 

In our Gym file, there are three classes, but most of the time, only one is displayed (even before the bug fix). Renaming the file parses all three classes correctly. However, after some time, it reverts to showing only one class and all the changes made in FlutterFlow Builder are lost. It is not possible to roll back and all the classes' implementations in FlutterFlow are deleted 🤯

ITFTkc7luM9NobRF+KX+K8dalmEsCUMBX5Ir1utvGAIYIbb2OuwQYsj+aXdCXd+4Sgt6Gk2GrEIyw6HqkuPuVsE5OTutGbV607gBbBXLZH6gR7qKCbuSX0B6JNNgC3KH0J+JhB5+Ks1hdV0t72GHcq3qNleeY8aSfxBlZ7vfcPo=

Support for pushing custom classes within the VS Code extension would be an useful update.

**Comment by wenkaifan0720** [comment]
I have identified the issue for your case @MarcelKempf . Will open another ticket to track that. Thank you!

**Comment by PetitAros** [comment]
The issue still seems to persist even after the fix

**Comment by Eloks7** [comment]
Can use custom actions to call the methods in your classes as a temporal fix.

**Comment by SSpotDeveloper** [comment]
I had this issue just now, while busy looking for answers here, it parsed. seems like we need to give it time.
