### ISSUE TITLE
Erroneous error when testing custom functions

### ISSUE THREAD

**Issue by Hypersight** [FlutterFlow/flutterflow-issues#626]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a number of custom functions, that as of the latest update (v3.1 Flutter 3.7.3 on Mac OS Ventura 13.2.1 and on Chrome 111.0.5563.64) that consistently return errors that I believe relate to the UI and not the code being tested. Function test response is consistently returned as a "1" and an error message appears at the bottom of the UI.

```
Compilation error: Info: Compiling with sound null safety
lib/main.dart:787:36:
Error: Couldn't find constructor 'Color.fromRGBO'.
  Color active_color = const Color.fromRGBO(68, 68, 74, 1.0);
                                   ^^^^^^^^
lib/main.dart:788:38:
Error: Couldn't find constructor 'Color.fromRGBO'.
  Color inactive_color = const Color.fromRGBO(38, 38, 41, 1.0);
                                     ^^^^^^^^
Error: Compilation failed.
```
![Screenshot 2023-03-17 at 10 59 09 am](https://user-images.githubusercontent.com/4229798/225973307-6b00a5db-8dd5-4de6-9f7e-2becae544431.png)

### Expected Behavior

When running the function, I expect it to return the response I'm expecting or report an error if the code is invalid.

### Steps To Reproduce

1. Create a simple function that returns a string, such as:
```
import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '../../flutter_flow/lat_lng.dart';
import '../../flutter_flow/place.dart';
import '../../flutter_flow/custom_functions.dart';
import '../../backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../auth/auth_util.dart';

String? testFunction() {
  /// MODIFY CODE ONLY BELOW THIS LINE

  return "Testing";

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```

2. Switch to the Test Function tab and click "Run"
3. The error noted in "Current Behavior" is shown and the response is always shown as "1". In the function above, I would expect there to be no errors shown and a response of "Testing".

### Bug Report Code

IT4gz8r6w49OsfpE7aX6bu9WiigvJU98R4c0sNobbxAjIoDoPJkUaffBTxNCYN++Y0FpKEWJuGQd+NbOuITEGPkqHymqbZxB+bpAWgrNVl+/aoSnBc3hdXMnFp5bfR2c0MPYuB14BOphWF4Z22eEOfOvXgjZNOL6Zwh9f6PHaOI=

### Context

I am not able to write or edit any custom function and validate that it works as expected.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web and MacOS
- Browser name and version: Chrome 111.0.5563.64
- Operating system and version affected: Mac OS Ventura 13.2.1
```

**Comment by Hypersight** [comment]
@hariprasadms Your response is confusing. Are you acknowledging this was a prior bug and should have been fixed in the latest version? That seems to be what you are suggesting.

I am running the current version and it's still returning this error across multiple platforms, so it's by no means fixed.

**Comment by agreaves** [comment]
You are correct, I believe we misunderstood you here and should not have closed. This will, however, be fixed in the upcoming deployment!

**Comment by Hypersight** [comment]
@agreaves I've still not seen a fix for this at all. And this ticket backs up my report https://github.com/FlutterFlow/flutterflow-issues/issues/691
