### ISSUE TITLE
Debug test mode is not showing certain pages

### ISSUE THREAD

**Issue by Remkin1976** [FlutterFlow/flutterflow-issues#6277]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

So in my app I have a basic admin panel. Any page that is using a page state wont show in the test debug panel. For instance I have a table with 2 admins in list view. The pen icon passes the page parameters to the next screen which is an editable card of that user.

For 6 hours I rewrote and attempted to debug. The pages states are passing through to the debug.

after 6 hours I tried something different - opened it in the browser. Works fine as designed, can see the page states but I can provide they are loading and also changing based on the operation of the buttons which have conditional formatting applied from the page states, as such the conditional formatting is representing the page state.

The issue is that there is no loading of any widgets apart from the side Nav which is loaded as a component. Sometimes that also doesnt show.

### Expected Behavior

The test and debug panel must be a reliable source or truth for debugging purposes. The only reason I am using this app is to speed up development. At the moment, with all other bugs, nuances, and now this stopping working it is not sustainable to use this tool. If I cant get it resolved then I'll just move to a MERN stack code directly out of VSCode. It's far superior for testing, speed of loading, and for error reporting.

I need this resolved by the end of the week otherwise I'll have to request a refund for the subscription. Let me know if you need any more from me. Happy to assist wherever possible, for myself though its not sustainable to develop apps through this platform if the very tools I need dont function.

### Steps to Reproduce

1. delete all page contents
2. add static widgets - works ok
3. add form widgets - works ok
4. pass page parameters through - breaks
5. Split page parameter widgets from static widgets - all broken, even static widgets dont fail

in the event of failure of a query for instance, null return, this type of error occurs.

6. Open app using Run in browser (no debug or test) - works ok

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5ThcqA5YhPsdtJ14SJcfowgjwWQkc7UOdEl+thaw4bDOvsOrM2esj8T3FJXMu4d2xUJGH8sGAIps6KhePTCcE3E06IQ75C+c9ybwrgJXOlVcnXBoeSZEdBL/Fjf0jC0qCOihUlCOppLyFl20OUJ/K9bB/bN5D3C1UNHf39FK3L+W/hGh3RFzhQtmNecCfn

### Visual documentation

<img width="7200" height="4309" alt="Image" src="https://github.com/user-attachments/assets/fc8841b3-1bc7-43bf-95c0-63e34546cf95" />
<img width="7200" height="4309" alt="Image" src="https://github.com/user-attachments/assets/228c40ac-4e15-4377-a683-0832d9580bbb" />

### Environment

```markdown
- FlutterFlow version: Version 6.1.15 (6.1.15)
- Platform: MacBook Pro M3 Max
- Browser name and version: Safari Version 18.5 (20621.2.5.11.8) also chrome
- Operating system and version affected: MacOS 15.5 (24F74)
```

**Comment by Alezanello** [comment]
Hello!

We’re currently experiencing some issues with Test Mode that the team is actively working on. These may affect your testing experience.

If you’re comfortable exporting code and using VS Code for debugging, we recommend trying out the FlutterFlow CLI. It allows you to download and use the Debug Panel locally, which helps in inspecting variables on each page. You can find the documentation here: [FlutterFlow CLI Docs](https://docs.flutterflow.io/exporting/ff-cli/)

To enable the Debug Panel locally, just use the --as-debug flag when exporting your project.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/17579de8-6130-48ad-87e6-e0a2e86a2bfa/78bd3ca4-9a14-4baa-924e-41fffbf0b9e4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNzU3OWRlOC02MTMwLTQ4YWQtODdlNi1lMGEyZTg2YTJiZmEvNzhiZDNjYTQtOWExNC00YmFhLTkyNGUtNDFmZmZiZjBiOWU0IiwiaWF0IjoxNzUzNzk5MDY2LCJleHAiOjMzMzI0MzU5MDY2fQ.Ax54I5B_JgbPLx42G8_S4NHljISululUxvq6UM8yQbE " alt="Captura de pantalla 2025-07-29 a la(s) 11.23.22 a. m..png" width="820" data-linear-height="85" />

**Comment by Remkin1976** [comment]
Hey what I mean is if I use VSCode ill just develop a MERN stack using react.

Can I get an update on this please, Ive given some specific core information for debugging. Saying go to CLI is not what I wanted. This needs attention ASAP I gave you to the end of the wee and its 'triage in progress' I'll turn the heat up if thats what you want. This is the death of use of this tool for me. Especially when your spamming me with this garbage about The flutterflow developers conference how is that even a priority you guys have got no idea it seems

**Comment by Alezanello** [comment]
Here is the bug of Test Mode: [https://github.com/FlutterFlow/flutterflow-issues/issues/6136](https://github.com/FlutterFlow/flutterflow-issues/issues/6136)<br><br>It has been solved, you can go back and use Test Mode

**Comment by Remkin1976** [comment]
Hey this is not solved, you may have fixed test mode but my bug still exists. please reopen

**Comment by Alezanello** [comment]
Could you please share the console logs you’re seeing when opening the page that appears blank? This type of issue is often related to a renderLayout error, and the logs will help us better understand what’s going on.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
