### ISSUE TITLE
Color condition fail

### ISSUE THREAD

**Issue by blondie63** [FlutterFlow/flutterflow-issues#650]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On an icon widget i added a condition (If/Then/Else) to choose the icon color basing on page state var
I choosed green color for condition = true and red for all other case
Running app as test i've Blue  for condition = true

### Expected Behavior

I need to render colors i choosed

### Steps To Reproduce

On an icon widget i added a condition (If/Then/Else) to choose the icon color basing on page state var
I choosed green color for condition = true and red for all other case
Running app as test i've Blue  for condition = true

### Bug Report Code

IT4wlsmAsI1Nobhe+KqJb/pvoCMvIjo2aJ0rk8IbGSs9Grb0POxzacn8XEpWOM+8d1ZHKEWInXMz3N6OkvzhU/ZeBwyWG9VZwsx6ZQvyQnK/aoSMELWWZHQnBZtRfmHC3J2N2CV/JfthdVo1217zDfKiQhLtQZ/7Zwh9f6PHaOI=

### Context

You can see here:
<img width="1288" alt="FF-color-condition-issue1" src="https://user-images.githubusercontent.com/1261851/226740317-671e2f34-52f5-4936-b311-37cde07edd8f.png">
<img width="847" alt="FF-color-condition-issue2" src="https://user-images.githubusercontent.com/1261851/226740336-d6ffcd7c-f42b-4638-bb45-940de705f565.png">

### Environment

```markdown
- FlutterFlow version: 3.1 released March 21 2023
- Platform: Web
- Browser name and version: Chrome Version 111.0.5563.64
- Operating system and version affected: macOS Ventura 13.2.1
```

**Comment by blondie63** [comment]
This is quite a big mistake, how does FF confuse the colors? Is it possible that no one from the team takes a look at it??

**Comment by wenkaifan0720** [comment]
Hi @blondie63. I looked into the code and it is generating the right color. I have no idea why this is happening, but I am looking into this issue.

**Comment by blondie63** [comment]
Thanks, it works fine !

**Comment by wenkaifan0720** [comment]
Hi @blondie63. I think this is resolved now, right? I'll close this issue.

(I could reproduce this issue at the time this issue was raised, but not right now)

**Comment by blondie63** [comment]
@wenkaifan0720 It seems to me that you are in too much hurry to close the issues !! I just tried and the problem persists!
Incidentally, the latest release is still that of March 23, nothing has changed!
I'll tell you more, if instead of using the conditions of the FF UI, I use a custom function, the colors are corrected...

**Comment by wenkaifan0720** [comment]
Hi @blondie63. You are right. My bad. I saw this screen first and thought the issue is resolved.
![iScreen Shoter - Google Chrome - 230326120121](https://user-images.githubusercontent.com/112435854/227788589-73ed1edb-ab00-4e08-be19-e8b3ce9626c5.jpg)

But when I click on the button in the top row, the blue icon color comes back. This is really confusing to be honest, because the generated code looks like the following for the two icons:
```
// Generated code for this StatusRow Widget...
Row(
  mainAxisSize: MainAxisSize.max,
  children: [
    Icon(
      Icons.alternate_email_sharp,
      color: valueOrDefault<Color>(
        getJsonField(
                  companyBookingsItem,
                  r'''$.email_verified''',
                ) ==
                FFAppState().intTrue
            ? FlutterFlowTheme.of(context).customColor1
            : FlutterFlowTheme.of(context).alternate,
        FlutterFlowTheme.of(context).alternate,
      ),
      size: 24,
    ),
    Padding(
      padding: EdgeInsetsDirectional.fromSTEB(10, 0, 0, 0),
      child: Icon(
        Icons.remove_red_eye_outlined,
        color: valueOrDefault<Color>(
          getJsonField(
                    companyBookingsItem,
                    r'''$.viewed''',
                  ) ==
                  FFAppState().intTrue
              ? FlutterFlowTheme.of(context).customColor1
              : FlutterFlowTheme.of(context).alternate,
          FlutterFlowTheme.of(context).alternate,
        ),
        size: 24,
      ),
    ),
  ],
)
```

**Comment by wenkaifan0720** [comment]
Hi @agreaves. Do you have any idea why this is happening?

**Comment by blondie63** [comment]
Hi @wenkaifan0720 I think this is FF code generation bug, if look in my custom function you can see viewedColor that works fine
I had previously tried using my function, then I thought the new version of FF fixed the problem and I went back to using the classic method.
I'll try again later with the function and I'll update the issue

**Comment by wenkaifan0720** [comment]
I don't know. If you look at the code I just attached, there is no difference between the code for the two buttons. And this is the code I downloaded and ran locally, but the issue persisted.

**Comment by blondie63** [comment]
@wenkaifan0720 I save my homepage to HomePageCompanyCopy then i modified to use a custom function
and works fine !
So for sure is an FF bug :(

**Comment by wenkaifan0720** [comment]
Yes, this is definitely a FF bug. Just not sure it is related to code gen. I think it might be something deeper, so I'll talk to our team about this.

**Comment by blondie63** [comment]
I hope the FF team will appreciate my debug work and take my reports into consideration

**Comment by wenkaifan0720** [comment]
@blondie63. Definitely! We really appreciate our users helping us sorting things out in FF. Thank you for your effort.

**Comment by wenkaifan0720** [comment]
It turns out you are testing your app in dark mode and the custom color 1 is blue in dark mode. There is no bug.

**Comment by blondie63** [comment]
oops. I had not thought of this possibility .. thanks a lot
