### ISSUE TITLE
JSON List not being persisted

### ISSUE THREAD

**Issue by benttropy** [FlutterFlow/flutterflow-issues#651]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created a JSON list string with the Persisted flag on. But whenever I restart the app on my device, this list shows up empty. 

![image](https://user-images.githubusercontent.com/128593243/226875706-1672187a-017d-4477-9e78-697a217de9dc.png)

Whereas I have other simpler datatypes like integers which seem to be persistent.

if (!FFAppState().GImportedContactsInJ.isEmpty) {
  debugPrint("Not Empty");
} else {
  debugPrint("Empty");
}
This was discussed with other FF users here -  https://community.flutterflow.io/c/discuss-and-get-help/json-list-not-being-persisted

### Expected Behavior

The JSON list contents should be persisted across the app shutdown & relaunch.

### Steps To Reproduce

1. In the FF UI, create a Local State JSON variable, with the List & Persisted flags turned on.
2. Start the app, 
3. Fill data into the above variable.
4. Close the app
5. Relaunch
6. Check if variable is empty, and voila! it is empty.

### Bug Report Code

NOTSUREHOWTOGETTHIS

### Context

Trying to persist a JSON list so that I can access data retrieved from user's phone and manipulate the data for the app purpose, across launches of the app

### Environment

```markdown
- FlutterFlow version: 3.1, Flutter: 3.7.3
- Platform: 
- Browser name and version: Samsung phone device
- Operating system and version affected: Android.
Other users also have reported this bug. Refer this discussion please - https://community.flutterflow.io/c/discuss-and-get-help/json-list-not-being-persisted
```

**Comment by benttropy** [comment]
Hi,

No It' not public as of now. Is there some way for me to give only you the
access?
Not just me, another person too on the thread I mentioned in the bug report
also faced the issue.

**Comment by victoriahuang1** [comment]
Hi @benttropy , you can give only the FlutterFlow team access to the project by generating the bug report code.

You can do so by right clicking the offending widget in the widget tree, and then choosing the "Get Bug Report Code" option.

<img width="289" alt="Screenshot 2023-04-03 at 11 42 28 PM" src="https://user-images.githubusercontent.com/16326980/229709674-3541067f-95bf-4c3a-a1b7-ac84debd2d41.png">

**Comment by eugene-orlov** [comment]
The same problem for me, but i saw intresting fact, if i click on blank space on my page, list can be loaded.

**Comment by victoriahuang1** [comment]
You can get the bug report code from any widget.

**Comment by benttropy** [comment]
Hi Victoria

I tried getting the report code, but I get the following error:

[image: image.png]

Couldn't find help on this online. Could you please advise?

**Comment by victoriahuang1** [comment]
Hi @benttropy I can't see your image. Can you try uploading again?

**Comment by benttropy** [comment]
Hi

It just said :
Failure to copy to clipboard: PlatformException(copy_fail, ClipboardsetData
failed, null, null)

**Comment by benttropy** [comment]
I am using Windows 11.

**Comment by victoriahuang1** [comment]
Are you on chrome or another browser? If you are on a different browser, have you checked if the bug report code works on chrome?

**Comment by benttropy** [comment]
Aaah ok
I tried it with Chrome now. I was trying with Opera earlier.

Here's the bug report code:

ITEekcmBw5ZhpbwG1qn+dcFajQMxN0A5beRF1+sbTRA3NZCuOqYpWvT7NlVaXs/geVZ2HFKlhkkDpuj9jvLlK/c4AAyHba5xzqhqcgnyXXKgRrK3DKq0YWglL8dnGkCB0rWjgRRvPrZaZV1pig/GSw==

Does this help?

BTW, I am building the app on Opera browser on a Windows 11. All the
testing though is on a samsung phone via Android studio.

Thanks.

**Comment by benttropy** [comment]
Not sure what all data can you see.

I have a page named MyContactsPage, on the Page Load, I call a custom
Function importPhoneContactsService:

Future importPhoneContactsService(String? userID) async {
  // Add your function code here!
  debugPrint("HELLOOOOOOOOOOOOOOOOOOOOOOO ");
  if (!FFAppState().GImportedContactsInJ.isEmpty) {

Here, GImportedContactsInJ is the JSON list state variable. And whenever I
relaunch (ie. stop and restart the app on the phone), this check of isEmpty
returns true always.

**Comment by benttropy** [comment]
And as I said, I am not the only one who is finding this issue. Other users
too have reported the same behavior:
Link -
https://community.flutterflow.io/c/discuss-and-get-help/json-list-not-being-persisted

**Comment by victoriahuang1** [comment]
Hi @benttropy , this issue should be fixed upon the next deploy.

**Comment by jshrager** [comment]
This is also happening with strings. We have a number of app state strings that are not persisting on Samsung devices, but work fine on Google Pixel.

**Comment by victoriahuang1** [comment]
These issues should all be fixed upon the next deploy

**Comment by benttropy** [comment]
Awesome, thanks!

Would you know when is this next deploy expected?

**Comment by victoriahuang1** [comment]
Should be today!

**Comment by freya-hickman** [comment]
Since the last fix, our app now will not open on our Samsung device it just shows a white screen when you open it - nothing else has changed except the FlutterFlow fixes. Please can you investigate and advise urgently?

**Comment by victoriahuang1** [comment]
Hi @freya-hickman , please open a new github issue with all the details for your project.

In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided. Thank you for your contribution!

**Comment by darkiice** [comment]
Has it been fixed already? I still have this issue when I tried it just now. 

All my app states, except JSON list, correctly persist when loading a new test session. In my use case, I am storing user-specific information using a JSON list. It will render the app useless unless fixed. Also, it completely clears my users' progress & history, which is an irreversible issue. Can someone please advise me on the latest with this bug?

**Comment by victoriahuang1** [comment]
@darkiice the bug affecting this particular issue has been addressed. Here, the issue is not actually related to JSONs at all, but rather the JSON was used in a way that was very error prone (due to race conditions).

There is another persisted app state variable bugfix that has not been deployed yet (see #851). It is hard to say what the issue is, or if it's even either of the ones I mentioned, without more details.

Please open a new github issue with all the details for your project.

In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided. Thank you for your contribution!

**Comment by sgnaguib** [comment]
I'm still having this issue. I have a JSON list that I set to persisted but when I close the app and open it again, any json objects stored in the list are gone

Here is my bug report code:

ITFfz8/q24lPm+FY1r6Jd8ZF9CoWNmUcTeU30+thcw4bI+PmBO0Ue/f8XFtWcuqHTQl2G2GlpGEz+MKLjdriUPYqFxaYR48/yM0MUxDgZD6mVYSMBai0OkBQO/9jCmnC1J6CkyNvKsVsckY962a2F/OQb3qCf9qOYwx5e6fDbOY=

**Comment by victoriahuang1** [comment]
Hi @sgnaguib , thanks for the report. This original bug is not at all related to JSONs though -- I will be updating the name to avoid future confusion.

If you can open a new Github issue with all the required information (reproducible steps, more documentation, ...), then we can look into what is happening.

In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided. Thank you for your contribution!

**Comment by KlausGrosser** [comment]
Im also facing this issue when updating persisted state variables when running the app in test mode, I can see the variables are updated correctly but when I "instant reload" the app, the values are reseted to the default ones.

ITFXkvHlvIZNrsRE7arbKPlKhSgwFjsFUOdEl9caeE0YG4jpE7Mfder+VGpdcMeKd2w/OVWLnkwH0tb4iNrLIPkEZCmqQoNozYdQWzryWnm6VKqDO6uVOHZCI8JhChG8yqS7rgl+XdZeWGwgw1r/cq3qNleeY8aSfxBlZ7vfcPo=
