### ISSUE TITLE
Passing SQLite parameters between pages/components bug

### ISSUE THREAD

**Issue by GinnyVR** [FlutterFlow/flutterflow-issues#6525]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When querying SQLite rows and then passing the row (single) to a component. Flutterflow wont accept choosing the first item in the list an passing it - see picture. Im getting this error trying to pass SQLite data to a listview component.

<img width="1302" height="1080" alt="Image" src="https://github.com/user-attachments/assets/02e3b078-7346-4cb7-bc33-bd7fc2b3b4a1" />

### Expected Behavior

I would expect the ability to choose a single SQLite row and passing it to pages/components.

### Steps to Reproduce

1. Create a page and a listview component.
2. Create an SQlite query e.g: (SELECT * FROM collection WHERE collectionRef = '${collectionRef}')
3. Query rows on the listview component and try and pass the first row to the listview component - Then error occurs.

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8gicjfw49ItbxK+KX9bcFFoGAvIjsja7snkuxEGA0bGIzrOp12dvSlVxFoQuaBa252OWD9mlwxw86MhIfPF+5dJgWqbIh93JVqED3vUTu5b4yVEpOde0BSI5hVG0zFyJ2vvhJ8A+FicmxhwzmYCOmidCzaNIOxDTEgQv+lDIPVj16CGnjBGyRs8xwXAx7eTI5ODEz25eKMrop5yfj/0w==

### Visual documentation

<img width="1302" height="1080" alt="Image" src="https://github.com/user-attachments/assets/5105a9d0-90ee-45af-a3c8-df61d164ea3e" />

<img width="1710" height="1620" alt="Image" src="https://github.com/user-attachments/assets/cee66e8e-b55c-4094-9d50-2b9a3aee185c" />

### Environment

```markdown
- FlutterFlow version: Version 6.3.13 (6.3.13)
- Platform:MacOS Desktop
- Browser name and version: Chrome Version 140.0.7339.186
- Operating system and version affected: macOS Sequoia 15.7
```

**Comment by Alezanello** [comment]
Hello!!

It looks like you’ve already found the correct way to set it up in your project. Can you confirm if the issue is now resolved on your side?

**Comment by GinnyVR** [comment]
The issue is not resolved, flutterflow won’t let me pass the data. I made a quick fix/work around, but would like to be able to pass data this way.
