### ISSUE TITLE
Theme widget style update overrides local widget text

### ISSUE THREAD

**Issue by pictobuddee** [FlutterFlow/flutterflow-issues#791]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1 - I create a theme widget in the Theme Settings (e.g. a button). 
2- I let it keep the button text 'Button'
3 - I apply the theme widget style to two different buttons in the project (See my test buttons on page 'ResetPassword'
4 - I update the button text on both buttons. Since we have translation activated I both enter an english text and a Danish text.

Now **two issues** arise if I try to change the button style via the Theme Widget.

First issue type
1. I update the style (e.g. border radius and elevation) in for the Theme Widget in the Theme Settings
2. I save the update
3. Now the local button texts have again been overridden with the text 'Button'. The local button texts (english and danish) have dissappeared

Second issue type
1. I update the style (e.g. border radius and elevation) in for the Theme Widget in the Theme Settings
2. I deactivate the link for button txt
3. Now the local button text is not overridden, BUT
4. The Danish translation is lost and the buttons show the english texts, AND
5. If I try to change the local button txt the txt in the other button dissappeares.

### Expected Behavior

I expected local updated texts to not be overridden by style updates to the Theme widget style in Theme settings
I expected the local translations to stay intact

### Steps to Reproduce

1 - Create two buttons on a page. 
2 - Activate translations for button names
3 - Create a theme widget button in the Theme Settings
2-  Let it keep the button text 'Button'
3 - Apply the theme widget style to the two buttons
4 - Update the button text on both local buttons and enter an english text and a Danish text.

Now **two issues** arise if I try to change the button style via the Theme Widget.

First issue type
1. Update the style (e.g. border radius and elevation) in for the Theme Widget in the Theme Settings
2. Save the update
3. Now the local button texts have again been overridden with the text 'Button'. The local button texts (english and danish) have dissappeared

Second issue type
1. Update the style (e.g. border radius and elevation) in for the Theme Widget in the Theme Settings
2. Deactivate the link for button txt
3. Local button text is not overridden, BUT
4. The Danish translation is lost and the buttons show the english texts
5.  try to change the local button txt in one button
6. Watch that the txt in the other button dissappeares at the same time

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CiMrlx89OxMcB7rrqdflR/SIXQkg/RY0vlO1Ec00YJ5PMC+wIZ/f7XFRuTde0YWN+M1mKjXEy3M3emvHLCu07NkibbJxJ+qhUZgHNeFuXM5SxO8yZP25/DedUG3aZ15mvuSJ7NtJtWV0j3zmuN/CRVhbbQqbwOnovOPyiC5KK2SrDX1iXc2URm05KZDPz

### Context

I can't work with theme widgets

Also they seem to be deleting conditional settings in our project, but my partner will help report this issue

### Visual documentation

![Skærmbillede 2023-04-20 kl  10 52 03](https://user-images.githubusercontent.com/122773807/233313613-2f98aec2-6a6c-4d2f-8b60-22ce3382c90f.png)
![Skærmbillede 2023-04-20 kl  10 53 01](https://user-images.githubusercontent.com/122773807/233313627-5a1b948f-4839-44c6-9750-25139d14657e.png)

### Additional Info

I hope the above description is detailed enough

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:3.7.3
- Browser name and version: Chrome 112.0.5615.121
- Operating system and version affected: MacOS High Sierra 10.13.6
```

**Comment by pictobuddee** [comment]
Please revisit

**Comment by bulgariamitko** [comment]
When creating the style of the buttons make sure you check the green icon which will link your text. Try that and tell me if it works for you. 
![whats-new2-FlutterFlow](https://github.com/FlutterFlow/flutterflow-issues/assets/7221384/cd3fcae4-e11c-42c7-aaac-eae378b1136a)

**Comment by benjaminathlan** [comment]
I have this issue, not sure this is really the same but I add a screen record just in case : 
https://share.cleanshot.com/4J34KsffysrwvtDmSsxS

https://share.cleanshot.com/DB7ggLt1QLxZVbhTkKh4

I've made sure that my button text is not synced : 
![](https://user-images.githubusercontent.com/7221384/238133668-cd3fcae4-e11c-42c7-aaac-eae378b1136a.png)

**Comment by benjaminathlan** [comment]
Another way to check this bug. 
Go to translations page in settings and some of the fields are broken like this 
![CleanShot 2023-05-20 at 13 58 17](https://github.com/FlutterFlow/flutterflow-issues/assets/173659/341bf7ce-2be1-4f3b-b00b-e8b4ac7c6f41)

**Comment by benjaminathlan** [comment]
I guess this happening when duplicating a elements from theme 
![CleanShot 2023-05-20 at 14 12 46@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/173659/fbc954e3-41c9-44bf-a23c-226c10f8dc72)

I recreated and isolated this bug here : https://app.flutterflow.io/project/test-khu5ar?tab=widgetTree&page=HomePage

**Comment by davidrobvenegas** [comment]
I'm also experiencing this issue. 
When multiple buttons share the same them widget style, If I change the translated label in one button, it updates the translated label for all the other buttons sharing the same widget style.

**Comment by benjaminathlan** [comment]
![CleanShot 2023-05-30 at 22 14 03@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/173659/0ef667f6-0ee9-4573-a283-f3db77a433cb)

Also experiencing it while I use this function

**Comment by wenkaifan0720** [comment]
Hi all. I am able to reproduce the issue and identify the cause. I will be working on a fix this week.

**Comment by wenkaifan0720** [comment]
Hi all. This issue should be fixed in our next update. Thank you all for the detailed reports!

**Comment by zjjt** [comment]
@wenkaifan0720 Unfortunately it still persists.No matter what i try i can't make it change without affecting the other. i have a button widget that uses the same translations as the other which is on another page. Here is the code displayed in flutterflow 

````

 text: FFLocalizations.of(context).getText(
                            'er5wlb3v' /* text */,
                          ),
````
as you can see both of them use the same getText id.

**Comment by benjaminathlan** [comment]
I confirm that i still have the bug

**Comment by bulgariamitko** [comment]
I will re-open this issue so the FF team can look at it again.

**Comment by wenkaifan0720** [comment]
Hi @zjjt, @benjaminathlan. I just tested with a new project (https://app.flutterflow.io/project/theme-test-4w9m1u) and don't see the issue happening. One thing I forgot to mention is that we couldn't fix the existing widgets that had this issue, so you need to recreate them to ensure they have unique ids of their own.

**Comment by zjjt** [comment]
@wenkaifan0720 Understood..for now i erased all translations from my project. I will redo for one page and revert.

**Comment by benjaminathlan** [comment]
@wenkaifan0720 is that mean I should shut down my project ? its a 10month project

**Comment by wenkaifan0720** [comment]
Hi @benjaminathlan. Not at all, but it does require some work on your end. You need to recreate the buttons that use theme widgets (so they would have a unique translation id and not be linked together anymore). I apologize for the inconvenience.

**Comment by wenkaifan0720** [comment]
Hi @dcarvalho-bridge-mt. Could you provide me with more details? A bug report code for the page that is still having the issue, and also the version&platform of FF that you are using. Thank you.

**Comment by wenkaifan0720** [comment]
@dcarvalho-bridge-mt. At least it is good to know that the issue is gone for new widgets. I do apologize for the confusion and trouble that this issue has caused for all of you.

**Comment by Doetheman** [comment]
I have the link off yet when I apply the widget theme for my text field it just replaces the text anyway lol

**Comment by faxioman** [comment]
Also with new created button, this issue is still present

**Comment by faxioman** [comment]
Fixed after removing ALL the buttons in my project.

**Comment by paour** [comment]
We're observing the same issue, which causes us to have to choose between not using i18n or not using theme widgets, both of which are not acceptable.

Could this be be reopened until a proper fix is implemented?

**Comment by lianr7** [comment]
The error persists, as we can see.

The alternative I found was to click on "copy widget style" and paste it into it or into another one that I want to correct. Then I add the texts for each language again.
However, if I make any changes to the widget style, everyone has the problem again

**Comment by jbarnabe** [comment]
Same problem here :(
