### ISSUE TITLE
Some assets are not shown properly

### ISSUE THREAD

**Issue by arash-vaziri** [FlutterFlow/flutterflow-issues#810]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- In design mode my header image not covering the whole area, despite the fact that settings are correct, and I know it because before update to this new version it was working properly

- Some are not showing properly in asset library and edit mode and test mode, despite the fact that they are shown correctly in side panel
- The animation with transparent parts is not rendered correctly , as it is rendered in solid white color on those parts. 

### Expected Behavior

- Showing assets correctly as before.
- Affect the coverage setting for images
- Maintain transparency for svg animation

### Steps to Reproduce

1. Go to : https://app.flutterflow.io/project/imin-9lep78
2. go to the edit mode on Intro page
3. you cannot see the svg icon in the center of screen
4. Also you can see a white border around the top image, which should not be there.
5. In assets library, the icon_02,icon_03, and icon_04 are not showing properly but you can see them in side panel of Intro_01 page
6. The white circle animation is showing in a solid color white background, In Get_Cellphone page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESj8nl5YpgouFD7qX5KuxAhQIgQ0QnU7gnlO1ucx4YGJTyE5YUPPT7bUNKTMOCdHxiImGZhkkC+tmLj/HXVsJePUutUa5H0JVAZzrKbES6bpTQO5CKSnBAP8VYfVCE1Jm4ngpSWbFfLFIN2Ey1Nq3qNleeY8aSfxBlZ7vfcPo=

### Context

I cannot continue to work and create new pages, while current pages are broken.

### Visual documentation

https://user-images.githubusercontent.com/95966719/234202324-d0f2ce6a-d7de-4f40-9863-01e295437939.mp4

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Google Chrome 112.0.56
- Operating system and version affected: Ms.Windows 10
```

**Comment by hariprasadms** [comment]
Hi @arash-vaziri - Thanks for posting the issue. I have tested it and I can re-produce the issue with the same SVG file. I also have tested it with few more different SVG files and the issue is in-consistent. It mostly looks like specific to SVG file resolutions and its image dimensions. I can mark this as a bug. As an work around I can suggest, change the size and resolution of the svg image and see if that can help you. 

Developers Note - The above same SVG files which are not loading properly, are also not displaying properly in FF editor in project media. See below

Sample SVG files - https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/17435678/234271513-725bf7fd-9928-4508-9d3c-5c81edd6cb9f.png">

**Comment by arash-vaziri** [comment]
Thank you for notifying the problem, 
aside from that, there is a problem with image coverage over the content as well. Is it related to svg ptoblem as well ?!

**Comment by sinasalek** [comment]
Any update on this?!

**Comment by sinasalek** [comment]
The new release also did not fix this issue

**Comment by katherineqian** [comment]
Experienced this issue too (assets that load everywhere else except not rendering on Flutter) and raised a ticket on the package -- https://github.com/dnfield/flutter_svg/issues/997
Which was resolved by https://github.com/dnfield/vector_graphics/pull/218 -- so should be fixed on other assets as well.

**Comment by lullahub** [comment]
Hi there,

I'm still having this issue - I've tried to resize the SVG files, but they still won't render, even after dropping the resolution right down.

The file is the main logo for the whole app, so it's essential it renders in some form!!

Any help would be much appreciated.


![Screenshot 2023-11-15 144048](https://github.com/FlutterFlow/flutterflow-issues/assets/150933195/27e5aa53-b4e5-4f6d-9f4f-ef9d8cf54305)
