### ISSUE TITLE
Firebase Phone Auth/Signin doesn't work on iOS - stuck on initial page and throws exception

### ISSUE THREAD

**Issue by subgutti** [FlutterFlow/flutterflow-issues#837]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

iOS App gets stuck on the home page and throws the exception in log (attached). 

### Expected Behavior

iOS App should automatically route to the "enter OTP/verification" code screen

### Steps to Reproduce

1. Follow the steps here to setup the Phone signin/auth https://docs.flutterflow.io/data-and-backend/firebase/authentication/phone-sign-in
2. Use the test mode to verify that phone signin/auth works for the android/web emulator
3. Download the code
4. Follow the steps here to setup the iOS development https://docs.flutterflow.io/deploying-your-app/testing-your-app/testing-your-app
5. Go into the downloaded code folder (step#3)
6. Open terminal and execute "flutter pub get" and "flutter packages pub run build_runner build --delete-conflicting-outputs"
7. Open iOS simulator or connect an iOS device 
8. Install the app: "flutter run"
9. Once the app loads, enter the phone number and click on the "verify" button
10. Notice that the app takes you to recaptcha
11. On return from recaptcha, the app gets stuck on the home page and doesn't automatically navigate to "enter OTP" screen
11. In the terminal log (from step#8), you will see the reported exception

Here is the project I started from scratch and ran into this error (also ran into same problem in my main project so created this from scratch)
https://app.flutterflow.io/project/test-phone-auth-l0sr7h

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48z/Hqx89grs9f1s+Nde9VimERNm07a5E/mOxDRRc8KOPdOoYUP8+kM0RpTenhTXw7PmeKnWoW0t78ivHxVO5dC06ZR75OybhAZhbJWj+jVpCpFJWgPGt5EeFQCmGO3MCzpxB4KbZ0SiUdw2aQItisdCzXGLr1OUdFDq/LZO4=

### Context

Phone signin/auth is the first and the most important step. This is blocking us from releasing the app. 

### Visual documentation

[error.txt](https://github.com/FlutterFlow/flutterflow-issues/files/11370305/error.txt)
![Screenshot 2023-05-01 at 11 32 03 PM](https://user-images.githubusercontent.com/1458358/235595410-a2e1db95-ac29-40e2-b8ad-233b6f6a76c7.png)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: iPhone (device or simulator)
- Browser name and version: Not related to browser
- Operating system and version affected: iOS 16.4
```

**Comment by subgutti** [comment]
Here is the video to show the error 

https://user-images.githubusercontent.com/1458358/235596670-f1a3aefa-35f7-4a8c-98e2-6a5ca088343d.mov

**Comment by subgutti** [comment]
@hariprasadms Ok. Thanks.

As Phone signin/auth is the first and the most important step, can the team prioritize the fix? This issue will block everyone using FlutterFlow. (We are currently blocked in releasing our app.)

**Comment by victoriahuang1** [comment]
Hi @subgutti thanks for the report. This issue should be fixed upon the next deploy!

**Comment by subgutti** [comment]
@victoriahuang1 I still get the same exception when I test it on iOS. 

Is the fix in a particular FlutterFlow release? The website shows the FlutterFlow version as v3.1 released on May 4th.
<img width="349" alt="Screenshot 2023-05-08 at 10 21 52 PM" src="https://user-images.githubusercontent.com/1458358/237001505-9c7d3213-8876-439a-9ce4-1355209f458e.png">

**Comment by victoriahuang1** [comment]
The deploy has not gone through yet. We need to wait for the next deploy (no date, but should be within a week).

**Comment by subgutti** [comment]
@victoriahuang1 I see that there is a new release on May 11th but still see the exception. Is it not part of this release? How will I know when the fix is deployed?

<img width="337" alt="Screenshot 2023-05-11 at 1 40 31 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1458358/0ab2a7fb-07f4-4e6d-b862-51435eb046e8">

**Comment by subgutti** [comment]
@victoriahuang1 I see that there is a new release on May 11th but still see the exception. Is it not part of this release? How will I know when the fix is deployed?

<img width="354" alt="Screenshot 2023-05-11 at 1 42 17 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1458358/148803dd-3e65-47ab-81ec-c0ab4fb8a1be">

**Comment by victoriahuang1** [comment]
This was a one off deploy for something unrelated to bugfixes. Still no date set for deploy, but I have confirmed that this particular bugfix has not been deployed yet. Should be within the next week

**Comment by subgutti** [comment]
@victoriahuang1 when is the expected release date?

**Comment by subgutti** [comment]
@victoriahuang1 @hariprasadms is the fix part of the latest release? 

If yes, I can still reproduce the issue. Can you please reopen the issue?

If no, when can I expect the fix?

https://community.flutterflow.io/c/whats-new-in-flutterflow/what-s-new-in-flutterflow-may-19th-2023

**Comment by greenrocks-development** [comment]
Hello, I'm commenting on this bug report because I am having the exact same issue now, although with a different error message in the console. Have their been any recent changes that might have prompted this bug to appear again?

**Comment by alex-gugu** [comment]
I am also having the exact same issue. Please look into this.

**Comment by PanSalut** [comment]
Same issue here. Can we look into it?

**Comment by arjusmoon860** [comment]
Same issue. Can we please reopen?

**Comment by arjusmoon860** [comment]
Any fixes? @subgutti

**Comment by Gabanelli** [comment]
Same issue

**Comment by Flexpro23** [comment]
Same issue, the app on test flight crashes

**Comment by milorad-j** [comment]
Same issue. When number is passed and Auth happens, new window opens and closes and the app returns to Homescreen which is frozen...
