### ISSUE TITLE
Get document property operation does not respect nullability

### ISSUE THREAD

**Issue by wenkaifan0720** [FlutterFlow/flutterflow-issues#999]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you want to use a variable which is one of the property fields of a document, then the code gen would think the document can not be null.

### Expected Behavior

The document should be treated as nullable, and code gen should use `?.` instead of `!.` when getting the property of the document, and ask for a default value on the front end.  

### Steps to Reproduce

Everything is in the test project that I prepared. Once run, you will see the null value error. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gobxZ0brpLfpqhQIgQ0QnU7gnlO1ucx4bB72rBO0Md87BQ0NKTMfnSmNYfFGJrGY1+PT6huH2GPBfZA2ZQak60JVAFwrKbF+hVYi1DpCKX3BSI+FYfVS/yMG3rB4lWLBuSU4S2lyHNq3qNleeY8aSfxBlZ7vfcPo=

### Context

The app will crash with a null value error.

### Visual documentation

![iScreen Shoter - Google Chrome - 230616151636](https://github.com/FlutterFlow/flutterflow-issues/assets/112435854/1ee410a6-c538-4502-a12f-290d81397743)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

**Comment by Franco98404** [comment]
I have this problem too

**Comment by aemelyanovff** [comment]
Fixed in the next update!

**Comment by Franco98404** [comment]
Hello @aemelyanovff @wenkaifan0720 I am still facing this issue. The fix was included in the last version of the July 6?

**Comment by Franco98404** [comment]
Hello again, the issue is not fixed yet, can you check the issue @agreaves @bulgariamitko ?

https://www.loom.com/share/a6e2230dbdac472a856867c13d276cb0

**Comment by aemelyanovff** [comment]
@Franco98404 I don't think it's the same issue. Please create a new issue with new Steps to Reproduce.
